issue-845-fix: true
with-expecter: true
resolve-type-alias: false
dir: "{{ .InterfaceDir }}/../mocks"
outpkg: "mocks"
filename: "mock_{{ .InterfaceName | snakecase | lower }}.go"
mockname: "{{ .InterfaceName }}"
packages:
  github.com/agglayer/aggkit/agglayer:
    config:
      inpackage: true
      dir: "{{ .InterfaceDir }}"
      outpkg: "{{ .PackageName }}"
    interfaces:
      AgglayerClientInterface:
        config:
          mockname: AgglayerClientMock
          filename: mock_agglayer_client.go
  github.com/agglayer/aggkit/aggoracle/types:
    config:
      all: true
  github.com/agglayer/aggkit/aggsender/db:
    config:
      all: true
  github.com/agglayer/aggkit/types:
    config:
      dir: "{{ .InterfaceDir }}/mocks"
      all: true
  github.com/agglayer/aggkit/aggsender/prover:
    config:
      all: true
  github.com/agglayer/aggkit/aggsender/grpc:
    config:
      all: true
  buf.build/gen/go/agglayer/provers/grpc/go/aggkit/prover/v1/proverv1grpc:
    config:
      all: true
      dir: "../aggsender/mocks"
  buf.build/gen/go/agglayer/agglayer/grpc/go/agglayer/node/v1/nodev1grpc:
    config:
      dir: "../agglayer/mocks"
    interfaces:
      NodeStateServiceClient:
        config:
      ConfigurationServiceClient:
        config:
      CertificateSubmissionServiceClient:
        config:
  github.com/agglayer/aggkit/aggsender/rpc:
    config:
      all: true
  github.com/agglayer/aggkit/aggsender/types:
    config:
      all: true
  github.com/agglayer/aggkit/bridgesync:
    config:
      dir: "{{ .InterfaceDir }}/mocks"
    interfaces:
      ReorgDetector:
  github.com/agglayer/aggkit/l1infotreesync:
    config:
      dir: "{{ .InterfaceDir }}/mocks"
    interfaces:
      EthClienter:
  github.com/agglayer/aggkit/reorgdetector:
    config:
      dir: "{{ .InterfaceDir }}"
      outpkg: "{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}Mock"
    interfaces:
      EthClient:
  github.com/agglayer/aggkit/bridgeservice:
    config:
      dir: "{{ .InterfaceDir }}/mocks"
      include-regex: "\\w+er\\b"
      exclude-regex: "^UintParam$"
  github.com/agglayer/aggkit/sync:
    config:
      dir: "{{ .InterfaceDir }}"
      outpkg: "{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}Mock"
      inpackage: true
    interfaces:
      ReorgDetector:
        configs:
          - dir: "{{ .InterfaceDir }}/../l1infotreesync/mocks"
            outpkg: "mocks"
            mockname: "{{ .InterfaceName }}Mock"
            inpackage: false
          - dir: "{{ .InterfaceDir }}"
            outpkg: "{{ .PackageName }}"
            mockname: "{{ .InterfaceName }}Mock"
      processorInterface:
        config:
          mockname: "ProcessorMock"
      EVMDownloaderInterface:
        config:
          mockname: "EVMDownloaderMock"
      Downloader:
        config:
          mockname: "DownloaderMock"
      EthClienter:
        config:
          mockname: "L2Mock"
  github.com/agglayer/aggkit/db/compatibility:
    config:
      dir: "{{ .InterfaceDir }}/mocks"
      all: true
      exclude:
        - RuntimeDataGetterFunc
  github.com/agglayer/aggkit/etherman:
    config:
      dir: "{{ .InterfaceDir }}/mocks"
      all: true
