with-expecter: true
packages:
  github.com/agglayer/aggkit/agglayer:
    config:
      inpackage: True
      dir: "{{ .InterfaceDir }}"
      outpkg: "{{ .PackageName }}"
    interfaces:
      AgglayerClientInterface:
        config:
          mockname: AgglayerClientMock
          filename: mock_agglayer_client.go
  github.com/agglayer/aggkit/aggoracle/chaingersender:
    config:
      dir: "{{ .InterfaceDir }}/../mocks"
      outpkg: "mocks"
    interfaces:
      EthTxManager:
        config:
          mockname: EthTxManagerMock
          filename: mock_ethtxmanager.go
      L2GERManagerContract:
        config:
          mockname: L2GERManagerMock
          filename: mock_l2germanager.go
  github.com/agglayer/aggkit/aggsender/db:
    config:
      dir: "{{.InterfaceDir}}/../mocks"
      outpkg: "mocks"
      filename: "{{ .InterfaceName | snakecase | lower }}.go"
      mockname: "{{ .InterfaceName }}"
    interfaces:
      AggSenderStorage:
        config:
  github.com/agglayer/aggkit/aggsender/rpc:
    config:
      dir: "{{.InterfaceDir}}/../mocks"
      outpkg: "mocks"
      mockname: "{{ .InterfaceName }}"
      filename: "{{ .InterfaceName | snakecase | lower }}.go"
    interfaces:
      aggsenderInterface:
        config:
      aggsenderStorer:
        config:
  github.com/agglayer/aggkit/aggsender/types:
    config:
      dir: "{{.InterfaceDir}}/../mocks"
      outpkg: "mocks"
      mockname: "{{ .InterfaceName }}"
      filename: "{{ .InterfaceName | snakecase | lower }}.go"
    interfaces:
      BlockNotifier:
        config:
      EpochNotifier:
        config:
      EthClient:
        config:
      GenericSubscriber:
        config:
      L1InfoTreeSyncer:
        config:
      L2BridgeSyncer:
        config:
      Logger:
        config:
  github.com/agglayer/aggkit/bridgesync:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: "mocks"
      mockname: "{{ .InterfaceName }}"
      filename: "{{ .InterfaceName | snakecase | lower }}.go"
    interfaces:
      ReorgDetector:
        config:
      EthClienter:
        config: