issue-845-fix: true
with-expecter: true
resolve-type-alias: false
dir: "{{ .InterfaceDir }}/../mocks"
outpkg: "mocks"
filename: "mock_{{ .InterfaceName | snakecase | lower }}.go"
mockname: "{{ .InterfaceName }}"
packages:
  github.com/agglayer/aggkit/agglayer:
    config:
      inpackage: true
      dir: "{{ .InterfaceDir }}"
      outpkg: "{{ .PackageName }}"
    interfaces:
      AgglayerClientInterface:
        config:
          mockname: AgglayerClientMock
          filename: mock_agglayer_client.go
  github.com/agglayer/aggkit/aggoracle/chaingersender:
    config:
    interfaces:
      EthTxManager:
        configs:
          - mockname: EthTxManagerMock
            filename: mock_ethtxmanager.go
          - mockname: EthTxManagerMock
            filename: mock_ethtxmanager.go
            dir: "{{ .InterfaceDir }}/../../test/helpers"
            outpkg: "helpers"
      L2GERManagerContract:
        config:
          mockname: L2GERManagerMock
          filename: mock_l2germanager.go
  github.com/agglayer/aggkit/aggsender/db:
    config:
      all: true
  github.com/agglayer/aggkit/aggsender/rpc:
    config:
      all: true
  github.com/agglayer/aggkit/aggsender/types:
    config:
      all: true
  github.com/agglayer/aggkit/bridgesync:
    config:
      dir: "{{ .InterfaceDir }}/mocks"
    interfaces:
      ReorgDetector:
      EthClienter:
  github.com/agglayer/aggkit/l1infotreesync:
    config:
      dir: "{{ .InterfaceDir }}/mocks"
    interfaces:
      EthClienter:
  github.com/agglayer/aggkit/reorgdetector:
    config:
      dir: "{{ .InterfaceDir }}"
      outpkg: "{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}Mock"
    interfaces:
      EthClient:
  github.com/agglayer/aggkit/rpc/client:
    config:
      all: true
  github.com/agglayer/aggkit/rpc:
    config:
      dir: "{{ .InterfaceDir }}/mocks"
      all: true
  github.com/agglayer/aggkit/sync:
    config:
      dir: "{{ .InterfaceDir }}"
      outpkg: "{{ .PackageName }}"
      mockname: "{{ .InterfaceName }}Mock"
      inpackage: true
    interfaces:
      ReorgDetector:
        configs:
          - dir: "{{ .InterfaceDir }}/../l1infotreesync/mocks"
            outpkg: "mocks"
            mockname: "{{ .InterfaceName }}Mock"
            inpackage: false
          - dir: "{{ .InterfaceDir }}"
            outpkg: "{{ .PackageName }}"
            mockname: "{{ .InterfaceName }}Mock"
      processorInterface:
        config:
          mockname: "ProcessorMock"
      evmDownloaderFull:
        config:
          mockname: "EVMDownloaderMock"
      EthClienter:
        config:
          mockname: "L2Mock"
  github.com/agglayer/go_signer/signer/types:
    config:
      dir: "../aggsender/mocks_signer"
      all: true
  github.com/agglayer/aggkit/db/compatibility:
    config:
      dir: "{{ .InterfaceDir }}/mocks"
      all: true
  github.com/agglayer/aggkit/etherman:
    config:
      dir: "{{ .InterfaceDir }}/mocks"
      all: true

