// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	bridgesync "github.com/agglayer/aggkit/bridgesync"

	mock "github.com/stretchr/testify/mock"
)

// BridgeSource is an autogenerated mock type for the BridgeSource type
type BridgeSource struct {
	mock.Mock
}

type BridgeSource_Expecter struct {
	mock *mock.Mock
}

func (_m *BridgeSource) EXPECT() *BridgeSource_Expecter {
	return &BridgeSource_Expecter{mock: &_m.Mock}
}

// GetBridges provides a mock function with given fields: ctx, fromBlock, toBlock
func (_m *BridgeSource) GetBridges(ctx context.Context, fromBlock uint64, toBlock uint64) ([]bridgesync.Bridge, error) {
	ret := _m.Called(ctx, fromBlock, toBlock)

	if len(ret) == 0 {
		panic("no return value specified for GetBridges")
	}

	var r0 []bridgesync.Bridge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]bridgesync.Bridge, error)); ok {
		return rf(ctx, fromBlock, toBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []bridgesync.Bridge); ok {
		r0 = rf(ctx, fromBlock, toBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bridgesync.Bridge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, fromBlock, toBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BridgeSource_GetBridges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBridges'
type BridgeSource_GetBridges_Call struct {
	*mock.Call
}

// GetBridges is a helper method to define mock.On call
//   - ctx context.Context
//   - fromBlock uint64
//   - toBlock uint64
func (_e *BridgeSource_Expecter) GetBridges(ctx interface{}, fromBlock interface{}, toBlock interface{}) *BridgeSource_GetBridges_Call {
	return &BridgeSource_GetBridges_Call{Call: _e.mock.On("GetBridges", ctx, fromBlock, toBlock)}
}

func (_c *BridgeSource_GetBridges_Call) Run(run func(ctx context.Context, fromBlock uint64, toBlock uint64)) *BridgeSource_GetBridges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *BridgeSource_GetBridges_Call) Return(_a0 []bridgesync.Bridge, _a1 error) *BridgeSource_GetBridges_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BridgeSource_GetBridges_Call) RunAndReturn(run func(context.Context, uint64, uint64) ([]bridgesync.Bridge, error)) *BridgeSource_GetBridges_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastProcessedBlock provides a mock function with given fields: ctx
func (_m *BridgeSource) GetLastProcessedBlock(ctx context.Context) (uint64, bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastProcessedBlock")
	}

	var r0 uint64
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (uint64, bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BridgeSource_GetLastProcessedBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastProcessedBlock'
type BridgeSource_GetLastProcessedBlock_Call struct {
	*mock.Call
}

// GetLastProcessedBlock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BridgeSource_Expecter) GetLastProcessedBlock(ctx interface{}) *BridgeSource_GetLastProcessedBlock_Call {
	return &BridgeSource_GetLastProcessedBlock_Call{Call: _e.mock.On("GetLastProcessedBlock", ctx)}
}

func (_c *BridgeSource_GetLastProcessedBlock_Call) Run(run func(ctx context.Context)) *BridgeSource_GetLastProcessedBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *BridgeSource_GetLastProcessedBlock_Call) Return(_a0 uint64, _a1 bool, _a2 error) *BridgeSource_GetLastProcessedBlock_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *BridgeSource_GetLastProcessedBlock_Call) RunAndReturn(run func(context.Context) (uint64, bool, error)) *BridgeSource_GetLastProcessedBlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewBridgeSource creates a new instance of BridgeSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBridgeSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *BridgeSource {
	mock := &BridgeSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
