// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	aggoracletypes "github.com/agglayer/aggkit/aggoracle/types"

	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/autoclaim/types"
)

// TransactionManagerFactory is an autogenerated mock type for the TransactionManagerFactory type
type TransactionManagerFactory struct {
	mock.Mock
}

type TransactionManagerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionManagerFactory) EXPECT() *TransactionManagerFactory_Expecter {
	return &TransactionManagerFactory_Expecter{mock: &_m.Mock}
}

// NewEthTxManager provides a mock function with given fields: ctx, target
func (_m *TransactionManagerFactory) NewEthTxManager(ctx context.Context, target types.ClaimerTarget) (aggoracletypes.EthTxManager, error) {
	ret := _m.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for NewEthTxManager")
	}

	var r0 aggoracletypes.EthTxManager
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ClaimerTarget) (aggoracletypes.EthTxManager, error)); ok {
		return rf(ctx, target)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.ClaimerTarget) aggoracletypes.EthTxManager); ok {
		r0 = rf(ctx, target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aggoracletypes.EthTxManager)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.ClaimerTarget) error); ok {
		r1 = rf(ctx, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionManagerFactory_NewEthTxManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewEthTxManager'
type TransactionManagerFactory_NewEthTxManager_Call struct {
	*mock.Call
}

// NewEthTxManager is a helper method to define mock.On call
//   - ctx context.Context
//   - target types.ClaimerTarget
func (_e *TransactionManagerFactory_Expecter) NewEthTxManager(ctx interface{}, target interface{}) *TransactionManagerFactory_NewEthTxManager_Call {
	return &TransactionManagerFactory_NewEthTxManager_Call{Call: _e.mock.On("NewEthTxManager", ctx, target)}
}

func (_c *TransactionManagerFactory_NewEthTxManager_Call) Run(run func(ctx context.Context, target types.ClaimerTarget)) *TransactionManagerFactory_NewEthTxManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.ClaimerTarget))
	})
	return _c
}

func (_c *TransactionManagerFactory_NewEthTxManager_Call) Return(_a0 aggoracletypes.EthTxManager, _a1 error) *TransactionManagerFactory_NewEthTxManager_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TransactionManagerFactory_NewEthTxManager_Call) RunAndReturn(run func(context.Context, types.ClaimerTarget) (aggoracletypes.EthTxManager, error)) *TransactionManagerFactory_NewEthTxManager_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionManagerFactory creates a new instance of TransactionManagerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionManagerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionManagerFactory {
	mock := &TransactionManagerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
