// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/autoclaim/types"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// EnqueueRequest provides a mock function with given fields: ctx, request
func (_m *Storage) EnqueueRequest(ctx context.Context, request types.AutoClaimRequest) (*types.AutoClaimRequest, bool, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueRequest")
	}

	var r0 *types.AutoClaimRequest
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AutoClaimRequest) (*types.AutoClaimRequest, bool, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AutoClaimRequest) *types.AutoClaimRequest); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AutoClaimRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AutoClaimRequest) bool); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, types.AutoClaimRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Storage_EnqueueRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueRequest'
type Storage_EnqueueRequest_Call struct {
	*mock.Call
}

// EnqueueRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - request types.AutoClaimRequest
func (_e *Storage_Expecter) EnqueueRequest(ctx interface{}, request interface{}) *Storage_EnqueueRequest_Call {
	return &Storage_EnqueueRequest_Call{Call: _e.mock.On("EnqueueRequest", ctx, request)}
}

func (_c *Storage_EnqueueRequest_Call) Run(run func(ctx context.Context, request types.AutoClaimRequest)) *Storage_EnqueueRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.AutoClaimRequest))
	})
	return _c
}

func (_c *Storage_EnqueueRequest_Call) Return(_a0 *types.AutoClaimRequest, _a1 bool, _a2 error) *Storage_EnqueueRequest_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Storage_EnqueueRequest_Call) RunAndReturn(run func(context.Context, types.AutoClaimRequest) (*types.AutoClaimRequest, bool, error)) *Storage_EnqueueRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequest provides a mock function with given fields: ctx, key
func (_m *Storage) GetRequest(ctx context.Context, key types.RequestKey) (*types.AutoClaimRequest, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 *types.AutoClaimRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestKey) (*types.AutoClaimRequest, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestKey) *types.AutoClaimRequest); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AutoClaimRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.RequestKey) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type Storage_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - key types.RequestKey
func (_e *Storage_Expecter) GetRequest(ctx interface{}, key interface{}) *Storage_GetRequest_Call {
	return &Storage_GetRequest_Call{Call: _e.mock.On("GetRequest", ctx, key)}
}

func (_c *Storage_GetRequest_Call) Run(run func(ctx context.Context, key types.RequestKey)) *Storage_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RequestKey))
	})
	return _c
}

func (_c *Storage_GetRequest_Call) Return(_a0 *types.AutoClaimRequest, _a1 error) *Storage_GetRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_GetRequest_Call) RunAndReturn(run func(context.Context, types.RequestKey) (*types.AutoClaimRequest, error)) *Storage_GetRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecoverableRequests provides a mock function with given fields: ctx, filter
func (_m *Storage) ListRecoverableRequests(ctx context.Context, filter types.RecoveryFilter) (*types.RequestPage, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListRecoverableRequests")
	}

	var r0 *types.RequestPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RecoveryFilter) (*types.RequestPage, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.RecoveryFilter) *types.RequestPage); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.RequestPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.RecoveryFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_ListRecoverableRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecoverableRequests'
type Storage_ListRecoverableRequests_Call struct {
	*mock.Call
}

// ListRecoverableRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - filter types.RecoveryFilter
func (_e *Storage_Expecter) ListRecoverableRequests(ctx interface{}, filter interface{}) *Storage_ListRecoverableRequests_Call {
	return &Storage_ListRecoverableRequests_Call{Call: _e.mock.On("ListRecoverableRequests", ctx, filter)}
}

func (_c *Storage_ListRecoverableRequests_Call) Run(run func(ctx context.Context, filter types.RecoveryFilter)) *Storage_ListRecoverableRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RecoveryFilter))
	})
	return _c
}

func (_c *Storage_ListRecoverableRequests_Call) Return(_a0 *types.RequestPage, _a1 error) *Storage_ListRecoverableRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_ListRecoverableRequests_Call) RunAndReturn(run func(context.Context, types.RecoveryFilter) (*types.RequestPage, error)) *Storage_ListRecoverableRequests_Call {
	_c.Call.Return(run)
	return _c
}

// ListRequests provides a mock function with given fields: ctx, filter
func (_m *Storage) ListRequests(ctx context.Context, filter types.RequestFilter) (*types.RequestPage, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListRequests")
	}

	var r0 *types.RequestPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestFilter) (*types.RequestPage, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestFilter) *types.RequestPage); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.RequestPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.RequestFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_ListRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRequests'
type Storage_ListRequests_Call struct {
	*mock.Call
}

// ListRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - filter types.RequestFilter
func (_e *Storage_Expecter) ListRequests(ctx interface{}, filter interface{}) *Storage_ListRequests_Call {
	return &Storage_ListRequests_Call{Call: _e.mock.On("ListRequests", ctx, filter)}
}

func (_c *Storage_ListRequests_Call) Run(run func(ctx context.Context, filter types.RequestFilter)) *Storage_ListRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RequestFilter))
	})
	return _c
}

func (_c *Storage_ListRequests_Call) Return(_a0 *types.RequestPage, _a1 error) *Storage_ListRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_ListRequests_Call) RunAndReturn(run func(context.Context, types.RequestFilter) (*types.RequestPage, error)) *Storage_ListRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RecordManualDecision provides a mock function with given fields: ctx, key, decision
func (_m *Storage) RecordManualDecision(ctx context.Context, key types.RequestKey, decision types.PolicyDecision) error {
	ret := _m.Called(ctx, key, decision)

	if len(ret) == 0 {
		panic("no return value specified for RecordManualDecision")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestKey, types.PolicyDecision) error); ok {
		r0 = rf(ctx, key, decision)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_RecordManualDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordManualDecision'
type Storage_RecordManualDecision_Call struct {
	*mock.Call
}

// RecordManualDecision is a helper method to define mock.On call
//   - ctx context.Context
//   - key types.RequestKey
//   - decision types.PolicyDecision
func (_e *Storage_Expecter) RecordManualDecision(ctx interface{}, key interface{}, decision interface{}) *Storage_RecordManualDecision_Call {
	return &Storage_RecordManualDecision_Call{Call: _e.mock.On("RecordManualDecision", ctx, key, decision)}
}

func (_c *Storage_RecordManualDecision_Call) Run(run func(ctx context.Context, key types.RequestKey, decision types.PolicyDecision)) *Storage_RecordManualDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RequestKey), args[2].(types.PolicyDecision))
	})
	return _c
}

func (_c *Storage_RecordManualDecision_Call) Return(_a0 error) *Storage_RecordManualDecision_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_RecordManualDecision_Call) RunAndReturn(run func(context.Context, types.RequestKey, types.PolicyDecision) error) *Storage_RecordManualDecision_Call {
	_c.Call.Return(run)
	return _c
}

// RecordPolicyDecision provides a mock function with given fields: ctx, key, decision
func (_m *Storage) RecordPolicyDecision(ctx context.Context, key types.RequestKey, decision types.PolicyDecision) error {
	ret := _m.Called(ctx, key, decision)

	if len(ret) == 0 {
		panic("no return value specified for RecordPolicyDecision")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestKey, types.PolicyDecision) error); ok {
		r0 = rf(ctx, key, decision)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_RecordPolicyDecision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordPolicyDecision'
type Storage_RecordPolicyDecision_Call struct {
	*mock.Call
}

// RecordPolicyDecision is a helper method to define mock.On call
//   - ctx context.Context
//   - key types.RequestKey
//   - decision types.PolicyDecision
func (_e *Storage_Expecter) RecordPolicyDecision(ctx interface{}, key interface{}, decision interface{}) *Storage_RecordPolicyDecision_Call {
	return &Storage_RecordPolicyDecision_Call{Call: _e.mock.On("RecordPolicyDecision", ctx, key, decision)}
}

func (_c *Storage_RecordPolicyDecision_Call) Run(run func(ctx context.Context, key types.RequestKey, decision types.PolicyDecision)) *Storage_RecordPolicyDecision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RequestKey), args[2].(types.PolicyDecision))
	})
	return _c
}

func (_c *Storage_RecordPolicyDecision_Call) Return(_a0 error) *Storage_RecordPolicyDecision_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_RecordPolicyDecision_Call) RunAndReturn(run func(context.Context, types.RequestKey, types.PolicyDecision) error) *Storage_RecordPolicyDecision_Call {
	_c.Call.Return(run)
	return _c
}

// RecordTransactionAttempt provides a mock function with given fields: ctx, key, attempt
func (_m *Storage) RecordTransactionAttempt(ctx context.Context, key types.RequestKey, attempt types.TransactionAttempt) error {
	ret := _m.Called(ctx, key, attempt)

	if len(ret) == 0 {
		panic("no return value specified for RecordTransactionAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestKey, types.TransactionAttempt) error); ok {
		r0 = rf(ctx, key, attempt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_RecordTransactionAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordTransactionAttempt'
type Storage_RecordTransactionAttempt_Call struct {
	*mock.Call
}

// RecordTransactionAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - key types.RequestKey
//   - attempt types.TransactionAttempt
func (_e *Storage_Expecter) RecordTransactionAttempt(ctx interface{}, key interface{}, attempt interface{}) *Storage_RecordTransactionAttempt_Call {
	return &Storage_RecordTransactionAttempt_Call{Call: _e.mock.On("RecordTransactionAttempt", ctx, key, attempt)}
}

func (_c *Storage_RecordTransactionAttempt_Call) Run(run func(ctx context.Context, key types.RequestKey, attempt types.TransactionAttempt)) *Storage_RecordTransactionAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RequestKey), args[2].(types.TransactionAttempt))
	})
	return _c
}

func (_c *Storage_RecordTransactionAttempt_Call) Return(_a0 error) *Storage_RecordTransactionAttempt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_RecordTransactionAttempt_Call) RunAndReturn(run func(context.Context, types.RequestKey, types.TransactionAttempt) error) *Storage_RecordTransactionAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// SaveProof provides a mock function with given fields: ctx, key, proof
func (_m *Storage) SaveProof(ctx context.Context, key types.RequestKey, proof types.ClaimProof) error {
	ret := _m.Called(ctx, key, proof)

	if len(ret) == 0 {
		panic("no return value specified for SaveProof")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestKey, types.ClaimProof) error); ok {
		r0 = rf(ctx, key, proof)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_SaveProof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveProof'
type Storage_SaveProof_Call struct {
	*mock.Call
}

// SaveProof is a helper method to define mock.On call
//   - ctx context.Context
//   - key types.RequestKey
//   - proof types.ClaimProof
func (_e *Storage_Expecter) SaveProof(ctx interface{}, key interface{}, proof interface{}) *Storage_SaveProof_Call {
	return &Storage_SaveProof_Call{Call: _e.mock.On("SaveProof", ctx, key, proof)}
}

func (_c *Storage_SaveProof_Call) Run(run func(ctx context.Context, key types.RequestKey, proof types.ClaimProof)) *Storage_SaveProof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RequestKey), args[2].(types.ClaimProof))
	})
	return _c
}

func (_c *Storage_SaveProof_Call) Return(_a0 error) *Storage_SaveProof_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_SaveProof_Call) RunAndReturn(run func(context.Context, types.RequestKey, types.ClaimProof) error) *Storage_SaveProof_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionRequest provides a mock function with given fields: ctx, key, from, to, now
func (_m *Storage) TransitionRequest(ctx context.Context, key types.RequestKey, from types.RequestStatus, to types.RequestStatus, now time.Time) (*types.AutoClaimRequest, error) {
	ret := _m.Called(ctx, key, from, to, now)

	if len(ret) == 0 {
		panic("no return value specified for TransitionRequest")
	}

	var r0 *types.AutoClaimRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestKey, types.RequestStatus, types.RequestStatus, time.Time) (*types.AutoClaimRequest, error)); ok {
		return rf(ctx, key, from, to, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestKey, types.RequestStatus, types.RequestStatus, time.Time) *types.AutoClaimRequest); ok {
		r0 = rf(ctx, key, from, to, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AutoClaimRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.RequestKey, types.RequestStatus, types.RequestStatus, time.Time) error); ok {
		r1 = rf(ctx, key, from, to, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storage_TransitionRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionRequest'
type Storage_TransitionRequest_Call struct {
	*mock.Call
}

// TransitionRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - key types.RequestKey
//   - from types.RequestStatus
//   - to types.RequestStatus
//   - now time.Time
func (_e *Storage_Expecter) TransitionRequest(ctx interface{}, key interface{}, from interface{}, to interface{}, now interface{}) *Storage_TransitionRequest_Call {
	return &Storage_TransitionRequest_Call{Call: _e.mock.On("TransitionRequest", ctx, key, from, to, now)}
}

func (_c *Storage_TransitionRequest_Call) Run(run func(ctx context.Context, key types.RequestKey, from types.RequestStatus, to types.RequestStatus, now time.Time)) *Storage_TransitionRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RequestKey), args[2].(types.RequestStatus), args[3].(types.RequestStatus), args[4].(time.Time))
	})
	return _c
}

func (_c *Storage_TransitionRequest_Call) Return(_a0 *types.AutoClaimRequest, _a1 error) *Storage_TransitionRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storage_TransitionRequest_Call) RunAndReturn(run func(context.Context, types.RequestKey, types.RequestStatus, types.RequestStatus, time.Time) (*types.AutoClaimRequest, error)) *Storage_TransitionRequest_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastError provides a mock function with given fields: ctx, key, lastError, now
func (_m *Storage) UpdateLastError(ctx context.Context, key types.RequestKey, lastError string, now time.Time) error {
	ret := _m.Called(ctx, key, lastError, now)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestKey, string, time.Time) error); ok {
		r0 = rf(ctx, key, lastError, now)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storage_UpdateLastError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastError'
type Storage_UpdateLastError_Call struct {
	*mock.Call
}

// UpdateLastError is a helper method to define mock.On call
//   - ctx context.Context
//   - key types.RequestKey
//   - lastError string
//   - now time.Time
func (_e *Storage_Expecter) UpdateLastError(ctx interface{}, key interface{}, lastError interface{}, now interface{}) *Storage_UpdateLastError_Call {
	return &Storage_UpdateLastError_Call{Call: _e.mock.On("UpdateLastError", ctx, key, lastError, now)}
}

func (_c *Storage_UpdateLastError_Call) Run(run func(ctx context.Context, key types.RequestKey, lastError string, now time.Time)) *Storage_UpdateLastError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RequestKey), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *Storage_UpdateLastError_Call) Return(_a0 error) *Storage_UpdateLastError_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_UpdateLastError_Call) RunAndReturn(run func(context.Context, types.RequestKey, string, time.Time) error) *Storage_UpdateLastError_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
