package exit_certificate

import (
	"context"
	"fmt"

	agglayertypes "github.com/agglayer/aggkit/agglayer/types"
	"github.com/agglayer/aggkit/log"
	"github.com/agglayer/aggkit/tools/exit_certificate/bridgesyncerlite"
	"github.com/ethereum/go-ethereum/common"
)

// buildLiteTreeFromCertificate builds the local exit tree by inserting the certificate's bridge
// exits into the lite DB — in their given order, continuing the deposit counts after Step G1's
// genesis→fork bridges — and returns the tree root and the per-exit metadata used for each leaf, in
// the same order. This is the single way the local exit tree (the sqlite the claimer later reads for
// proofs) is built: the off-chain path uses it to compute the NewLocalExitRoot, and the shadow-fork
// path uses it to produce the root it cross-checks against the contract's getRoot().
//
// The leaf encoding mirrors what the bridge contract emits: a native exit (no token info / gas
// token) uses the gas token as origin; an ERC-20 exit uses its TokenInfo origin. Each leaf carries
// the raw generatedMetadata for its exit (generated by generateMetadata, replicating bridgeAsset) —
// the lite syncer keccak256-hashes it for the leaf, exactly as the contract does. If the generated
// metadata is wrong for an exit, the shadow-fork root cross-check (treeRoot vs getRoot) detects it.
// generatedMetadata must be aligned by index with certificate.BridgeExits.
func buildLiteTreeFromCertificate(
	ctx context.Context, cfg *Config, certificate *agglayertypes.Certificate,
	forkBlock uint64, gasTokenNetwork uint32, gasTokenAddress common.Address, generatedMetadata [][]byte,
) (common.Hash, [][]byte, error) {
	exits := certificate.BridgeExits
	if len(generatedMetadata) != len(exits) {
		return common.Hash{}, nil, fmt.Errorf("generated metadata count %d does not match bridge exit count %d",
			len(generatedMetadata), len(exits))
	}

	nextDepositCount, err := liteForkNextDepositCount(ctx, cfg)
	if err != nil {
		return common.Hash{}, nil, err
	}

	leaves := make([]bridgesyncerlite.BridgeLeaf, len(exits))
	metadatas := make([][]byte, len(exits))
	for i, be := range exits {
		originNetwork, originAddr := gasTokenNetwork, gasTokenAddress
		if be.TokenInfo != nil && be.TokenInfo.OriginTokenAddress != (common.Address{}) {
			originNetwork = be.TokenInfo.OriginNetwork
			originAddr = be.TokenInfo.OriginTokenAddress
		}
		leaves[i] = bridgesyncerlite.BridgeLeaf{
			// Synthetic block position: the leaves do not exist on a chain here. BlockNum/BlockPos do
			// not affect the tree root (only leaf hash and deposit-count order do); they just need to be
			// present and distinct, so we place them all in the block right after the fork.
			BlockNum:           forkBlock + 1,
			BlockPos:           uint64(i),
			LeafType:           uint8(be.LeafType),
			OriginNetwork:      originNetwork,
			OriginAddress:      originAddr,
			DestinationNetwork: be.DestinationNetwork,
			DestinationAddress: be.DestinationAddress,
			Amount:             be.Amount,
			Metadata:           generatedMetadata[i],
			DepositCount:       nextDepositCount + uint32(i),
		}
		metadatas[i] = generatedMetadata[i]
	}

	ler, err := buildLiteTreeWithReplayed(ctx, cfg, leaves)
	if err != nil {
		return common.Hash{}, nil, err
	}
	log.Infof("Local exit root from lite tree of %d certificate exits: %s", len(exits), ler.Hex())
	return ler, metadatas, nil
}

// liteForkNextDepositCount returns the deposit count the first certificate exit should get: one past
// the highest deposit count Step G1 synced into the lite DB (i.e. the number of genesis→fork
// bridges). It opens the G1 lite DB read-only (no chain access).
func liteForkNextDepositCount(ctx context.Context, cfg *Config) (uint32, error) {
	dbPath := g1LiteDBPath(cfg)
	if !fileExists(dbPath) {
		return 0, fmt.Errorf("lite syncer DB %s not found (run Step G1 first)", dbPath)
	}
	syncer, err := bridgesyncerlite.New(ctx, bridgesyncerlite.Config{DBPath: dbPath},
		log.WithFields("module", "exit-cert-bridgesyncerlite"))
	if err != nil {
		return 0, fmt.Errorf("open lite syncer DB: %w", err)
	}
	defer func() {
		if cerr := syncer.Close(); cerr != nil {
			log.Warnf("error closing lite bridge syncer: %v", cerr)
		}
	}()
	nextDepositCount, err := syncer.NextDepositCount(ctx)
	if err != nil {
		return 0, fmt.Errorf("read genesis→fork next deposit count: %w", err)
	}
	return nextDepositCount, nil
}

// buildLiteTreeWithReplayed builds the full exit tree for Step G2 and returns its root.
//
// Step G1 persisted the L2 bridges from genesis up to the shadow-fork block (no tree yet) into the
// G1 lite DB. Here we copy that DB to the G2 lite DB (so G1's DB stays intact and reusable across G2
// re-runs) and, on the copy, **insert the replayed bridges directly** — they were already captured
// from the replay's BridgeEvents, so no second pass over Anvil is needed (the syncer runs DB-only,
// it never touches the chain). We then build the whole exit tree once from the full set
// (genesis→fork plus replayed); the resulting root is what RunStepG2 cross-checks against the forked
// contract's getRoot().
func buildLiteTreeWithReplayed(
	ctx context.Context, cfg *Config, replayedLeaves []bridgesyncerlite.BridgeLeaf,
) (common.Hash, error) {
	srcPath := g1LiteDBPath(cfg)
	if !fileExists(srcPath) {
		return common.Hash{}, fmt.Errorf("lite syncer DB %s not found (run Step G1 first)", srcPath)
	}

	// Work on a copy so Step G1's DB (genesis→fork bridges) is left untouched and a G2 re-run starts
	// from a clean copy rather than a tree already built/appended by a previous run.
	dbPath := g2LiteDBPath(cfg)
	if err := copyLiteDB(srcPath, dbPath); err != nil {
		return common.Hash{}, fmt.Errorf("copy lite syncer DB for Step G2: %w", err)
	}
	log.Infof("Copied lite syncer DB %s → %s for Step G2", srcPath, dbPath)

	// DB-only syncer (no RPCURL): we only persist the already-collected bridges and build the tree,
	// so it must not make any Anvil calls.
	syncer, err := bridgesyncerlite.New(ctx, bridgesyncerlite.Config{
		DBPath: dbPath,
	}, log.WithFields("module", "exit-cert-bridgesyncerlite"))
	if err != nil {
		return common.Hash{}, fmt.Errorf("reopen lite syncer DB: %w", err)
	}
	defer func() {
		if cerr := syncer.Close(); cerr != nil {
			log.Warnf("error closing lite bridge syncer: %v", cerr)
		}
	}()

	// Persist the replayed bridges alongside the genesis→fork ones Step G1 stored (StoreBridges sorts
	// them by deposit count, so their order here does not matter).
	if err := syncer.StoreBridges(ctx, replayedLeaves); err != nil {
		return common.Hash{}, fmt.Errorf("store replayed bridges: %w", err)
	}

	// Build the whole exit tree once, now that every bridge is persisted.
	ler, err := syncer.BuildTree(ctx)
	if err != nil {
		return common.Hash{}, fmt.Errorf("build lite exit tree: %w", err)
	}
	log.Infof("Built lite exit tree with %d replayed bridges; local exit root = %s",
		len(replayedLeaves), ler.Hex())
	return ler, nil
}
