// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RollupContractReader is an autogenerated mock type for the RollupContractReader type
type RollupContractReader struct {
	mock.Mock
}

type RollupContractReader_Expecter struct {
	mock *mock.Mock
}

func (_m *RollupContractReader) EXPECT() *RollupContractReader_Expecter {
	return &RollupContractReader_Expecter{mock: &_m.Mock}
}

// AggchainMetadata provides a mock function with given fields: ctx, key
func (_m *RollupContractReader) AggchainMetadata(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for AggchainMetadata")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RollupContractReader_AggchainMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggchainMetadata'
type RollupContractReader_AggchainMetadata_Call struct {
	*mock.Call
}

// AggchainMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *RollupContractReader_Expecter) AggchainMetadata(ctx interface{}, key interface{}) *RollupContractReader_AggchainMetadata_Call {
	return &RollupContractReader_AggchainMetadata_Call{Call: _e.mock.On("AggchainMetadata", ctx, key)}
}

func (_c *RollupContractReader_AggchainMetadata_Call) Run(run func(ctx context.Context, key string)) *RollupContractReader_AggchainMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RollupContractReader_AggchainMetadata_Call) Return(_a0 string, _a1 error) *RollupContractReader_AggchainMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RollupContractReader_AggchainMetadata_Call) RunAndReturn(run func(context.Context, string) (string, error)) *RollupContractReader_AggchainMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// TrustedSequencerURL provides a mock function with given fields: ctx
func (_m *RollupContractReader) TrustedSequencerURL(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TrustedSequencerURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RollupContractReader_TrustedSequencerURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrustedSequencerURL'
type RollupContractReader_TrustedSequencerURL_Call struct {
	*mock.Call
}

// TrustedSequencerURL is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RollupContractReader_Expecter) TrustedSequencerURL(ctx interface{}) *RollupContractReader_TrustedSequencerURL_Call {
	return &RollupContractReader_TrustedSequencerURL_Call{Call: _e.mock.On("TrustedSequencerURL", ctx)}
}

func (_c *RollupContractReader_TrustedSequencerURL_Call) Run(run func(ctx context.Context)) *RollupContractReader_TrustedSequencerURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RollupContractReader_TrustedSequencerURL_Call) Return(_a0 string, _a1 error) *RollupContractReader_TrustedSequencerURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RollupContractReader_TrustedSequencerURL_Call) RunAndReturn(run func(context.Context) (string, error)) *RollupContractReader_TrustedSequencerURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewRollupContractReader creates a new instance of RollupContractReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRollupContractReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *RollupContractReader {
	mock := &RollupContractReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
