// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// EthChainReader is an autogenerated mock type for the EthChainReader type
type EthChainReader struct {
	mock.Mock
}

type EthChainReader_Expecter struct {
	mock *mock.Mock
}

func (_m *EthChainReader) EXPECT() *EthChainReader_Expecter {
	return &EthChainReader_Expecter{mock: &_m.Mock}
}

// HeaderByHash provides a mock function with given fields: ctx, hash
func (_m *EthChainReader) HeaderByHash(ctx context.Context, hash common.Hash) (*types.Header, error) {
	ret := _m.Called(ctx, hash)

	if len(ret) == 0 {
		panic("no return value specified for HeaderByHash")
	}

	var r0 *types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash) (*types.Header, error)); ok {
		return rf(ctx, hash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash) *types.Header); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Hash) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EthChainReader_HeaderByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeaderByHash'
type EthChainReader_HeaderByHash_Call struct {
	*mock.Call
}

// HeaderByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - hash common.Hash
func (_e *EthChainReader_Expecter) HeaderByHash(ctx interface{}, hash interface{}) *EthChainReader_HeaderByHash_Call {
	return &EthChainReader_HeaderByHash_Call{Call: _e.mock.On("HeaderByHash", ctx, hash)}
}

func (_c *EthChainReader_HeaderByHash_Call) Run(run func(ctx context.Context, hash common.Hash)) *EthChainReader_HeaderByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash))
	})
	return _c
}

func (_c *EthChainReader_HeaderByHash_Call) Return(_a0 *types.Header, _a1 error) *EthChainReader_HeaderByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EthChainReader_HeaderByHash_Call) RunAndReturn(run func(context.Context, common.Hash) (*types.Header, error)) *EthChainReader_HeaderByHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewEthChainReader creates a new instance of EthChainReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEthChainReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *EthChainReader {
	mock := &EthChainReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
