// Code generated by mockery v2.53.3. DO NOT EDIT.

package l1infotreesync

import (
	types "github.com/agglayer/aggkit/types"
	mock "github.com/stretchr/testify/mock"
)

// DownloaderInterfaceMock is an autogenerated mock type for the DownloaderInterface type
type DownloaderInterfaceMock struct {
	mock.Mock
}

type DownloaderInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DownloaderInterfaceMock) EXPECT() *DownloaderInterfaceMock_Expecter {
	return &DownloaderInterfaceMock_Expecter{mock: &_m.Mock}
}

// Finality provides a mock function with no fields
func (_m *DownloaderInterfaceMock) Finality() types.BlockNumberFinality {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Finality")
	}

	var r0 types.BlockNumberFinality
	if rf, ok := ret.Get(0).(func() types.BlockNumberFinality); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.BlockNumberFinality)
	}

	return r0
}

// DownloaderInterfaceMock_Finality_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finality'
type DownloaderInterfaceMock_Finality_Call struct {
	*mock.Call
}

// Finality is a helper method to define mock.On call
func (_e *DownloaderInterfaceMock_Expecter) Finality() *DownloaderInterfaceMock_Finality_Call {
	return &DownloaderInterfaceMock_Finality_Call{Call: _e.mock.On("Finality")}
}

func (_c *DownloaderInterfaceMock_Finality_Call) Run(run func()) *DownloaderInterfaceMock_Finality_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DownloaderInterfaceMock_Finality_Call) Return(_a0 types.BlockNumberFinality) *DownloaderInterfaceMock_Finality_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DownloaderInterfaceMock_Finality_Call) RunAndReturn(run func() types.BlockNumberFinality) *DownloaderInterfaceMock_Finality_Call {
	_c.Call.Return(run)
	return _c
}

// NewDownloaderInterfaceMock creates a new instance of DownloaderInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDownloaderInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DownloaderInterfaceMock {
	mock := &DownloaderInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
