// Code generated by mockery v2.53.5. DO NOT EDIT.

package l1infotreesync

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DriverInterfaceMock is an autogenerated mock type for the DriverInterface type
type DriverInterfaceMock struct {
	mock.Mock
}

type DriverInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DriverInterfaceMock) EXPECT() *DriverInterfaceMock_Expecter {
	return &DriverInterfaceMock_Expecter{mock: &_m.Mock}
}

// Sync provides a mock function with given fields: ctx
func (_m *DriverInterfaceMock) Sync(ctx context.Context) {
	_m.Called(ctx)
}

// DriverInterfaceMock_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type DriverInterfaceMock_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DriverInterfaceMock_Expecter) Sync(ctx interface{}) *DriverInterfaceMock_Sync_Call {
	return &DriverInterfaceMock_Sync_Call{Call: _e.mock.On("Sync", ctx)}
}

func (_c *DriverInterfaceMock_Sync_Call) Run(run func(ctx context.Context)) *DriverInterfaceMock_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DriverInterfaceMock_Sync_Call) Return() *DriverInterfaceMock_Sync_Call {
	_c.Call.Return()
	return _c
}

func (_c *DriverInterfaceMock_Sync_Call) RunAndReturn(run func(context.Context)) *DriverInterfaceMock_Sync_Call {
	_c.Run(run)
	return _c
}

// NewDriverInterfaceMock creates a new instance of DriverInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriverInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DriverInterfaceMock {
	mock := &DriverInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
