// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// RetryHandler is an autogenerated mock type for the RetryHandler type
type RetryHandler struct {
	mock.Mock
}

type RetryHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *RetryHandler) EXPECT() *RetryHandler_Expecter {
	return &RetryHandler_Expecter{mock: &_m.Mock}
}

// Delay provides a mock function with given fields: attempt
func (_m *RetryHandler) Delay(attempt int) time.Duration {
	ret := _m.Called(attempt)

	if len(ret) == 0 {
		panic("no return value specified for Delay")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(int) time.Duration); ok {
		r0 = rf(attempt)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// RetryHandler_Delay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delay'
type RetryHandler_Delay_Call struct {
	*mock.Call
}

// Delay is a helper method to define mock.On call
//   - attempt int
func (_e *RetryHandler_Expecter) Delay(attempt interface{}) *RetryHandler_Delay_Call {
	return &RetryHandler_Delay_Call{Call: _e.mock.On("Delay", attempt)}
}

func (_c *RetryHandler_Delay_Call) Run(run func(attempt int)) *RetryHandler_Delay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *RetryHandler_Delay_Call) Return(_a0 time.Duration) *RetryHandler_Delay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryHandler_Delay_Call) RunAndReturn(run func(int) time.Duration) *RetryHandler_Delay_Call {
	_c.Call.Return(run)
	return _c
}

// MustExecuteAttempt provides a mock function with given fields: attempt
func (_m *RetryHandler) MustExecuteAttempt(attempt int) bool {
	ret := _m.Called(attempt)

	if len(ret) == 0 {
		panic("no return value specified for MustExecuteAttempt")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(attempt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RetryHandler_MustExecuteAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustExecuteAttempt'
type RetryHandler_MustExecuteAttempt_Call struct {
	*mock.Call
}

// MustExecuteAttempt is a helper method to define mock.On call
//   - attempt int
func (_e *RetryHandler_Expecter) MustExecuteAttempt(attempt interface{}) *RetryHandler_MustExecuteAttempt_Call {
	return &RetryHandler_MustExecuteAttempt_Call{Call: _e.mock.On("MustExecuteAttempt", attempt)}
}

func (_c *RetryHandler_MustExecuteAttempt_Call) Run(run func(attempt int)) *RetryHandler_MustExecuteAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *RetryHandler_MustExecuteAttempt_Call) Return(_a0 bool) *RetryHandler_MustExecuteAttempt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryHandler_MustExecuteAttempt_Call) RunAndReturn(run func(int) bool) *RetryHandler_MustExecuteAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with no fields
func (_m *RetryHandler) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RetryHandler_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type RetryHandler_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *RetryHandler_Expecter) String() *RetryHandler_String_Call {
	return &RetryHandler_String_Call{Call: _e.mock.On("String")}
}

func (_c *RetryHandler_String_Call) Run(run func()) *RetryHandler_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RetryHandler_String_Call) Return(_a0 string) *RetryHandler_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryHandler_String_Call) RunAndReturn(run func() string) *RetryHandler_String_Call {
	_c.Call.Return(run)
	return _c
}

// StringAttempt provides a mock function with given fields: attempt
func (_m *RetryHandler) StringAttempt(attempt int) string {
	ret := _m.Called(attempt)

	if len(ret) == 0 {
		panic("no return value specified for StringAttempt")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(attempt)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RetryHandler_StringAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StringAttempt'
type RetryHandler_StringAttempt_Call struct {
	*mock.Call
}

// StringAttempt is a helper method to define mock.On call
//   - attempt int
func (_e *RetryHandler_Expecter) StringAttempt(attempt interface{}) *RetryHandler_StringAttempt_Call {
	return &RetryHandler_StringAttempt_Call{Call: _e.mock.On("StringAttempt", attempt)}
}

func (_c *RetryHandler_StringAttempt_Call) Run(run func(attempt int)) *RetryHandler_StringAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *RetryHandler_StringAttempt_Call) Return(_a0 string) *RetryHandler_StringAttempt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryHandler_StringAttempt_Call) RunAndReturn(run func(int) string) *RetryHandler_StringAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with no fields
func (_m *RetryHandler) Validate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetryHandler_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type RetryHandler_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *RetryHandler_Expecter) Validate() *RetryHandler_Validate_Call {
	return &RetryHandler_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *RetryHandler_Validate_Call) Run(run func()) *RetryHandler_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RetryHandler_Validate_Call) Return(_a0 error) *RetryHandler_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryHandler_Validate_Call) RunAndReturn(run func() error) *RetryHandler_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewRetryHandler creates a new instance of RetryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRetryHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *RetryHandler {
	mock := &RetryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
