// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/agglayer/aggkit/common/types"
	mock "github.com/stretchr/testify/mock"
)

// RetryPolicyConfigurer is an autogenerated mock type for the RetryPolicyConfigurer type
type RetryPolicyConfigurer struct {
	mock.Mock
}

type RetryPolicyConfigurer_Expecter struct {
	mock *mock.Mock
}

func (_m *RetryPolicyConfigurer) EXPECT() *RetryPolicyConfigurer_Expecter {
	return &RetryPolicyConfigurer_Expecter{mock: &_m.Mock}
}

// Brief provides a mock function with no fields
func (_m *RetryPolicyConfigurer) Brief() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Brief")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RetryPolicyConfigurer_Brief_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Brief'
type RetryPolicyConfigurer_Brief_Call struct {
	*mock.Call
}

// Brief is a helper method to define mock.On call
func (_e *RetryPolicyConfigurer_Expecter) Brief() *RetryPolicyConfigurer_Brief_Call {
	return &RetryPolicyConfigurer_Brief_Call{Call: _e.mock.On("Brief")}
}

func (_c *RetryPolicyConfigurer_Brief_Call) Run(run func()) *RetryPolicyConfigurer_Brief_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RetryPolicyConfigurer_Brief_Call) Return(_a0 string) *RetryPolicyConfigurer_Brief_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryPolicyConfigurer_Brief_Call) RunAndReturn(run func() string) *RetryPolicyConfigurer_Brief_Call {
	_c.Call.Return(run)
	return _c
}

// NewRetryHandler provides a mock function with no fields
func (_m *RetryPolicyConfigurer) NewRetryHandler() (types.RetryHandler, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewRetryHandler")
	}

	var r0 types.RetryHandler
	var r1 error
	if rf, ok := ret.Get(0).(func() (types.RetryHandler, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() types.RetryHandler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.RetryHandler)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetryPolicyConfigurer_NewRetryHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRetryHandler'
type RetryPolicyConfigurer_NewRetryHandler_Call struct {
	*mock.Call
}

// NewRetryHandler is a helper method to define mock.On call
func (_e *RetryPolicyConfigurer_Expecter) NewRetryHandler() *RetryPolicyConfigurer_NewRetryHandler_Call {
	return &RetryPolicyConfigurer_NewRetryHandler_Call{Call: _e.mock.On("NewRetryHandler")}
}

func (_c *RetryPolicyConfigurer_NewRetryHandler_Call) Run(run func()) *RetryPolicyConfigurer_NewRetryHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RetryPolicyConfigurer_NewRetryHandler_Call) Return(_a0 types.RetryHandler, _a1 error) *RetryPolicyConfigurer_NewRetryHandler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RetryPolicyConfigurer_NewRetryHandler_Call) RunAndReturn(run func() (types.RetryHandler, error)) *RetryPolicyConfigurer_NewRetryHandler_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with no fields
func (_m *RetryPolicyConfigurer) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RetryPolicyConfigurer_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type RetryPolicyConfigurer_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *RetryPolicyConfigurer_Expecter) String() *RetryPolicyConfigurer_String_Call {
	return &RetryPolicyConfigurer_String_Call{Call: _e.mock.On("String")}
}

func (_c *RetryPolicyConfigurer_String_Call) Run(run func()) *RetryPolicyConfigurer_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RetryPolicyConfigurer_String_Call) Return(_a0 string) *RetryPolicyConfigurer_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryPolicyConfigurer_String_Call) RunAndReturn(run func() string) *RetryPolicyConfigurer_String_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with no fields
func (_m *RetryPolicyConfigurer) Validate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetryPolicyConfigurer_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type RetryPolicyConfigurer_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *RetryPolicyConfigurer_Expecter) Validate() *RetryPolicyConfigurer_Validate_Call {
	return &RetryPolicyConfigurer_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *RetryPolicyConfigurer_Validate_Call) Run(run func()) *RetryPolicyConfigurer_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RetryPolicyConfigurer_Validate_Call) Return(_a0 error) *RetryPolicyConfigurer_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryPolicyConfigurer_Validate_Call) RunAndReturn(run func() error) *RetryPolicyConfigurer_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewRetryPolicyConfigurer creates a new instance of RetryPolicyConfigurer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRetryPolicyConfigurer(t interface {
	mock.TestingT
	Cleanup(func())
}) *RetryPolicyConfigurer {
	mock := &RetryPolicyConfigurer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
