// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	big "math/big"

	common "github.com/ethereum/go-ethereum/common"

	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/claimsync/types"
)

// Claimer is an autogenerated mock type for the Claimer type
type Claimer struct {
	mock.Mock
}

type Claimer_Expecter struct {
	mock *mock.Mock
}

func (_m *Claimer) EXPECT() *Claimer_Expecter {
	return &Claimer_Expecter{mock: &_m.Mock}
}

// GetClaimsByGER provides a mock function with given fields: ctx, globalExitRoot
func (_m *Claimer) GetClaimsByGER(ctx context.Context, globalExitRoot common.Hash) ([]*types.Claim, error) {
	ret := _m.Called(ctx, globalExitRoot)

	if len(ret) == 0 {
		panic("no return value specified for GetClaimsByGER")
	}

	var r0 []*types.Claim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash) ([]*types.Claim, error)); ok {
		return rf(ctx, globalExitRoot)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Hash) []*types.Claim); ok {
		r0 = rf(ctx, globalExitRoot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Claim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Hash) error); ok {
		r1 = rf(ctx, globalExitRoot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Claimer_GetClaimsByGER_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaimsByGER'
type Claimer_GetClaimsByGER_Call struct {
	*mock.Call
}

// GetClaimsByGER is a helper method to define mock.On call
//   - ctx context.Context
//   - globalExitRoot common.Hash
func (_e *Claimer_Expecter) GetClaimsByGER(ctx interface{}, globalExitRoot interface{}) *Claimer_GetClaimsByGER_Call {
	return &Claimer_GetClaimsByGER_Call{Call: _e.mock.On("GetClaimsByGER", ctx, globalExitRoot)}
}

func (_c *Claimer_GetClaimsByGER_Call) Run(run func(ctx context.Context, globalExitRoot common.Hash)) *Claimer_GetClaimsByGER_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Hash))
	})
	return _c
}

func (_c *Claimer_GetClaimsByGER_Call) Return(_a0 []*types.Claim, _a1 error) *Claimer_GetClaimsByGER_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Claimer_GetClaimsByGER_Call) RunAndReturn(run func(context.Context, common.Hash) ([]*types.Claim, error)) *Claimer_GetClaimsByGER_Call {
	_c.Call.Return(run)
	return _c
}

// GetClaimsPaged provides a mock function with given fields: ctx, page, pageSize, networkIDs, globalIndex
func (_m *Claimer) GetClaimsPaged(ctx context.Context, page uint32, pageSize uint32, networkIDs []uint32, globalIndex *big.Int) ([]*types.Claim, int, error) {
	ret := _m.Called(ctx, page, pageSize, networkIDs, globalIndex)

	if len(ret) == 0 {
		panic("no return value specified for GetClaimsPaged")
	}

	var r0 []*types.Claim
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, []uint32, *big.Int) ([]*types.Claim, int, error)); ok {
		return rf(ctx, page, pageSize, networkIDs, globalIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, []uint32, *big.Int) []*types.Claim); ok {
		r0 = rf(ctx, page, pageSize, networkIDs, globalIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Claim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, []uint32, *big.Int) int); ok {
		r1 = rf(ctx, page, pageSize, networkIDs, globalIndex)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint32, uint32, []uint32, *big.Int) error); ok {
		r2 = rf(ctx, page, pageSize, networkIDs, globalIndex)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Claimer_GetClaimsPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClaimsPaged'
type Claimer_GetClaimsPaged_Call struct {
	*mock.Call
}

// GetClaimsPaged is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint32
//   - pageSize uint32
//   - networkIDs []uint32
//   - globalIndex *big.Int
func (_e *Claimer_Expecter) GetClaimsPaged(ctx interface{}, page interface{}, pageSize interface{}, networkIDs interface{}, globalIndex interface{}) *Claimer_GetClaimsPaged_Call {
	return &Claimer_GetClaimsPaged_Call{Call: _e.mock.On("GetClaimsPaged", ctx, page, pageSize, networkIDs, globalIndex)}
}

func (_c *Claimer_GetClaimsPaged_Call) Run(run func(ctx context.Context, page uint32, pageSize uint32, networkIDs []uint32, globalIndex *big.Int)) *Claimer_GetClaimsPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].([]uint32), args[4].(*big.Int))
	})
	return _c
}

func (_c *Claimer_GetClaimsPaged_Call) Return(_a0 []*types.Claim, _a1 int, _a2 error) *Claimer_GetClaimsPaged_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Claimer_GetClaimsPaged_Call) RunAndReturn(run func(context.Context, uint32, uint32, []uint32, *big.Int) ([]*types.Claim, int, error)) *Claimer_GetClaimsPaged_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetClaimsPaged provides a mock function with given fields: ctx, page, pageSize, globalIndex
func (_m *Claimer) GetSetClaimsPaged(ctx context.Context, page uint32, pageSize uint32, globalIndex *big.Int) ([]*types.SetClaim, int, error) {
	ret := _m.Called(ctx, page, pageSize, globalIndex)

	if len(ret) == 0 {
		panic("no return value specified for GetSetClaimsPaged")
	}

	var r0 []*types.SetClaim
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, *big.Int) ([]*types.SetClaim, int, error)); ok {
		return rf(ctx, page, pageSize, globalIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, *big.Int) []*types.SetClaim); ok {
		r0 = rf(ctx, page, pageSize, globalIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.SetClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, *big.Int) int); ok {
		r1 = rf(ctx, page, pageSize, globalIndex)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint32, uint32, *big.Int) error); ok {
		r2 = rf(ctx, page, pageSize, globalIndex)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Claimer_GetSetClaimsPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetClaimsPaged'
type Claimer_GetSetClaimsPaged_Call struct {
	*mock.Call
}

// GetSetClaimsPaged is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint32
//   - pageSize uint32
//   - globalIndex *big.Int
func (_e *Claimer_Expecter) GetSetClaimsPaged(ctx interface{}, page interface{}, pageSize interface{}, globalIndex interface{}) *Claimer_GetSetClaimsPaged_Call {
	return &Claimer_GetSetClaimsPaged_Call{Call: _e.mock.On("GetSetClaimsPaged", ctx, page, pageSize, globalIndex)}
}

func (_c *Claimer_GetSetClaimsPaged_Call) Run(run func(ctx context.Context, page uint32, pageSize uint32, globalIndex *big.Int)) *Claimer_GetSetClaimsPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(*big.Int))
	})
	return _c
}

func (_c *Claimer_GetSetClaimsPaged_Call) Return(_a0 []*types.SetClaim, _a1 int, _a2 error) *Claimer_GetSetClaimsPaged_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Claimer_GetSetClaimsPaged_Call) RunAndReturn(run func(context.Context, uint32, uint32, *big.Int) ([]*types.SetClaim, int, error)) *Claimer_GetSetClaimsPaged_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnsetClaimsPaged provides a mock function with given fields: ctx, page, pageSize, globalIndex
func (_m *Claimer) GetUnsetClaimsPaged(ctx context.Context, page uint32, pageSize uint32, globalIndex *big.Int) ([]*types.UnsetClaim, int, error) {
	ret := _m.Called(ctx, page, pageSize, globalIndex)

	if len(ret) == 0 {
		panic("no return value specified for GetUnsetClaimsPaged")
	}

	var r0 []*types.UnsetClaim
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, *big.Int) ([]*types.UnsetClaim, int, error)); ok {
		return rf(ctx, page, pageSize, globalIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, uint32, *big.Int) []*types.UnsetClaim); ok {
		r0 = rf(ctx, page, pageSize, globalIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.UnsetClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, uint32, *big.Int) int); ok {
		r1 = rf(ctx, page, pageSize, globalIndex)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint32, uint32, *big.Int) error); ok {
		r2 = rf(ctx, page, pageSize, globalIndex)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Claimer_GetUnsetClaimsPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnsetClaimsPaged'
type Claimer_GetUnsetClaimsPaged_Call struct {
	*mock.Call
}

// GetUnsetClaimsPaged is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint32
//   - pageSize uint32
//   - globalIndex *big.Int
func (_e *Claimer_Expecter) GetUnsetClaimsPaged(ctx interface{}, page interface{}, pageSize interface{}, globalIndex interface{}) *Claimer_GetUnsetClaimsPaged_Call {
	return &Claimer_GetUnsetClaimsPaged_Call{Call: _e.mock.On("GetUnsetClaimsPaged", ctx, page, pageSize, globalIndex)}
}

func (_c *Claimer_GetUnsetClaimsPaged_Call) Run(run func(ctx context.Context, page uint32, pageSize uint32, globalIndex *big.Int)) *Claimer_GetUnsetClaimsPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(uint32), args[3].(*big.Int))
	})
	return _c
}

func (_c *Claimer_GetUnsetClaimsPaged_Call) Return(_a0 []*types.UnsetClaim, _a1 int, _a2 error) *Claimer_GetUnsetClaimsPaged_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Claimer_GetUnsetClaimsPaged_Call) RunAndReturn(run func(context.Context, uint32, uint32, *big.Int) ([]*types.UnsetClaim, int, error)) *Claimer_GetUnsetClaimsPaged_Call {
	_c.Call.Return(run)
	return _c
}

// NewClaimer creates a new instance of Claimer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Claimer {
	mock := &Claimer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
