// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	l2gersync "github.com/agglayer/aggkit/l2gersync"

	mock "github.com/stretchr/testify/mock"
)

// L2GERSyncer is an autogenerated mock type for the L2GERSyncer type
type L2GERSyncer struct {
	mock.Mock
}

type L2GERSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *L2GERSyncer) EXPECT() *L2GERSyncer_Expecter {
	return &L2GERSyncer_Expecter{mock: &_m.Mock}
}

// GetFirstGERAfterL1InfoTreeIndex provides a mock function with given fields: ctx, atOrAfterL1InfoTreeIndex
func (_m *L2GERSyncer) GetFirstGERAfterL1InfoTreeIndex(ctx context.Context, atOrAfterL1InfoTreeIndex uint32) (l2gersync.GlobalExitRootInfo, error) {
	ret := _m.Called(ctx, atOrAfterL1InfoTreeIndex)

	if len(ret) == 0 {
		panic("no return value specified for GetFirstGERAfterL1InfoTreeIndex")
	}

	var r0 l2gersync.GlobalExitRootInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (l2gersync.GlobalExitRootInfo, error)); ok {
		return rf(ctx, atOrAfterL1InfoTreeIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) l2gersync.GlobalExitRootInfo); ok {
		r0 = rf(ctx, atOrAfterL1InfoTreeIndex)
	} else {
		r0 = ret.Get(0).(l2gersync.GlobalExitRootInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, atOrAfterL1InfoTreeIndex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// L2GERSyncer_GetFirstGERAfterL1InfoTreeIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFirstGERAfterL1InfoTreeIndex'
type L2GERSyncer_GetFirstGERAfterL1InfoTreeIndex_Call struct {
	*mock.Call
}

// GetFirstGERAfterL1InfoTreeIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - atOrAfterL1InfoTreeIndex uint32
func (_e *L2GERSyncer_Expecter) GetFirstGERAfterL1InfoTreeIndex(ctx interface{}, atOrAfterL1InfoTreeIndex interface{}) *L2GERSyncer_GetFirstGERAfterL1InfoTreeIndex_Call {
	return &L2GERSyncer_GetFirstGERAfterL1InfoTreeIndex_Call{Call: _e.mock.On("GetFirstGERAfterL1InfoTreeIndex", ctx, atOrAfterL1InfoTreeIndex)}
}

func (_c *L2GERSyncer_GetFirstGERAfterL1InfoTreeIndex_Call) Run(run func(ctx context.Context, atOrAfterL1InfoTreeIndex uint32)) *L2GERSyncer_GetFirstGERAfterL1InfoTreeIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *L2GERSyncer_GetFirstGERAfterL1InfoTreeIndex_Call) Return(_a0 l2gersync.GlobalExitRootInfo, _a1 error) *L2GERSyncer_GetFirstGERAfterL1InfoTreeIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *L2GERSyncer_GetFirstGERAfterL1InfoTreeIndex_Call) RunAndReturn(run func(context.Context, uint32) (l2gersync.GlobalExitRootInfo, error)) *L2GERSyncer_GetFirstGERAfterL1InfoTreeIndex_Call {
	_c.Call.Return(run)
	return _c
}

// GetRemoveGEREvents provides a mock function with given fields: ctx, globalExitRoot, limit
func (_m *L2GERSyncer) GetRemoveGEREvents(ctx context.Context, globalExitRoot *common.Hash, limit uint32) ([]*l2gersync.RemoveGEREvent, error) {
	ret := _m.Called(ctx, globalExitRoot, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRemoveGEREvents")
	}

	var r0 []*l2gersync.RemoveGEREvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *common.Hash, uint32) ([]*l2gersync.RemoveGEREvent, error)); ok {
		return rf(ctx, globalExitRoot, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *common.Hash, uint32) []*l2gersync.RemoveGEREvent); ok {
		r0 = rf(ctx, globalExitRoot, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*l2gersync.RemoveGEREvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *common.Hash, uint32) error); ok {
		r1 = rf(ctx, globalExitRoot, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// L2GERSyncer_GetRemoveGEREvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRemoveGEREvents'
type L2GERSyncer_GetRemoveGEREvents_Call struct {
	*mock.Call
}

// GetRemoveGEREvents is a helper method to define mock.On call
//   - ctx context.Context
//   - globalExitRoot *common.Hash
//   - limit uint32
func (_e *L2GERSyncer_Expecter) GetRemoveGEREvents(ctx interface{}, globalExitRoot interface{}, limit interface{}) *L2GERSyncer_GetRemoveGEREvents_Call {
	return &L2GERSyncer_GetRemoveGEREvents_Call{Call: _e.mock.On("GetRemoveGEREvents", ctx, globalExitRoot, limit)}
}

func (_c *L2GERSyncer_GetRemoveGEREvents_Call) Run(run func(ctx context.Context, globalExitRoot *common.Hash, limit uint32)) *L2GERSyncer_GetRemoveGEREvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*common.Hash), args[2].(uint32))
	})
	return _c
}

func (_c *L2GERSyncer_GetRemoveGEREvents_Call) Return(_a0 []*l2gersync.RemoveGEREvent, _a1 error) *L2GERSyncer_GetRemoveGEREvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *L2GERSyncer_GetRemoveGEREvents_Call) RunAndReturn(run func(context.Context, *common.Hash, uint32) ([]*l2gersync.RemoveGEREvent, error)) *L2GERSyncer_GetRemoveGEREvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewL2GERSyncer creates a new instance of L2GERSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewL2GERSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *L2GERSyncer {
	mock := &L2GERSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
