package backward_forward_let

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/0xPolygon/cdk-rpc/rpc"
	agglayertypes "github.com/agglayer/aggkit/agglayer/types"
	"github.com/ethereum/go-ethereum/common"
	"github.com/urfave/cli/v2"
)

const (
	DefaultExportCertExitsMaxCerts uint64 = 2000
	DefaultExportCertExitsTimeout         = 30 * time.Minute
)

var fetchAdminCertificate = fetchAgglayerAdminCertificate

type certIDsFileJSON struct {
	NetworkID    uint32            `json:"network_id"`
	Certificates map[string]string `json:"certificates"`
}

type exportCertExitsManifest struct {
	NetworkID        uint32                 `json:"network_id"`
	Source           string                 `json:"source"`
	AgglayerAdminURL string                 `json:"agglayer_admin_url"`
	OverrideFile     string                 `json:"override_file"`
	Certificates     []exportCertExitsEntry `json:"certificates"`
}

type exportCertExitsEntry struct {
	Height          uint64 `json:"height"`
	CertificateID   string `json:"certificate_id"`
	BridgeExitCount int    `json:"bridge_exit_count"`
}

// RunExportCertExits exports an override JSON from a read-only AggLayer admin source.
func RunExportCertExits(c *cli.Context) error {
	cfg, err := LoadConfig(c)
	if err != nil {
		return err
	}

	certIDs, err := loadCertIDsFile(c.String("cert-ids-file"), cfg.BackwardForwardLET.L2NetworkID)
	if err != nil {
		return err
	}
	if len(certIDs) == 0 {
		return fmt.Errorf("cert IDs file contains no certificates")
	}
	if uint64(len(certIDs)) > c.Uint64("max-certs") {
		return fmt.Errorf("refusing to export %d certificates; increase --max-certs if this batch is intended", len(certIDs))
	}

	timeout := c.Duration("timeout")
	if timeout <= 0 {
		timeout = DefaultExportCertExitsTimeout
	}
	ctx, cancel := context.WithTimeout(c.Context, timeout)
	defer cancel()

	outPath := filepath.Clean(c.String("out"))
	manifestPath := c.String("manifest-out")
	if manifestPath == "" {
		manifestPath = outPath + ".manifest.json"
	}
	manifestPath = filepath.Clean(manifestPath)

	heights := sortedCertHeights(certIDs)
	override := overrideFileJSON{
		NetworkID:   cfg.BackwardForwardLET.L2NetworkID,
		Description: "generated by backward-forward-let export-cert-exits from agglayer admin_getCertificate",
		Heights:     make(map[string][]*agglayertypes.BridgeExit, len(heights)),
	}
	manifest := exportCertExitsManifest{
		NetworkID:        cfg.BackwardForwardLET.L2NetworkID,
		Source:           "agglayer admin_getCertificate",
		AgglayerAdminURL: sanitizeAdminURL(c.String("agglayer-admin-url")),
		OverrideFile:     outPath,
		Certificates:     make([]exportCertExitsEntry, 0, len(heights)),
	}

	for _, height := range heights {
		certID := certIDs[height]
		cert, err := fetchAdminCertificate(ctx, c.String("agglayer-admin-url"), certID)
		if err != nil {
			return fmt.Errorf("fetch admin_getCertificate height=%d certID=%s: %w", height, certID.Hex(), err)
		}
		if err := validateAdminCertificate(cert, cfg.BackwardForwardLET.L2NetworkID, height, certID); err != nil {
			return fmt.Errorf("validate admin certificate height=%d certID=%s: %w", height, certID.Hex(), err)
		}
		exits := cert.BridgeExits
		if exits == nil {
			exits = []*agglayertypes.BridgeExit{}
		}
		override.Heights[strconv.FormatUint(height, 10)] = exits
		manifest.Certificates = append(manifest.Certificates, exportCertExitsEntry{
			Height:          height,
			CertificateID:   certID.Hex(),
			BridgeExitCount: len(exits),
		})
	}

	if err := writeJSONFile(outPath, override); err != nil {
		return err
	}
	if err := writeJSONFile(manifestPath, manifest); err != nil {
		return err
	}

	fmt.Println("Exported certificate exits override.")
	fmt.Printf("Network ID: %d\n", cfg.BackwardForwardLET.L2NetworkID)
	fmt.Printf("Certificates exported: %d\n", len(heights))
	fmt.Printf("Override file: %s\n", outPath)
	fmt.Printf("Source manifest: %s\n", manifestPath)
	fmt.Println("Next:")
	fmt.Printf("  backward-forward-let --cfg <config> --cert-exits-file %s --diagnose-only\n", outPath)
	fmt.Printf("  backward-forward-let --cfg <config> --cert-exits-file %s\n", outPath)
	return nil
}

func loadCertIDsFile(filePath string, expectedNetworkID uint32) (map[uint64]common.Hash, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("read cert IDs file %s: %w", filePath, err)
	}
	var raw certIDsFileJSON
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("parse cert IDs file %s: %w", filePath, err)
	}
	if raw.NetworkID != 0 && raw.NetworkID != expectedNetworkID {
		return nil, fmt.Errorf("cert IDs file %s: network_id %d does not match config L2NetworkID %d",
			filePath, raw.NetworkID, expectedNetworkID)
	}
	if raw.Certificates == nil {
		return nil, fmt.Errorf("cert IDs file %s: certificates map is missing", filePath)
	}

	parsed := make(map[uint64]common.Hash, len(raw.Certificates))
	for key, value := range raw.Certificates {
		height, err := strconv.ParseUint(key, 10, 64)
		if err != nil {
			return nil, fmt.Errorf("cert IDs file %s: non-numeric height key %q: %w", filePath, key, err)
		}
		certID, err := parseCertificateID(value)
		if err != nil {
			return nil, fmt.Errorf("cert IDs file %s: height %d has invalid cert ID: %w", filePath, height, err)
		}
		parsed[height] = certID
	}
	return parsed, nil
}

func parseCertificateID(value string) (common.Hash, error) {
	value = strings.TrimSpace(value)
	if !strings.HasPrefix(value, "0x") || len(value) != 66 {
		return common.Hash{}, fmt.Errorf("must be a 32-byte 0x-prefixed hex string")
	}
	if _, err := hex.DecodeString(value[2:]); err != nil {
		return common.Hash{}, err
	}
	return common.HexToHash(value), nil
}

func sortedCertHeights(certIDs map[uint64]common.Hash) []uint64 {
	heights := make([]uint64, 0, len(certIDs))
	for height := range certIDs {
		heights = append(heights, height)
	}
	sort.Slice(heights, func(i, j int) bool { return heights[i] < heights[j] })
	return heights
}

func fetchAgglayerAdminCertificate(ctx context.Context, adminURL string, certID common.Hash) (*agglayertypes.Certificate, error) {
	response, err := rpc.JSONRPCCallWithContext(ctx, adminURL, "admin_getCertificate", certID)
	if err != nil {
		return nil, err
	}
	if response.Error != nil {
		return nil, fmt.Errorf("admin_getCertificate returned error: %v", response.Error)
	}
	var pair [2]json.RawMessage
	if err := json.Unmarshal(response.Result, &pair); err != nil {
		return nil, fmt.Errorf("unmarshal admin_getCertificate result as [Certificate, CertificateHeader|null]: %w", err)
	}
	if len(pair[0]) == 0 || string(pair[0]) == "null" {
		return nil, fmt.Errorf("admin_getCertificate returned nil certificate")
	}
	var cert agglayertypes.Certificate
	if err := json.Unmarshal(pair[0], &cert); err != nil {
		return nil, fmt.Errorf("unmarshal Certificate from admin_getCertificate result: %w", err)
	}
	return &cert, nil
}

func validateAdminCertificate(cert *agglayertypes.Certificate, networkID uint32, height uint64, certID common.Hash) error {
	if cert == nil {
		return fmt.Errorf("certificate is nil")
	}
	if cert.NetworkID != networkID {
		return fmt.Errorf("network_id %d does not match expected %d", cert.NetworkID, networkID)
	}
	if cert.Height != height {
		return fmt.Errorf("height %d does not match expected %d", cert.Height, height)
	}
	if calculated := cert.CertificateID(); calculated != certID {
		return fmt.Errorf("calculated certificate ID %s does not match expected %s", calculated.Hex(), certID.Hex())
	}
	return nil
}

func writeJSONFile(filePath string, value interface{}) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal %s: %w", filePath, err)
	}
	if err := os.WriteFile(filePath, append(data, '\n'), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", filePath, err)
	}
	return nil
}

func sanitizeAdminURL(rawURL string) string {
	parsed, err := url.Parse(rawURL)
	if err != nil {
		return rawURL
	}
	parsed.User = nil
	parsed.RawQuery = ""
	parsed.Fragment = ""
	return parsed.String()
}
