// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	agglayertypes "github.com/agglayer/aggkit/agglayer/types"

	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/aggsender/types"
)

// FlowInterface is an autogenerated mock type for the FlowInterface type
type FlowInterface struct {
	mock.Mock
}

type FlowInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *FlowInterface) EXPECT() *FlowInterface_Expecter {
	return &FlowInterface_Expecter{mock: &_m.Mock}
}

// BuildCertificate provides a mock function with given fields: ctx, buildParams
func (_m *FlowInterface) BuildCertificate(ctx context.Context, buildParams *types.CertificateBuildParams) (*agglayertypes.Certificate, error) {
	ret := _m.Called(ctx, buildParams)

	if len(ret) == 0 {
		panic("no return value specified for BuildCertificate")
	}

	var r0 *agglayertypes.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.CertificateBuildParams) (*agglayertypes.Certificate, error)); ok {
		return rf(ctx, buildParams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.CertificateBuildParams) *agglayertypes.Certificate); ok {
		r0 = rf(ctx, buildParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agglayertypes.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.CertificateBuildParams) error); ok {
		r1 = rf(ctx, buildParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FlowInterface_BuildCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildCertificate'
type FlowInterface_BuildCertificate_Call struct {
	*mock.Call
}

// BuildCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - buildParams *types.CertificateBuildParams
func (_e *FlowInterface_Expecter) BuildCertificate(ctx interface{}, buildParams interface{}) *FlowInterface_BuildCertificate_Call {
	return &FlowInterface_BuildCertificate_Call{Call: _e.mock.On("BuildCertificate", ctx, buildParams)}
}

func (_c *FlowInterface_BuildCertificate_Call) Run(run func(ctx context.Context, buildParams *types.CertificateBuildParams)) *FlowInterface_BuildCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.CertificateBuildParams))
	})
	return _c
}

func (_c *FlowInterface_BuildCertificate_Call) Return(_a0 *agglayertypes.Certificate, _a1 error) *FlowInterface_BuildCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FlowInterface_BuildCertificate_Call) RunAndReturn(run func(context.Context, *types.CertificateBuildParams) (*agglayertypes.Certificate, error)) *FlowInterface_BuildCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateBuildParams provides a mock function with given fields: ctx, preParams
func (_m *FlowInterface) GenerateBuildParams(ctx context.Context, preParams *types.CertificatePreBuildParams) (*types.CertificateBuildParams, error) {
	ret := _m.Called(ctx, preParams)

	if len(ret) == 0 {
		panic("no return value specified for GenerateBuildParams")
	}

	var r0 *types.CertificateBuildParams
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.CertificatePreBuildParams) (*types.CertificateBuildParams, error)); ok {
		return rf(ctx, preParams)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.CertificatePreBuildParams) *types.CertificateBuildParams); ok {
		r0 = rf(ctx, preParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.CertificateBuildParams)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.CertificatePreBuildParams) error); ok {
		r1 = rf(ctx, preParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FlowInterface_GenerateBuildParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateBuildParams'
type FlowInterface_GenerateBuildParams_Call struct {
	*mock.Call
}

// GenerateBuildParams is a helper method to define mock.On call
//   - ctx context.Context
//   - preParams *types.CertificatePreBuildParams
func (_e *FlowInterface_Expecter) GenerateBuildParams(ctx interface{}, preParams interface{}) *FlowInterface_GenerateBuildParams_Call {
	return &FlowInterface_GenerateBuildParams_Call{Call: _e.mock.On("GenerateBuildParams", ctx, preParams)}
}

func (_c *FlowInterface_GenerateBuildParams_Call) Run(run func(ctx context.Context, preParams *types.CertificatePreBuildParams)) *FlowInterface_GenerateBuildParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.CertificatePreBuildParams))
	})
	return _c
}

func (_c *FlowInterface_GenerateBuildParams_Call) Return(_a0 *types.CertificateBuildParams, _a1 error) *FlowInterface_GenerateBuildParams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FlowInterface_GenerateBuildParams_Call) RunAndReturn(run func(context.Context, *types.CertificatePreBuildParams) (*types.CertificateBuildParams, error)) *FlowInterface_GenerateBuildParams_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCertificate provides a mock function with given fields: ctx, cert
func (_m *FlowInterface) ValidateCertificate(ctx context.Context, cert *agglayertypes.Certificate) error {
	ret := _m.Called(ctx, cert)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *agglayertypes.Certificate) error); ok {
		r0 = rf(ctx, cert)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FlowInterface_ValidateCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCertificate'
type FlowInterface_ValidateCertificate_Call struct {
	*mock.Call
}

// ValidateCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - cert *agglayertypes.Certificate
func (_e *FlowInterface_Expecter) ValidateCertificate(ctx interface{}, cert interface{}) *FlowInterface_ValidateCertificate_Call {
	return &FlowInterface_ValidateCertificate_Call{Call: _e.mock.On("ValidateCertificate", ctx, cert)}
}

func (_c *FlowInterface_ValidateCertificate_Call) Run(run func(ctx context.Context, cert *agglayertypes.Certificate)) *FlowInterface_ValidateCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*agglayertypes.Certificate))
	})
	return _c
}

func (_c *FlowInterface_ValidateCertificate_Call) Return(_a0 error) *FlowInterface_ValidateCertificate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FlowInterface_ValidateCertificate_Call) RunAndReturn(run func(context.Context, *agglayertypes.Certificate) error) *FlowInterface_ValidateCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// NewFlowInterface creates a new instance of FlowInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFlowInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlowInterface {
	mock := &FlowInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
