// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	aggkittypes "github.com/agglayer/aggkit/types"
	common "github.com/ethereum/go-ethereum/common"

	context "context"

	mock "github.com/stretchr/testify/mock"

	multidownloadertypes "github.com/agglayer/aggkit/multidownloader/types"
)

// MultidownloaderInterface is an autogenerated mock type for the MultidownloaderInterface type
type MultidownloaderInterface struct {
	mock.Mock
}

type MultidownloaderInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MultidownloaderInterface) EXPECT() *MultidownloaderInterface_Expecter {
	return &MultidownloaderInterface_Expecter{mock: &_m.Mock}
}

// CheckValidBlock provides a mock function with given fields: ctx, blockNumber, blockHash
func (_m *MultidownloaderInterface) CheckValidBlock(ctx context.Context, blockNumber uint64, blockHash common.Hash) (bool, uint64, error) {
	ret := _m.Called(ctx, blockNumber, blockHash)

	if len(ret) == 0 {
		panic("no return value specified for CheckValidBlock")
	}

	var r0 bool
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Hash) (bool, uint64, error)); ok {
		return rf(ctx, blockNumber, blockHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, common.Hash) bool); ok {
		r0 = rf(ctx, blockNumber, blockHash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, common.Hash) uint64); ok {
		r1 = rf(ctx, blockNumber, blockHash)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64, common.Hash) error); ok {
		r2 = rf(ctx, blockNumber, blockHash)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MultidownloaderInterface_CheckValidBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckValidBlock'
type MultidownloaderInterface_CheckValidBlock_Call struct {
	*mock.Call
}

// CheckValidBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNumber uint64
//   - blockHash common.Hash
func (_e *MultidownloaderInterface_Expecter) CheckValidBlock(ctx interface{}, blockNumber interface{}, blockHash interface{}) *MultidownloaderInterface_CheckValidBlock_Call {
	return &MultidownloaderInterface_CheckValidBlock_Call{Call: _e.mock.On("CheckValidBlock", ctx, blockNumber, blockHash)}
}

func (_c *MultidownloaderInterface_CheckValidBlock_Call) Run(run func(ctx context.Context, blockNumber uint64, blockHash common.Hash)) *MultidownloaderInterface_CheckValidBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(common.Hash))
	})
	return _c
}

func (_c *MultidownloaderInterface_CheckValidBlock_Call) Return(_a0 bool, _a1 uint64, _a2 error) *MultidownloaderInterface_CheckValidBlock_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MultidownloaderInterface_CheckValidBlock_Call) RunAndReturn(run func(context.Context, uint64, common.Hash) (bool, uint64, error)) *MultidownloaderInterface_CheckValidBlock_Call {
	_c.Call.Return(run)
	return _c
}

// Finality provides a mock function with no fields
func (_m *MultidownloaderInterface) Finality() aggkittypes.BlockNumberFinality {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Finality")
	}

	var r0 aggkittypes.BlockNumberFinality
	if rf, ok := ret.Get(0).(func() aggkittypes.BlockNumberFinality); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(aggkittypes.BlockNumberFinality)
	}

	return r0
}

// MultidownloaderInterface_Finality_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finality'
type MultidownloaderInterface_Finality_Call struct {
	*mock.Call
}

// Finality is a helper method to define mock.On call
func (_e *MultidownloaderInterface_Expecter) Finality() *MultidownloaderInterface_Finality_Call {
	return &MultidownloaderInterface_Finality_Call{Call: _e.mock.On("Finality")}
}

func (_c *MultidownloaderInterface_Finality_Call) Run(run func()) *MultidownloaderInterface_Finality_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MultidownloaderInterface_Finality_Call) Return(_a0 aggkittypes.BlockNumberFinality) *MultidownloaderInterface_Finality_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MultidownloaderInterface_Finality_Call) RunAndReturn(run func() aggkittypes.BlockNumberFinality) *MultidownloaderInterface_Finality_Call {
	_c.Call.Return(run)
	return _c
}

// GetReorgedDataByChainID provides a mock function with given fields: ctx, reorgedChainID
func (_m *MultidownloaderInterface) GetReorgedDataByChainID(ctx context.Context, reorgedChainID uint64) (*multidownloadertypes.ReorgData, error) {
	ret := _m.Called(ctx, reorgedChainID)

	if len(ret) == 0 {
		panic("no return value specified for GetReorgedDataByChainID")
	}

	var r0 *multidownloadertypes.ReorgData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*multidownloadertypes.ReorgData, error)); ok {
		return rf(ctx, reorgedChainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *multidownloadertypes.ReorgData); ok {
		r0 = rf(ctx, reorgedChainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*multidownloadertypes.ReorgData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, reorgedChainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MultidownloaderInterface_GetReorgedDataByChainID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReorgedDataByChainID'
type MultidownloaderInterface_GetReorgedDataByChainID_Call struct {
	*mock.Call
}

// GetReorgedDataByChainID is a helper method to define mock.On call
//   - ctx context.Context
//   - reorgedChainID uint64
func (_e *MultidownloaderInterface_Expecter) GetReorgedDataByChainID(ctx interface{}, reorgedChainID interface{}) *MultidownloaderInterface_GetReorgedDataByChainID_Call {
	return &MultidownloaderInterface_GetReorgedDataByChainID_Call{Call: _e.mock.On("GetReorgedDataByChainID", ctx, reorgedChainID)}
}

func (_c *MultidownloaderInterface_GetReorgedDataByChainID_Call) Run(run func(ctx context.Context, reorgedChainID uint64)) *MultidownloaderInterface_GetReorgedDataByChainID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MultidownloaderInterface_GetReorgedDataByChainID_Call) Return(_a0 *multidownloadertypes.ReorgData, _a1 error) *MultidownloaderInterface_GetReorgedDataByChainID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MultidownloaderInterface_GetReorgedDataByChainID_Call) RunAndReturn(run func(context.Context, uint64) (*multidownloadertypes.ReorgData, error)) *MultidownloaderInterface_GetReorgedDataByChainID_Call {
	_c.Call.Return(run)
	return _c
}

// HeaderByNumber provides a mock function with given fields: ctx, number
func (_m *MultidownloaderInterface) HeaderByNumber(ctx context.Context, number *aggkittypes.BlockNumberFinality) (*aggkittypes.BlockHeader, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for HeaderByNumber")
	}

	var r0 *aggkittypes.BlockHeader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *aggkittypes.BlockNumberFinality) (*aggkittypes.BlockHeader, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *aggkittypes.BlockNumberFinality) *aggkittypes.BlockHeader); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aggkittypes.BlockHeader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *aggkittypes.BlockNumberFinality) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MultidownloaderInterface_HeaderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeaderByNumber'
type MultidownloaderInterface_HeaderByNumber_Call struct {
	*mock.Call
}

// HeaderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number *aggkittypes.BlockNumberFinality
func (_e *MultidownloaderInterface_Expecter) HeaderByNumber(ctx interface{}, number interface{}) *MultidownloaderInterface_HeaderByNumber_Call {
	return &MultidownloaderInterface_HeaderByNumber_Call{Call: _e.mock.On("HeaderByNumber", ctx, number)}
}

func (_c *MultidownloaderInterface_HeaderByNumber_Call) Run(run func(ctx context.Context, number *aggkittypes.BlockNumberFinality)) *MultidownloaderInterface_HeaderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*aggkittypes.BlockNumberFinality))
	})
	return _c
}

func (_c *MultidownloaderInterface_HeaderByNumber_Call) Return(_a0 *aggkittypes.BlockHeader, _a1 error) *MultidownloaderInterface_HeaderByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MultidownloaderInterface_HeaderByNumber_Call) RunAndReturn(run func(context.Context, *aggkittypes.BlockNumberFinality) (*aggkittypes.BlockHeader, error)) *MultidownloaderInterface_HeaderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// IsAvailable provides a mock function with given fields: query
func (_m *MultidownloaderInterface) IsAvailable(query multidownloadertypes.LogQuery) bool {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for IsAvailable")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(multidownloadertypes.LogQuery) bool); ok {
		r0 = rf(query)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MultidownloaderInterface_IsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailable'
type MultidownloaderInterface_IsAvailable_Call struct {
	*mock.Call
}

// IsAvailable is a helper method to define mock.On call
//   - query multidownloadertypes.LogQuery
func (_e *MultidownloaderInterface_Expecter) IsAvailable(query interface{}) *MultidownloaderInterface_IsAvailable_Call {
	return &MultidownloaderInterface_IsAvailable_Call{Call: _e.mock.On("IsAvailable", query)}
}

func (_c *MultidownloaderInterface_IsAvailable_Call) Run(run func(query multidownloadertypes.LogQuery)) *MultidownloaderInterface_IsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(multidownloadertypes.LogQuery))
	})
	return _c
}

func (_c *MultidownloaderInterface_IsAvailable_Call) Return(_a0 bool) *MultidownloaderInterface_IsAvailable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MultidownloaderInterface_IsAvailable_Call) RunAndReturn(run func(multidownloadertypes.LogQuery) bool) *MultidownloaderInterface_IsAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// IsPartiallyAvailable provides a mock function with given fields: query
func (_m *MultidownloaderInterface) IsPartiallyAvailable(query multidownloadertypes.LogQuery) (bool, *multidownloadertypes.LogQuery) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for IsPartiallyAvailable")
	}

	var r0 bool
	var r1 *multidownloadertypes.LogQuery
	if rf, ok := ret.Get(0).(func(multidownloadertypes.LogQuery) (bool, *multidownloadertypes.LogQuery)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(multidownloadertypes.LogQuery) bool); ok {
		r0 = rf(query)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(multidownloadertypes.LogQuery) *multidownloadertypes.LogQuery); ok {
		r1 = rf(query)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*multidownloadertypes.LogQuery)
		}
	}

	return r0, r1
}

// MultidownloaderInterface_IsPartiallyAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPartiallyAvailable'
type MultidownloaderInterface_IsPartiallyAvailable_Call struct {
	*mock.Call
}

// IsPartiallyAvailable is a helper method to define mock.On call
//   - query multidownloadertypes.LogQuery
func (_e *MultidownloaderInterface_Expecter) IsPartiallyAvailable(query interface{}) *MultidownloaderInterface_IsPartiallyAvailable_Call {
	return &MultidownloaderInterface_IsPartiallyAvailable_Call{Call: _e.mock.On("IsPartiallyAvailable", query)}
}

func (_c *MultidownloaderInterface_IsPartiallyAvailable_Call) Run(run func(query multidownloadertypes.LogQuery)) *MultidownloaderInterface_IsPartiallyAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(multidownloadertypes.LogQuery))
	})
	return _c
}

func (_c *MultidownloaderInterface_IsPartiallyAvailable_Call) Return(_a0 bool, _a1 *multidownloadertypes.LogQuery) *MultidownloaderInterface_IsPartiallyAvailable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MultidownloaderInterface_IsPartiallyAvailable_Call) RunAndReturn(run func(multidownloadertypes.LogQuery) (bool, *multidownloadertypes.LogQuery)) *MultidownloaderInterface_IsPartiallyAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// LogQuery provides a mock function with given fields: ctx, query
func (_m *MultidownloaderInterface) LogQuery(ctx context.Context, query multidownloadertypes.LogQuery) (multidownloadertypes.LogQueryResponse, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for LogQuery")
	}

	var r0 multidownloadertypes.LogQueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, multidownloadertypes.LogQuery) (multidownloadertypes.LogQueryResponse, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, multidownloadertypes.LogQuery) multidownloadertypes.LogQueryResponse); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(multidownloadertypes.LogQueryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, multidownloadertypes.LogQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MultidownloaderInterface_LogQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogQuery'
type MultidownloaderInterface_LogQuery_Call struct {
	*mock.Call
}

// LogQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - query multidownloadertypes.LogQuery
func (_e *MultidownloaderInterface_Expecter) LogQuery(ctx interface{}, query interface{}) *MultidownloaderInterface_LogQuery_Call {
	return &MultidownloaderInterface_LogQuery_Call{Call: _e.mock.On("LogQuery", ctx, query)}
}

func (_c *MultidownloaderInterface_LogQuery_Call) Run(run func(ctx context.Context, query multidownloadertypes.LogQuery)) *MultidownloaderInterface_LogQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(multidownloadertypes.LogQuery))
	})
	return _c
}

func (_c *MultidownloaderInterface_LogQuery_Call) Return(_a0 multidownloadertypes.LogQueryResponse, _a1 error) *MultidownloaderInterface_LogQuery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MultidownloaderInterface_LogQuery_Call) RunAndReturn(run func(context.Context, multidownloadertypes.LogQuery) (multidownloadertypes.LogQueryResponse, error)) *MultidownloaderInterface_LogQuery_Call {
	_c.Call.Return(run)
	return _c
}

// StorageHeaderByNumber provides a mock function with given fields: ctx, number
func (_m *MultidownloaderInterface) StorageHeaderByNumber(ctx context.Context, number *aggkittypes.BlockNumberFinality) (*aggkittypes.BlockHeader, multidownloadertypes.FinalizedType, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for StorageHeaderByNumber")
	}

	var r0 *aggkittypes.BlockHeader
	var r1 multidownloadertypes.FinalizedType
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *aggkittypes.BlockNumberFinality) (*aggkittypes.BlockHeader, multidownloadertypes.FinalizedType, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *aggkittypes.BlockNumberFinality) *aggkittypes.BlockHeader); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aggkittypes.BlockHeader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *aggkittypes.BlockNumberFinality) multidownloadertypes.FinalizedType); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Get(1).(multidownloadertypes.FinalizedType)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *aggkittypes.BlockNumberFinality) error); ok {
		r2 = rf(ctx, number)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MultidownloaderInterface_StorageHeaderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StorageHeaderByNumber'
type MultidownloaderInterface_StorageHeaderByNumber_Call struct {
	*mock.Call
}

// StorageHeaderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number *aggkittypes.BlockNumberFinality
func (_e *MultidownloaderInterface_Expecter) StorageHeaderByNumber(ctx interface{}, number interface{}) *MultidownloaderInterface_StorageHeaderByNumber_Call {
	return &MultidownloaderInterface_StorageHeaderByNumber_Call{Call: _e.mock.On("StorageHeaderByNumber", ctx, number)}
}

func (_c *MultidownloaderInterface_StorageHeaderByNumber_Call) Run(run func(ctx context.Context, number *aggkittypes.BlockNumberFinality)) *MultidownloaderInterface_StorageHeaderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*aggkittypes.BlockNumberFinality))
	})
	return _c
}

func (_c *MultidownloaderInterface_StorageHeaderByNumber_Call) Return(_a0 *aggkittypes.BlockHeader, _a1 multidownloadertypes.FinalizedType, _a2 error) *MultidownloaderInterface_StorageHeaderByNumber_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MultidownloaderInterface_StorageHeaderByNumber_Call) RunAndReturn(run func(context.Context, *aggkittypes.BlockNumberFinality) (*aggkittypes.BlockHeader, multidownloadertypes.FinalizedType, error)) *MultidownloaderInterface_StorageHeaderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewMultidownloaderInterface creates a new instance of MultidownloaderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMultidownloaderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MultidownloaderInterface {
	mock := &MultidownloaderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
