// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	bridgetracker "github.com/agglayer/aggkit/bridgetracker"

	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/bridgetracker/types"
)

// CertificateSource is an autogenerated mock type for the CertificateSource type
type CertificateSource struct {
	mock.Mock
}

type CertificateSource_Expecter struct {
	mock *mock.Mock
}

func (_m *CertificateSource) EXPECT() *CertificateSource_Expecter {
	return &CertificateSource_Expecter{mock: &_m.Mock}
}

// CertificateFor provides a mock function with given fields: ctx, bridge
func (_m *CertificateSource) CertificateFor(ctx context.Context, bridge *bridgetracker.BridgeInfo) (*types.CertificateData, error) {
	ret := _m.Called(ctx, bridge)

	if len(ret) == 0 {
		panic("no return value specified for CertificateFor")
	}

	var r0 *types.CertificateData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *bridgetracker.BridgeInfo) (*types.CertificateData, error)); ok {
		return rf(ctx, bridge)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *bridgetracker.BridgeInfo) *types.CertificateData); ok {
		r0 = rf(ctx, bridge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.CertificateData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *bridgetracker.BridgeInfo) error); ok {
		r1 = rf(ctx, bridge)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertificateSource_CertificateFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CertificateFor'
type CertificateSource_CertificateFor_Call struct {
	*mock.Call
}

// CertificateFor is a helper method to define mock.On call
//   - ctx context.Context
//   - bridge *bridgetracker.BridgeInfo
func (_e *CertificateSource_Expecter) CertificateFor(ctx interface{}, bridge interface{}) *CertificateSource_CertificateFor_Call {
	return &CertificateSource_CertificateFor_Call{Call: _e.mock.On("CertificateFor", ctx, bridge)}
}

func (_c *CertificateSource_CertificateFor_Call) Run(run func(ctx context.Context, bridge *bridgetracker.BridgeInfo)) *CertificateSource_CertificateFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*bridgetracker.BridgeInfo))
	})
	return _c
}

func (_c *CertificateSource_CertificateFor_Call) Return(_a0 *types.CertificateData, _a1 error) *CertificateSource_CertificateFor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CertificateSource_CertificateFor_Call) RunAndReturn(run func(context.Context, *bridgetracker.BridgeInfo) (*types.CertificateData, error)) *CertificateSource_CertificateFor_Call {
	_c.Call.Return(run)
	return _c
}

// NewCertificateSource creates a new instance of CertificateSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertificateSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertificateSource {
	mock := &CertificateSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
