// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	bridgetracker "github.com/agglayer/aggkit/bridgetracker"

	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/bridgetracker/types"
)

// ClaimSource is an autogenerated mock type for the ClaimSource type
type ClaimSource struct {
	mock.Mock
}

type ClaimSource_Expecter struct {
	mock *mock.Mock
}

func (_m *ClaimSource) EXPECT() *ClaimSource_Expecter {
	return &ClaimSource_Expecter{mock: &_m.Mock}
}

// ClaimFor provides a mock function with given fields: ctx, bridge
func (_m *ClaimSource) ClaimFor(ctx context.Context, bridge *bridgetracker.BridgeInfo) (*types.ClaimResult, error) {
	ret := _m.Called(ctx, bridge)

	if len(ret) == 0 {
		panic("no return value specified for ClaimFor")
	}

	var r0 *types.ClaimResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *bridgetracker.BridgeInfo) (*types.ClaimResult, error)); ok {
		return rf(ctx, bridge)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *bridgetracker.BridgeInfo) *types.ClaimResult); ok {
		r0 = rf(ctx, bridge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ClaimResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *bridgetracker.BridgeInfo) error); ok {
		r1 = rf(ctx, bridge)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimSource_ClaimFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimFor'
type ClaimSource_ClaimFor_Call struct {
	*mock.Call
}

// ClaimFor is a helper method to define mock.On call
//   - ctx context.Context
//   - bridge *bridgetracker.BridgeInfo
func (_e *ClaimSource_Expecter) ClaimFor(ctx interface{}, bridge interface{}) *ClaimSource_ClaimFor_Call {
	return &ClaimSource_ClaimFor_Call{Call: _e.mock.On("ClaimFor", ctx, bridge)}
}

func (_c *ClaimSource_ClaimFor_Call) Run(run func(ctx context.Context, bridge *bridgetracker.BridgeInfo)) *ClaimSource_ClaimFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*bridgetracker.BridgeInfo))
	})
	return _c
}

func (_c *ClaimSource_ClaimFor_Call) Return(_a0 *types.ClaimResult, _a1 error) *ClaimSource_ClaimFor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClaimSource_ClaimFor_Call) RunAndReturn(run func(context.Context, *bridgetracker.BridgeInfo) (*types.ClaimResult, error)) *ClaimSource_ClaimFor_Call {
	_c.Call.Return(run)
	return _c
}

// NewClaimSource creates a new instance of ClaimSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimSource {
	mock := &ClaimSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
