// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/bridgetracker/types"
)

// StatusNotifier is an autogenerated mock type for the StatusNotifier type
type StatusNotifier struct {
	mock.Mock
}

type StatusNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *StatusNotifier) EXPECT() *StatusNotifier_Expecter {
	return &StatusNotifier_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: networkID, txHash
func (_m *StatusNotifier) Subscribe(networkID uint32, txHash common.Hash) (<-chan types.BridgeUpdate, func()) {
	ret := _m.Called(networkID, txHash)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan types.BridgeUpdate
	var r1 func()
	if rf, ok := ret.Get(0).(func(uint32, common.Hash) (<-chan types.BridgeUpdate, func())); ok {
		return rf(networkID, txHash)
	}
	if rf, ok := ret.Get(0).(func(uint32, common.Hash) <-chan types.BridgeUpdate); ok {
		r0 = rf(networkID, txHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan types.BridgeUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(uint32, common.Hash) func()); ok {
		r1 = rf(networkID, txHash)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	return r0, r1
}

// StatusNotifier_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type StatusNotifier_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - networkID uint32
//   - txHash common.Hash
func (_e *StatusNotifier_Expecter) Subscribe(networkID interface{}, txHash interface{}) *StatusNotifier_Subscribe_Call {
	return &StatusNotifier_Subscribe_Call{Call: _e.mock.On("Subscribe", networkID, txHash)}
}

func (_c *StatusNotifier_Subscribe_Call) Run(run func(networkID uint32, txHash common.Hash)) *StatusNotifier_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint32), args[1].(common.Hash))
	})
	return _c
}

func (_c *StatusNotifier_Subscribe_Call) Return(_a0 <-chan types.BridgeUpdate, _a1 func()) *StatusNotifier_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatusNotifier_Subscribe_Call) RunAndReturn(run func(uint32, common.Hash) (<-chan types.BridgeUpdate, func())) *StatusNotifier_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewStatusNotifier creates a new instance of StatusNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatusNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatusNotifier {
	mock := &StatusNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
