// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	domain "github.com/agglayer/aggkit/bridgetracker/domain"

	mock "github.com/stretchr/testify/mock"
)

// ActivityBridgeScanner is an autogenerated mock type for the ActivityBridgeScanner type
type ActivityBridgeScanner struct {
	mock.Mock
}

type ActivityBridgeScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityBridgeScanner) EXPECT() *ActivityBridgeScanner_Expecter {
	return &ActivityBridgeScanner_Expecter{mock: &_m.Mock}
}

// BridgesFrom provides a mock function with given fields: ctx, fromAddress, known
func (_m *ActivityBridgeScanner) BridgesFrom(ctx context.Context, fromAddress common.Address, known map[string]domain.KnownBridge) ([]*domain.ScannedBridge, []string, []domain.ActivityWarning, error) {
	ret := _m.Called(ctx, fromAddress, known)

	if len(ret) == 0 {
		panic("no return value specified for BridgesFrom")
	}

	var r0 []*domain.ScannedBridge
	var r1 []string
	var r2 []domain.ActivityWarning
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, map[string]domain.KnownBridge) ([]*domain.ScannedBridge, []string, []domain.ActivityWarning, error)); ok {
		return rf(ctx, fromAddress, known)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, map[string]domain.KnownBridge) []*domain.ScannedBridge); ok {
		r0 = rf(ctx, fromAddress, known)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ScannedBridge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, map[string]domain.KnownBridge) []string); ok {
		r1 = rf(ctx, fromAddress, known)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, common.Address, map[string]domain.KnownBridge) []domain.ActivityWarning); ok {
		r2 = rf(ctx, fromAddress, known)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]domain.ActivityWarning)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, common.Address, map[string]domain.KnownBridge) error); ok {
		r3 = rf(ctx, fromAddress, known)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// ActivityBridgeScanner_BridgesFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BridgesFrom'
type ActivityBridgeScanner_BridgesFrom_Call struct {
	*mock.Call
}

// BridgesFrom is a helper method to define mock.On call
//   - ctx context.Context
//   - fromAddress common.Address
//   - known map[string]domain.KnownBridge
func (_e *ActivityBridgeScanner_Expecter) BridgesFrom(ctx interface{}, fromAddress interface{}, known interface{}) *ActivityBridgeScanner_BridgesFrom_Call {
	return &ActivityBridgeScanner_BridgesFrom_Call{Call: _e.mock.On("BridgesFrom", ctx, fromAddress, known)}
}

func (_c *ActivityBridgeScanner_BridgesFrom_Call) Run(run func(ctx context.Context, fromAddress common.Address, known map[string]domain.KnownBridge)) *ActivityBridgeScanner_BridgesFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(map[string]domain.KnownBridge))
	})
	return _c
}

func (_c *ActivityBridgeScanner_BridgesFrom_Call) Return(found []*domain.ScannedBridge, invalidated []string, warnings []domain.ActivityWarning, err error) *ActivityBridgeScanner_BridgesFrom_Call {
	_c.Call.Return(found, invalidated, warnings, err)
	return _c
}

func (_c *ActivityBridgeScanner_BridgesFrom_Call) RunAndReturn(run func(context.Context, common.Address, map[string]domain.KnownBridge) ([]*domain.ScannedBridge, []string, []domain.ActivityWarning, error)) *ActivityBridgeScanner_BridgesFrom_Call {
	_c.Call.Return(run)
	return _c
}

// NewActivityBridgeScanner creates a new instance of ActivityBridgeScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityBridgeScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityBridgeScanner {
	mock := &ActivityBridgeScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
