// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	bridgetracker "github.com/agglayer/aggkit/bridgetracker"

	mock "github.com/stretchr/testify/mock"
)

// ClaimChecker is an autogenerated mock type for the ClaimChecker type
type ClaimChecker struct {
	mock.Mock
}

type ClaimChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *ClaimChecker) EXPECT() *ClaimChecker_Expecter {
	return &ClaimChecker_Expecter{mock: &_m.Mock}
}

// IsClaimed provides a mock function with given fields: ctx, bridge
func (_m *ClaimChecker) IsClaimed(ctx context.Context, bridge *bridgetracker.BridgeInfo) (bool, error) {
	ret := _m.Called(ctx, bridge)

	if len(ret) == 0 {
		panic("no return value specified for IsClaimed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *bridgetracker.BridgeInfo) (bool, error)); ok {
		return rf(ctx, bridge)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *bridgetracker.BridgeInfo) bool); ok {
		r0 = rf(ctx, bridge)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *bridgetracker.BridgeInfo) error); ok {
		r1 = rf(ctx, bridge)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimChecker_IsClaimed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsClaimed'
type ClaimChecker_IsClaimed_Call struct {
	*mock.Call
}

// IsClaimed is a helper method to define mock.On call
//   - ctx context.Context
//   - bridge *bridgetracker.BridgeInfo
func (_e *ClaimChecker_Expecter) IsClaimed(ctx interface{}, bridge interface{}) *ClaimChecker_IsClaimed_Call {
	return &ClaimChecker_IsClaimed_Call{Call: _e.mock.On("IsClaimed", ctx, bridge)}
}

func (_c *ClaimChecker_IsClaimed_Call) Run(run func(ctx context.Context, bridge *bridgetracker.BridgeInfo)) *ClaimChecker_IsClaimed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*bridgetracker.BridgeInfo))
	})
	return _c
}

func (_c *ClaimChecker_IsClaimed_Call) Return(_a0 bool, _a1 error) *ClaimChecker_IsClaimed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClaimChecker_IsClaimed_Call) RunAndReturn(run func(context.Context, *bridgetracker.BridgeInfo) (bool, error)) *ClaimChecker_IsClaimed_Call {
	_c.Call.Return(run)
	return _c
}

// NewClaimChecker creates a new instance of ClaimChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimChecker {
	mock := &ClaimChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
