// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	compatibility "github.com/agglayer/aggkit/db/compatibility"

	mock "github.com/stretchr/testify/mock"
)

// CompatibilityDataGetter is an autogenerated mock type for the CompatibilityDataGetter type
type CompatibilityDataGetter[T compatibility.CompatibilityComparer[T]] struct {
	mock.Mock
}

type CompatibilityDataGetter_Expecter[T compatibility.CompatibilityComparer[T]] struct {
	mock *mock.Mock
}

func (_m *CompatibilityDataGetter[T]) EXPECT() *CompatibilityDataGetter_Expecter[T] {
	return &CompatibilityDataGetter_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *CompatibilityDataGetter[T]) Execute(ctx context.Context) (T, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (T, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) T); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompatibilityDataGetter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CompatibilityDataGetter_Execute_Call[T compatibility.CompatibilityComparer[T]] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CompatibilityDataGetter_Expecter[T]) Execute(ctx interface{}) *CompatibilityDataGetter_Execute_Call[T] {
	return &CompatibilityDataGetter_Execute_Call[T]{Call: _e.mock.On("Execute", ctx)}
}

func (_c *CompatibilityDataGetter_Execute_Call[T]) Run(run func(ctx context.Context)) *CompatibilityDataGetter_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CompatibilityDataGetter_Execute_Call[T]) Return(_a0 T, _a1 error) *CompatibilityDataGetter_Execute_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompatibilityDataGetter_Execute_Call[T]) RunAndReturn(run func(context.Context) (T, error)) *CompatibilityDataGetter_Execute_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewCompatibilityDataGetter creates a new instance of CompatibilityDataGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompatibilityDataGetter[T compatibility.CompatibilityComparer[T]](t interface {
	mock.TestingT
	Cleanup(func())
}) *CompatibilityDataGetter[T] {
	mock := &CompatibilityDataGetter[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
