// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	aggkittypes "github.com/agglayer/aggkit/types"
	common "github.com/ethereum/go-ethereum/common"

	context "context"

	coretypes "github.com/ethereum/go-ethereum/core/types"

	mock "github.com/stretchr/testify/mock"

	multidownloadertypes "github.com/agglayer/aggkit/multidownloader/types"

	types "github.com/agglayer/aggkit/db/types"
)

// Storager is an autogenerated mock type for the Storager type
type Storager struct {
	mock.Mock
}

type Storager_Expecter struct {
	mock *mock.Mock
}

func (_m *Storager) EXPECT() *Storager_Expecter {
	return &Storager_Expecter{mock: &_m.Mock}
}

// GetBlockHeaderByNumber provides a mock function with given fields: tx, blockNumber
func (_m *Storager) GetBlockHeaderByNumber(tx types.Querier, blockNumber uint64) (*aggkittypes.BlockHeader, bool, error) {
	ret := _m.Called(tx, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockHeaderByNumber")
	}

	var r0 *aggkittypes.BlockHeader
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(types.Querier, uint64) (*aggkittypes.BlockHeader, bool, error)); ok {
		return rf(tx, blockNumber)
	}
	if rf, ok := ret.Get(0).(func(types.Querier, uint64) *aggkittypes.BlockHeader); ok {
		r0 = rf(tx, blockNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aggkittypes.BlockHeader)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Querier, uint64) bool); ok {
		r1 = rf(tx, blockNumber)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(types.Querier, uint64) error); ok {
		r2 = rf(tx, blockNumber)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Storager_GetBlockHeaderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockHeaderByNumber'
type Storager_GetBlockHeaderByNumber_Call struct {
	*mock.Call
}

// GetBlockHeaderByNumber is a helper method to define mock.On call
//   - tx types.Querier
//   - blockNumber uint64
func (_e *Storager_Expecter) GetBlockHeaderByNumber(tx interface{}, blockNumber interface{}) *Storager_GetBlockHeaderByNumber_Call {
	return &Storager_GetBlockHeaderByNumber_Call{Call: _e.mock.On("GetBlockHeaderByNumber", tx, blockNumber)}
}

func (_c *Storager_GetBlockHeaderByNumber_Call) Run(run func(tx types.Querier, blockNumber uint64)) *Storager_GetBlockHeaderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].(uint64))
	})
	return _c
}

func (_c *Storager_GetBlockHeaderByNumber_Call) Return(_a0 *aggkittypes.BlockHeader, _a1 bool, _a2 error) *Storager_GetBlockHeaderByNumber_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Storager_GetBlockHeaderByNumber_Call) RunAndReturn(run func(types.Querier, uint64) (*aggkittypes.BlockHeader, bool, error)) *Storager_GetBlockHeaderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockHeadersNotFinalized provides a mock function with given fields: tx, maxBlock
func (_m *Storager) GetBlockHeadersNotFinalized(tx types.Querier, maxBlock *uint64) (aggkittypes.ListBlockHeaders, error) {
	ret := _m.Called(tx, maxBlock)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockHeadersNotFinalized")
	}

	var r0 aggkittypes.ListBlockHeaders
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Querier, *uint64) (aggkittypes.ListBlockHeaders, error)); ok {
		return rf(tx, maxBlock)
	}
	if rf, ok := ret.Get(0).(func(types.Querier, *uint64) aggkittypes.ListBlockHeaders); ok {
		r0 = rf(tx, maxBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aggkittypes.ListBlockHeaders)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Querier, *uint64) error); ok {
		r1 = rf(tx, maxBlock)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storager_GetBlockHeadersNotFinalized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockHeadersNotFinalized'
type Storager_GetBlockHeadersNotFinalized_Call struct {
	*mock.Call
}

// GetBlockHeadersNotFinalized is a helper method to define mock.On call
//   - tx types.Querier
//   - maxBlock *uint64
func (_e *Storager_Expecter) GetBlockHeadersNotFinalized(tx interface{}, maxBlock interface{}) *Storager_GetBlockHeadersNotFinalized_Call {
	return &Storager_GetBlockHeadersNotFinalized_Call{Call: _e.mock.On("GetBlockHeadersNotFinalized", tx, maxBlock)}
}

func (_c *Storager_GetBlockHeadersNotFinalized_Call) Run(run func(tx types.Querier, maxBlock *uint64)) *Storager_GetBlockHeadersNotFinalized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].(*uint64))
	})
	return _c
}

func (_c *Storager_GetBlockHeadersNotFinalized_Call) Return(_a0 aggkittypes.ListBlockHeaders, _a1 error) *Storager_GetBlockHeadersNotFinalized_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storager_GetBlockHeadersNotFinalized_Call) RunAndReturn(run func(types.Querier, *uint64) (aggkittypes.ListBlockHeaders, error)) *Storager_GetBlockHeadersNotFinalized_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockReorgedChainID provides a mock function with given fields: tx, blockNumber, blockHash
func (_m *Storager) GetBlockReorgedChainID(tx types.Querier, blockNumber uint64, blockHash common.Hash) (uint64, bool, error) {
	ret := _m.Called(tx, blockNumber, blockHash)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockReorgedChainID")
	}

	var r0 uint64
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(types.Querier, uint64, common.Hash) (uint64, bool, error)); ok {
		return rf(tx, blockNumber, blockHash)
	}
	if rf, ok := ret.Get(0).(func(types.Querier, uint64, common.Hash) uint64); ok {
		r0 = rf(tx, blockNumber, blockHash)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(types.Querier, uint64, common.Hash) bool); ok {
		r1 = rf(tx, blockNumber, blockHash)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(types.Querier, uint64, common.Hash) error); ok {
		r2 = rf(tx, blockNumber, blockHash)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Storager_GetBlockReorgedChainID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockReorgedChainID'
type Storager_GetBlockReorgedChainID_Call struct {
	*mock.Call
}

// GetBlockReorgedChainID is a helper method to define mock.On call
//   - tx types.Querier
//   - blockNumber uint64
//   - blockHash common.Hash
func (_e *Storager_Expecter) GetBlockReorgedChainID(tx interface{}, blockNumber interface{}, blockHash interface{}) *Storager_GetBlockReorgedChainID_Call {
	return &Storager_GetBlockReorgedChainID_Call{Call: _e.mock.On("GetBlockReorgedChainID", tx, blockNumber, blockHash)}
}

func (_c *Storager_GetBlockReorgedChainID_Call) Run(run func(tx types.Querier, blockNumber uint64, blockHash common.Hash)) *Storager_GetBlockReorgedChainID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].(uint64), args[2].(common.Hash))
	})
	return _c
}

func (_c *Storager_GetBlockReorgedChainID_Call) Return(_a0 uint64, _a1 bool, _a2 error) *Storager_GetBlockReorgedChainID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Storager_GetBlockReorgedChainID_Call) RunAndReturn(run func(types.Querier, uint64, common.Hash) (uint64, bool, error)) *Storager_GetBlockReorgedChainID_Call {
	_c.Call.Return(run)
	return _c
}

// GetEthLogs provides a mock function with given fields: tx, query
func (_m *Storager) GetEthLogs(tx types.Querier, query multidownloadertypes.LogQuery) ([]coretypes.Log, error) {
	ret := _m.Called(tx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetEthLogs")
	}

	var r0 []coretypes.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Querier, multidownloadertypes.LogQuery) ([]coretypes.Log, error)); ok {
		return rf(tx, query)
	}
	if rf, ok := ret.Get(0).(func(types.Querier, multidownloadertypes.LogQuery) []coretypes.Log); ok {
		r0 = rf(tx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]coretypes.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Querier, multidownloadertypes.LogQuery) error); ok {
		r1 = rf(tx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storager_GetEthLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEthLogs'
type Storager_GetEthLogs_Call struct {
	*mock.Call
}

// GetEthLogs is a helper method to define mock.On call
//   - tx types.Querier
//   - query multidownloadertypes.LogQuery
func (_e *Storager_Expecter) GetEthLogs(tx interface{}, query interface{}) *Storager_GetEthLogs_Call {
	return &Storager_GetEthLogs_Call{Call: _e.mock.On("GetEthLogs", tx, query)}
}

func (_c *Storager_GetEthLogs_Call) Run(run func(tx types.Querier, query multidownloadertypes.LogQuery)) *Storager_GetEthLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].(multidownloadertypes.LogQuery))
	})
	return _c
}

func (_c *Storager_GetEthLogs_Call) Return(_a0 []coretypes.Log, _a1 error) *Storager_GetEthLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storager_GetEthLogs_Call) RunAndReturn(run func(types.Querier, multidownloadertypes.LogQuery) ([]coretypes.Log, error)) *Storager_GetEthLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetHighestBlockNumber provides a mock function with given fields: tx
func (_m *Storager) GetHighestBlockNumber(tx types.Querier) (uint64, error) {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for GetHighestBlockNumber")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Querier) (uint64, error)); ok {
		return rf(tx)
	}
	if rf, ok := ret.Get(0).(func(types.Querier) uint64); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(types.Querier) error); ok {
		r1 = rf(tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storager_GetHighestBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHighestBlockNumber'
type Storager_GetHighestBlockNumber_Call struct {
	*mock.Call
}

// GetHighestBlockNumber is a helper method to define mock.On call
//   - tx types.Querier
func (_e *Storager_Expecter) GetHighestBlockNumber(tx interface{}) *Storager_GetHighestBlockNumber_Call {
	return &Storager_GetHighestBlockNumber_Call{Call: _e.mock.On("GetHighestBlockNumber", tx)}
}

func (_c *Storager_GetHighestBlockNumber_Call) Run(run func(tx types.Querier)) *Storager_GetHighestBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier))
	})
	return _c
}

func (_c *Storager_GetHighestBlockNumber_Call) Return(_a0 uint64, _a1 error) *Storager_GetHighestBlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storager_GetHighestBlockNumber_Call) RunAndReturn(run func(types.Querier) (uint64, error)) *Storager_GetHighestBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetRangeBlockHeader provides a mock function with given fields: tx, isFinal
func (_m *Storager) GetRangeBlockHeader(tx types.Querier, isFinal multidownloadertypes.FinalizedType) (*aggkittypes.BlockHeader, *aggkittypes.BlockHeader, error) {
	ret := _m.Called(tx, isFinal)

	if len(ret) == 0 {
		panic("no return value specified for GetRangeBlockHeader")
	}

	var r0 *aggkittypes.BlockHeader
	var r1 *aggkittypes.BlockHeader
	var r2 error
	if rf, ok := ret.Get(0).(func(types.Querier, multidownloadertypes.FinalizedType) (*aggkittypes.BlockHeader, *aggkittypes.BlockHeader, error)); ok {
		return rf(tx, isFinal)
	}
	if rf, ok := ret.Get(0).(func(types.Querier, multidownloadertypes.FinalizedType) *aggkittypes.BlockHeader); ok {
		r0 = rf(tx, isFinal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aggkittypes.BlockHeader)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Querier, multidownloadertypes.FinalizedType) *aggkittypes.BlockHeader); ok {
		r1 = rf(tx, isFinal)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*aggkittypes.BlockHeader)
		}
	}

	if rf, ok := ret.Get(2).(func(types.Querier, multidownloadertypes.FinalizedType) error); ok {
		r2 = rf(tx, isFinal)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Storager_GetRangeBlockHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRangeBlockHeader'
type Storager_GetRangeBlockHeader_Call struct {
	*mock.Call
}

// GetRangeBlockHeader is a helper method to define mock.On call
//   - tx types.Querier
//   - isFinal multidownloadertypes.FinalizedType
func (_e *Storager_Expecter) GetRangeBlockHeader(tx interface{}, isFinal interface{}) *Storager_GetRangeBlockHeader_Call {
	return &Storager_GetRangeBlockHeader_Call{Call: _e.mock.On("GetRangeBlockHeader", tx, isFinal)}
}

func (_c *Storager_GetRangeBlockHeader_Call) Run(run func(tx types.Querier, isFinal multidownloadertypes.FinalizedType)) *Storager_GetRangeBlockHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].(multidownloadertypes.FinalizedType))
	})
	return _c
}

func (_c *Storager_GetRangeBlockHeader_Call) Return(lowest *aggkittypes.BlockHeader, highest *aggkittypes.BlockHeader, err error) *Storager_GetRangeBlockHeader_Call {
	_c.Call.Return(lowest, highest, err)
	return _c
}

func (_c *Storager_GetRangeBlockHeader_Call) RunAndReturn(run func(types.Querier, multidownloadertypes.FinalizedType) (*aggkittypes.BlockHeader, *aggkittypes.BlockHeader, error)) *Storager_GetRangeBlockHeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetSyncedBlockRangePerContract provides a mock function with given fields: tx
func (_m *Storager) GetSyncedBlockRangePerContract(tx types.Querier) (multidownloadertypes.SetSyncSegment, error) {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncedBlockRangePerContract")
	}

	var r0 multidownloadertypes.SetSyncSegment
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Querier) (multidownloadertypes.SetSyncSegment, error)); ok {
		return rf(tx)
	}
	if rf, ok := ret.Get(0).(func(types.Querier) multidownloadertypes.SetSyncSegment); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Get(0).(multidownloadertypes.SetSyncSegment)
	}

	if rf, ok := ret.Get(1).(func(types.Querier) error); ok {
		r1 = rf(tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storager_GetSyncedBlockRangePerContract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSyncedBlockRangePerContract'
type Storager_GetSyncedBlockRangePerContract_Call struct {
	*mock.Call
}

// GetSyncedBlockRangePerContract is a helper method to define mock.On call
//   - tx types.Querier
func (_e *Storager_Expecter) GetSyncedBlockRangePerContract(tx interface{}) *Storager_GetSyncedBlockRangePerContract_Call {
	return &Storager_GetSyncedBlockRangePerContract_Call{Call: _e.mock.On("GetSyncedBlockRangePerContract", tx)}
}

func (_c *Storager_GetSyncedBlockRangePerContract_Call) Run(run func(tx types.Querier)) *Storager_GetSyncedBlockRangePerContract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier))
	})
	return _c
}

func (_c *Storager_GetSyncedBlockRangePerContract_Call) Return(_a0 multidownloadertypes.SetSyncSegment, _a1 error) *Storager_GetSyncedBlockRangePerContract_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storager_GetSyncedBlockRangePerContract_Call) RunAndReturn(run func(types.Querier) (multidownloadertypes.SetSyncSegment, error)) *Storager_GetSyncedBlockRangePerContract_Call {
	_c.Call.Return(run)
	return _c
}

// GetValue provides a mock function with given fields: tx, owner, key
func (_m *Storager) GetValue(tx types.Querier, owner string, key string) (string, error) {
	ret := _m.Called(tx, owner, key)

	if len(ret) == 0 {
		panic("no return value specified for GetValue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Querier, string, string) (string, error)); ok {
		return rf(tx, owner, key)
	}
	if rf, ok := ret.Get(0).(func(types.Querier, string, string) string); ok {
		r0 = rf(tx, owner, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(types.Querier, string, string) error); ok {
		r1 = rf(tx, owner, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storager_GetValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValue'
type Storager_GetValue_Call struct {
	*mock.Call
}

// GetValue is a helper method to define mock.On call
//   - tx types.Querier
//   - owner string
//   - key string
func (_e *Storager_Expecter) GetValue(tx interface{}, owner interface{}, key interface{}) *Storager_GetValue_Call {
	return &Storager_GetValue_Call{Call: _e.mock.On("GetValue", tx, owner, key)}
}

func (_c *Storager_GetValue_Call) Run(run func(tx types.Querier, owner string, key string)) *Storager_GetValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Storager_GetValue_Call) Return(_a0 string, _a1 error) *Storager_GetValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storager_GetValue_Call) RunAndReturn(run func(types.Querier, string, string) (string, error)) *Storager_GetValue_Call {
	_c.Call.Return(run)
	return _c
}

// InsertReorgAndMoveReorgedBlocksAndLogs provides a mock function with given fields: tx, reorgData
func (_m *Storager) InsertReorgAndMoveReorgedBlocksAndLogs(tx types.Querier, reorgData multidownloadertypes.ReorgData) (uint64, error) {
	ret := _m.Called(tx, reorgData)

	if len(ret) == 0 {
		panic("no return value specified for InsertReorgAndMoveReorgedBlocksAndLogs")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Querier, multidownloadertypes.ReorgData) (uint64, error)); ok {
		return rf(tx, reorgData)
	}
	if rf, ok := ret.Get(0).(func(types.Querier, multidownloadertypes.ReorgData) uint64); ok {
		r0 = rf(tx, reorgData)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(types.Querier, multidownloadertypes.ReorgData) error); ok {
		r1 = rf(tx, reorgData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storager_InsertReorgAndMoveReorgedBlocksAndLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertReorgAndMoveReorgedBlocksAndLogs'
type Storager_InsertReorgAndMoveReorgedBlocksAndLogs_Call struct {
	*mock.Call
}

// InsertReorgAndMoveReorgedBlocksAndLogs is a helper method to define mock.On call
//   - tx types.Querier
//   - reorgData multidownloadertypes.ReorgData
func (_e *Storager_Expecter) InsertReorgAndMoveReorgedBlocksAndLogs(tx interface{}, reorgData interface{}) *Storager_InsertReorgAndMoveReorgedBlocksAndLogs_Call {
	return &Storager_InsertReorgAndMoveReorgedBlocksAndLogs_Call{Call: _e.mock.On("InsertReorgAndMoveReorgedBlocksAndLogs", tx, reorgData)}
}

func (_c *Storager_InsertReorgAndMoveReorgedBlocksAndLogs_Call) Run(run func(tx types.Querier, reorgData multidownloadertypes.ReorgData)) *Storager_InsertReorgAndMoveReorgedBlocksAndLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].(multidownloadertypes.ReorgData))
	})
	return _c
}

func (_c *Storager_InsertReorgAndMoveReorgedBlocksAndLogs_Call) Return(_a0 uint64, _a1 error) *Storager_InsertReorgAndMoveReorgedBlocksAndLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storager_InsertReorgAndMoveReorgedBlocksAndLogs_Call) RunAndReturn(run func(types.Querier, multidownloadertypes.ReorgData) (uint64, error)) *Storager_InsertReorgAndMoveReorgedBlocksAndLogs_Call {
	_c.Call.Return(run)
	return _c
}

// InsertValue provides a mock function with given fields: tx, owner, key, value
func (_m *Storager) InsertValue(tx types.Querier, owner string, key string, value string) error {
	ret := _m.Called(tx, owner, key, value)

	if len(ret) == 0 {
		panic("no return value specified for InsertValue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Querier, string, string, string) error); ok {
		r0 = rf(tx, owner, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storager_InsertValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertValue'
type Storager_InsertValue_Call struct {
	*mock.Call
}

// InsertValue is a helper method to define mock.On call
//   - tx types.Querier
//   - owner string
//   - key string
//   - value string
func (_e *Storager_Expecter) InsertValue(tx interface{}, owner interface{}, key interface{}, value interface{}) *Storager_InsertValue_Call {
	return &Storager_InsertValue_Call{Call: _e.mock.On("InsertValue", tx, owner, key, value)}
}

func (_c *Storager_InsertValue_Call) Run(run func(tx types.Querier, owner string, key string, value string)) *Storager_InsertValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Storager_InsertValue_Call) Return(_a0 error) *Storager_InsertValue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storager_InsertValue_Call) RunAndReturn(run func(types.Querier, string, string, string) error) *Storager_InsertValue_Call {
	_c.Call.Return(run)
	return _c
}

// NewTx provides a mock function with given fields: ctx
func (_m *Storager) NewTx(ctx context.Context) (types.Txer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewTx")
	}

	var r0 types.Txer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (types.Txer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) types.Txer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Txer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Storager_NewTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTx'
type Storager_NewTx_Call struct {
	*mock.Call
}

// NewTx is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Storager_Expecter) NewTx(ctx interface{}) *Storager_NewTx_Call {
	return &Storager_NewTx_Call{Call: _e.mock.On("NewTx", ctx)}
}

func (_c *Storager_NewTx_Call) Run(run func(ctx context.Context)) *Storager_NewTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Storager_NewTx_Call) Return(_a0 types.Txer, _a1 error) *Storager_NewTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Storager_NewTx_Call) RunAndReturn(run func(context.Context) (types.Txer, error)) *Storager_NewTx_Call {
	_c.Call.Return(run)
	return _c
}

// SaveEthLogsWithHeaders provides a mock function with given fields: tx, blockHeaders, logs, isFinal
func (_m *Storager) SaveEthLogsWithHeaders(tx types.Querier, blockHeaders aggkittypes.ListBlockHeaders, logs []coretypes.Log, isFinal bool) error {
	ret := _m.Called(tx, blockHeaders, logs, isFinal)

	if len(ret) == 0 {
		panic("no return value specified for SaveEthLogsWithHeaders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Querier, aggkittypes.ListBlockHeaders, []coretypes.Log, bool) error); ok {
		r0 = rf(tx, blockHeaders, logs, isFinal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storager_SaveEthLogsWithHeaders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveEthLogsWithHeaders'
type Storager_SaveEthLogsWithHeaders_Call struct {
	*mock.Call
}

// SaveEthLogsWithHeaders is a helper method to define mock.On call
//   - tx types.Querier
//   - blockHeaders aggkittypes.ListBlockHeaders
//   - logs []coretypes.Log
//   - isFinal bool
func (_e *Storager_Expecter) SaveEthLogsWithHeaders(tx interface{}, blockHeaders interface{}, logs interface{}, isFinal interface{}) *Storager_SaveEthLogsWithHeaders_Call {
	return &Storager_SaveEthLogsWithHeaders_Call{Call: _e.mock.On("SaveEthLogsWithHeaders", tx, blockHeaders, logs, isFinal)}
}

func (_c *Storager_SaveEthLogsWithHeaders_Call) Run(run func(tx types.Querier, blockHeaders aggkittypes.ListBlockHeaders, logs []coretypes.Log, isFinal bool)) *Storager_SaveEthLogsWithHeaders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].(aggkittypes.ListBlockHeaders), args[2].([]coretypes.Log), args[3].(bool))
	})
	return _c
}

func (_c *Storager_SaveEthLogsWithHeaders_Call) Return(_a0 error) *Storager_SaveEthLogsWithHeaders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storager_SaveEthLogsWithHeaders_Call) RunAndReturn(run func(types.Querier, aggkittypes.ListBlockHeaders, []coretypes.Log, bool) error) *Storager_SaveEthLogsWithHeaders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBlockToFinalized provides a mock function with given fields: tx, blockNumbers
func (_m *Storager) UpdateBlockToFinalized(tx types.Querier, blockNumbers []uint64) error {
	ret := _m.Called(tx, blockNumbers)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBlockToFinalized")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Querier, []uint64) error); ok {
		r0 = rf(tx, blockNumbers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storager_UpdateBlockToFinalized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBlockToFinalized'
type Storager_UpdateBlockToFinalized_Call struct {
	*mock.Call
}

// UpdateBlockToFinalized is a helper method to define mock.On call
//   - tx types.Querier
//   - blockNumbers []uint64
func (_e *Storager_Expecter) UpdateBlockToFinalized(tx interface{}, blockNumbers interface{}) *Storager_UpdateBlockToFinalized_Call {
	return &Storager_UpdateBlockToFinalized_Call{Call: _e.mock.On("UpdateBlockToFinalized", tx, blockNumbers)}
}

func (_c *Storager_UpdateBlockToFinalized_Call) Run(run func(tx types.Querier, blockNumbers []uint64)) *Storager_UpdateBlockToFinalized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].([]uint64))
	})
	return _c
}

func (_c *Storager_UpdateBlockToFinalized_Call) Return(_a0 error) *Storager_UpdateBlockToFinalized_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storager_UpdateBlockToFinalized_Call) RunAndReturn(run func(types.Querier, []uint64) error) *Storager_UpdateBlockToFinalized_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSyncedStatus provides a mock function with given fields: tx, segments
func (_m *Storager) UpdateSyncedStatus(tx types.Querier, segments []multidownloadertypes.SyncSegment) error {
	ret := _m.Called(tx, segments)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSyncedStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Querier, []multidownloadertypes.SyncSegment) error); ok {
		r0 = rf(tx, segments)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storager_UpdateSyncedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSyncedStatus'
type Storager_UpdateSyncedStatus_Call struct {
	*mock.Call
}

// UpdateSyncedStatus is a helper method to define mock.On call
//   - tx types.Querier
//   - segments []multidownloadertypes.SyncSegment
func (_e *Storager_Expecter) UpdateSyncedStatus(tx interface{}, segments interface{}) *Storager_UpdateSyncedStatus_Call {
	return &Storager_UpdateSyncedStatus_Call{Call: _e.mock.On("UpdateSyncedStatus", tx, segments)}
}

func (_c *Storager_UpdateSyncedStatus_Call) Run(run func(tx types.Querier, segments []multidownloadertypes.SyncSegment)) *Storager_UpdateSyncedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].([]multidownloadertypes.SyncSegment))
	})
	return _c
}

func (_c *Storager_UpdateSyncedStatus_Call) Return(_a0 error) *Storager_UpdateSyncedStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storager_UpdateSyncedStatus_Call) RunAndReturn(run func(types.Querier, []multidownloadertypes.SyncSegment) error) *Storager_UpdateSyncedStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateValue provides a mock function with given fields: tx, owner, key, value
func (_m *Storager) UpdateValue(tx types.Querier, owner string, key string, value string) error {
	ret := _m.Called(tx, owner, key, value)

	if len(ret) == 0 {
		panic("no return value specified for UpdateValue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Querier, string, string, string) error); ok {
		r0 = rf(tx, owner, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storager_UpdateValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateValue'
type Storager_UpdateValue_Call struct {
	*mock.Call
}

// UpdateValue is a helper method to define mock.On call
//   - tx types.Querier
//   - owner string
//   - key string
//   - value string
func (_e *Storager_Expecter) UpdateValue(tx interface{}, owner interface{}, key interface{}, value interface{}) *Storager_UpdateValue_Call {
	return &Storager_UpdateValue_Call{Call: _e.mock.On("UpdateValue", tx, owner, key, value)}
}

func (_c *Storager_UpdateValue_Call) Run(run func(tx types.Querier, owner string, key string, value string)) *Storager_UpdateValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *Storager_UpdateValue_Call) Return(_a0 error) *Storager_UpdateValue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storager_UpdateValue_Call) RunAndReturn(run func(types.Querier, string, string, string) error) *Storager_UpdateValue_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertSyncerConfigs provides a mock function with given fields: tx, configs
func (_m *Storager) UpsertSyncerConfigs(tx types.Querier, configs []multidownloadertypes.ContractConfig) error {
	ret := _m.Called(tx, configs)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSyncerConfigs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Querier, []multidownloadertypes.ContractConfig) error); ok {
		r0 = rf(tx, configs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Storager_UpsertSyncerConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertSyncerConfigs'
type Storager_UpsertSyncerConfigs_Call struct {
	*mock.Call
}

// UpsertSyncerConfigs is a helper method to define mock.On call
//   - tx types.Querier
//   - configs []multidownloadertypes.ContractConfig
func (_e *Storager_Expecter) UpsertSyncerConfigs(tx interface{}, configs interface{}) *Storager_UpsertSyncerConfigs_Call {
	return &Storager_UpsertSyncerConfigs_Call{Call: _e.mock.On("UpsertSyncerConfigs", tx, configs)}
}

func (_c *Storager_UpsertSyncerConfigs_Call) Run(run func(tx types.Querier, configs []multidownloadertypes.ContractConfig)) *Storager_UpsertSyncerConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Querier), args[1].([]multidownloadertypes.ContractConfig))
	})
	return _c
}

func (_c *Storager_UpsertSyncerConfigs_Call) Return(_a0 error) *Storager_UpsertSyncerConfigs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storager_UpsertSyncerConfigs_Call) RunAndReturn(run func(types.Querier, []multidownloadertypes.ContractConfig) error) *Storager_UpsertSyncerConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorager creates a new instance of Storager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storager {
	mock := &Storager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
