// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/agglayer/aggkit/multidownloader/types"
	mock "github.com/stretchr/testify/mock"
)

// ReorgProcessor is an autogenerated mock type for the ReorgProcessor type
type ReorgProcessor struct {
	mock.Mock
}

type ReorgProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *ReorgProcessor) EXPECT() *ReorgProcessor_Expecter {
	return &ReorgProcessor_Expecter{mock: &_m.Mock}
}

// ProcessReorg provides a mock function with given fields: ctx, detectedReorgError
func (_m *ReorgProcessor) ProcessReorg(ctx context.Context, detectedReorgError types.DetectedReorgError) error {
	ret := _m.Called(ctx, detectedReorgError)

	if len(ret) == 0 {
		panic("no return value specified for ProcessReorg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.DetectedReorgError) error); ok {
		r0 = rf(ctx, detectedReorgError)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReorgProcessor_ProcessReorg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessReorg'
type ReorgProcessor_ProcessReorg_Call struct {
	*mock.Call
}

// ProcessReorg is a helper method to define mock.On call
//   - ctx context.Context
//   - detectedReorgError types.DetectedReorgError
func (_e *ReorgProcessor_Expecter) ProcessReorg(ctx interface{}, detectedReorgError interface{}) *ReorgProcessor_ProcessReorg_Call {
	return &ReorgProcessor_ProcessReorg_Call{Call: _e.mock.On("ProcessReorg", ctx, detectedReorgError)}
}

func (_c *ReorgProcessor_ProcessReorg_Call) Run(run func(ctx context.Context, detectedReorgError types.DetectedReorgError)) *ReorgProcessor_ProcessReorg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.DetectedReorgError))
	})
	return _c
}

func (_c *ReorgProcessor_ProcessReorg_Call) Return(_a0 error) *ReorgProcessor_ProcessReorg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReorgProcessor_ProcessReorg_Call) RunAndReturn(run func(context.Context, types.DetectedReorgError) error) *ReorgProcessor_ProcessReorg_Call {
	_c.Call.Return(run)
	return _c
}

// NewReorgProcessor creates a new instance of ReorgProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReorgProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReorgProcessor {
	mock := &ReorgProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
