// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	big "math/big"

	common "github.com/ethereum/go-ethereum/common"

	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// Token is an autogenerated mock type for the Token type
type Token struct {
	mock.Mock
}

type Token_Expecter struct {
	mock *mock.Mock
}

func (_m *Token) EXPECT() *Token_Expecter {
	return &Token_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *Token) Address() common.Address {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 common.Address
	if rf, ok := ret.Get(0).(func() common.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	return r0
}

// Token_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type Token_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *Token_Expecter) Address() *Token_Address_Call {
	return &Token_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *Token_Address_Call) Run(run func()) *Token_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Token_Address_Call) Return(_a0 common.Address) *Token_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Token_Address_Call) RunAndReturn(run func() common.Address) *Token_Address_Call {
	_c.Call.Return(run)
	return _c
}

// Allowance provides a mock function with given fields: ctx, owner, spender
func (_m *Token) Allowance(ctx context.Context, owner common.Address, spender common.Address) (*big.Int, error) {
	ret := _m.Called(ctx, owner, spender)

	if len(ret) == 0 {
		panic("no return value specified for Allowance")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Address) (*big.Int, error)); ok {
		return rf(ctx, owner, spender)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, common.Address) *big.Int); ok {
		r0 = rf(ctx, owner, spender)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, common.Address) error); ok {
		r1 = rf(ctx, owner, spender)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_Allowance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allowance'
type Token_Allowance_Call struct {
	*mock.Call
}

// Allowance is a helper method to define mock.On call
//   - ctx context.Context
//   - owner common.Address
//   - spender common.Address
func (_e *Token_Expecter) Allowance(ctx interface{}, owner interface{}, spender interface{}) *Token_Allowance_Call {
	return &Token_Allowance_Call{Call: _e.mock.On("Allowance", ctx, owner, spender)}
}

func (_c *Token_Allowance_Call) Run(run func(ctx context.Context, owner common.Address, spender common.Address)) *Token_Allowance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(common.Address))
	})
	return _c
}

func (_c *Token_Allowance_Call) Return(_a0 *big.Int, _a1 error) *Token_Allowance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_Allowance_Call) RunAndReturn(run func(context.Context, common.Address, common.Address) (*big.Int, error)) *Token_Allowance_Call {
	_c.Call.Return(run)
	return _c
}

// Approve provides a mock function with given fields: ctx, spender, amount
func (_m *Token) Approve(ctx context.Context, spender common.Address, amount *big.Int) (*types.Receipt, error) {
	ret := _m.Called(ctx, spender, amount)

	if len(ret) == 0 {
		panic("no return value specified for Approve")
	}

	var r0 *types.Receipt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) (*types.Receipt, error)); ok {
		return rf(ctx, spender, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) *types.Receipt); ok {
		r0 = rf(ctx, spender, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Receipt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int) error); ok {
		r1 = rf(ctx, spender, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_Approve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Approve'
type Token_Approve_Call struct {
	*mock.Call
}

// Approve is a helper method to define mock.On call
//   - ctx context.Context
//   - spender common.Address
//   - amount *big.Int
func (_e *Token_Expecter) Approve(ctx interface{}, spender interface{}, amount interface{}) *Token_Approve_Call {
	return &Token_Approve_Call{Call: _e.mock.On("Approve", ctx, spender, amount)}
}

func (_c *Token_Approve_Call) Run(run func(ctx context.Context, spender common.Address, amount *big.Int)) *Token_Approve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*big.Int))
	})
	return _c
}

func (_c *Token_Approve_Call) Return(_a0 *types.Receipt, _a1 error) *Token_Approve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_Approve_Call) RunAndReturn(run func(context.Context, common.Address, *big.Int) (*types.Receipt, error)) *Token_Approve_Call {
	_c.Call.Return(run)
	return _c
}

// BalanceOf provides a mock function with given fields: ctx, account
func (_m *Token) BalanceOf(ctx context.Context, account common.Address) (*big.Int, error) {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for BalanceOf")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address) (*big.Int, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address) *big.Int); ok {
		r0 = rf(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_BalanceOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceOf'
type Token_BalanceOf_Call struct {
	*mock.Call
}

// BalanceOf is a helper method to define mock.On call
//   - ctx context.Context
//   - account common.Address
func (_e *Token_Expecter) BalanceOf(ctx interface{}, account interface{}) *Token_BalanceOf_Call {
	return &Token_BalanceOf_Call{Call: _e.mock.On("BalanceOf", ctx, account)}
}

func (_c *Token_BalanceOf_Call) Run(run func(ctx context.Context, account common.Address)) *Token_BalanceOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address))
	})
	return _c
}

func (_c *Token_BalanceOf_Call) Return(_a0 *big.Int, _a1 error) *Token_BalanceOf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_BalanceOf_Call) RunAndReturn(run func(context.Context, common.Address) (*big.Int, error)) *Token_BalanceOf_Call {
	_c.Call.Return(run)
	return _c
}

// Mint provides a mock function with given fields: ctx, to, amount
func (_m *Token) Mint(ctx context.Context, to common.Address, amount *big.Int) (*types.Receipt, error) {
	ret := _m.Called(ctx, to, amount)

	if len(ret) == 0 {
		panic("no return value specified for Mint")
	}

	var r0 *types.Receipt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) (*types.Receipt, error)); ok {
		return rf(ctx, to, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *big.Int) *types.Receipt); ok {
		r0 = rf(ctx, to, amount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Receipt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *big.Int) error); ok {
		r1 = rf(ctx, to, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Token_Mint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mint'
type Token_Mint_Call struct {
	*mock.Call
}

// Mint is a helper method to define mock.On call
//   - ctx context.Context
//   - to common.Address
//   - amount *big.Int
func (_e *Token_Expecter) Mint(ctx interface{}, to interface{}, amount interface{}) *Token_Mint_Call {
	return &Token_Mint_Call{Call: _e.mock.On("Mint", ctx, to, amount)}
}

func (_c *Token_Mint_Call) Run(run func(ctx context.Context, to common.Address, amount *big.Int)) *Token_Mint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*big.Int))
	})
	return _c
}

func (_c *Token_Mint_Call) Return(_a0 *types.Receipt, _a1 error) *Token_Mint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Token_Mint_Call) RunAndReturn(run func(context.Context, common.Address, *big.Int) (*types.Receipt, error)) *Token_Mint_Call {
	_c.Call.Return(run)
	return _c
}

// NewToken creates a new instance of Token. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *Token {
	mock := &Token{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
