#!/bin/bash

source $(dirname $0)/local_config_helper
export KURTOSIS_ENCLAVE=aggkit

###############################################################################
function export_values_of_aggkit_config() {
    local AGGKIT_CONFIG_FILE=$1
    common_export_values_of_aggkit_config "$AGGKIT_CONFIG_FILE"
    export_key_from_toml_file_or_fatal zkevm_bridge_l2_address $AGGKIT_CONFIG_FILE BridgeL2Sync BridgeAddr
    export_key_from_toml_file_or_fatal zkevm_rollup_address $AGGKIT_CONFIG_FILE L1Config rollupAddress
    export_key_from_toml_file_or_fatal zkevm_global_exit_root_l2_address $AGGKIT_CONFIG_FILE L2Config GlobalExitRootAddr
}
###############################################################################
function export_ports_from_kurtosis() {
    common_export_ports_from_kurtosis
    export_portnum_from_kurtosis_or_fail zkevm_rpc_http_port cdk-erigon-rpc-001 http-rpc rpc
    export l2_rpc_url="http://localhost:${zkevm_rpc_http_port}"
    export agglayer_grpc_url="http://localhost:${agglayer_grpc_port}"
}
###############################################################################
# MAIN
###############################################################################
ORIG_TEMPLATE_FILE=test/config/fep-config.toml.template
DEST_TEMPLATE_FILE=$DEST/test.kurtosis.toml
main $*