// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	ethermantypes "github.com/agglayer/aggkit/etherman/types"
	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/types"
)

// BlockNotifierManager is an autogenerated mock type for the BlockNotifierManager type
type BlockNotifierManager struct {
	mock.Mock
}

type BlockNotifierManager_Expecter struct {
	mock *mock.Mock
}

func (_m *BlockNotifierManager) EXPECT() *BlockNotifierManager_Expecter {
	return &BlockNotifierManager_Expecter{mock: &_m.Mock}
}

// GetBlockNotifier provides a mock function with given fields: ctx, finality
func (_m *BlockNotifierManager) GetBlockNotifier(ctx context.Context, finality types.BlockNumberFinality) (ethermantypes.BlockNotifier, error) {
	ret := _m.Called(ctx, finality)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockNotifier")
	}

	var r0 ethermantypes.BlockNotifier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.BlockNumberFinality) (ethermantypes.BlockNotifier, error)); ok {
		return rf(ctx, finality)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.BlockNumberFinality) ethermantypes.BlockNotifier); ok {
		r0 = rf(ctx, finality)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ethermantypes.BlockNotifier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.BlockNumberFinality) error); ok {
		r1 = rf(ctx, finality)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockNotifierManager_GetBlockNotifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockNotifier'
type BlockNotifierManager_GetBlockNotifier_Call struct {
	*mock.Call
}

// GetBlockNotifier is a helper method to define mock.On call
//   - ctx context.Context
//   - finality types.BlockNumberFinality
func (_e *BlockNotifierManager_Expecter) GetBlockNotifier(ctx interface{}, finality interface{}) *BlockNotifierManager_GetBlockNotifier_Call {
	return &BlockNotifierManager_GetBlockNotifier_Call{Call: _e.mock.On("GetBlockNotifier", ctx, finality)}
}

func (_c *BlockNotifierManager_GetBlockNotifier_Call) Run(run func(ctx context.Context, finality types.BlockNumberFinality)) *BlockNotifierManager_GetBlockNotifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.BlockNumberFinality))
	})
	return _c
}

func (_c *BlockNotifierManager_GetBlockNotifier_Call) Return(_a0 ethermantypes.BlockNotifier, _a1 error) *BlockNotifierManager_GetBlockNotifier_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockNotifierManager_GetBlockNotifier_Call) RunAndReturn(run func(context.Context, types.BlockNumberFinality) (ethermantypes.BlockNotifier, error)) *BlockNotifierManager_GetBlockNotifier_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentBlockNumber provides a mock function with given fields: ctx, finality
func (_m *BlockNotifierManager) GetCurrentBlockNumber(ctx context.Context, finality types.BlockNumberFinality) (uint64, error) {
	ret := _m.Called(ctx, finality)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentBlockNumber")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.BlockNumberFinality) (uint64, error)); ok {
		return rf(ctx, finality)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.BlockNumberFinality) uint64); ok {
		r0 = rf(ctx, finality)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.BlockNumberFinality) error); ok {
		r1 = rf(ctx, finality)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BlockNotifierManager_GetCurrentBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentBlockNumber'
type BlockNotifierManager_GetCurrentBlockNumber_Call struct {
	*mock.Call
}

// GetCurrentBlockNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - finality types.BlockNumberFinality
func (_e *BlockNotifierManager_Expecter) GetCurrentBlockNumber(ctx interface{}, finality interface{}) *BlockNotifierManager_GetCurrentBlockNumber_Call {
	return &BlockNotifierManager_GetCurrentBlockNumber_Call{Call: _e.mock.On("GetCurrentBlockNumber", ctx, finality)}
}

func (_c *BlockNotifierManager_GetCurrentBlockNumber_Call) Run(run func(ctx context.Context, finality types.BlockNumberFinality)) *BlockNotifierManager_GetCurrentBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.BlockNumberFinality))
	})
	return _c
}

func (_c *BlockNotifierManager_GetCurrentBlockNumber_Call) Return(_a0 uint64, _a1 error) *BlockNotifierManager_GetCurrentBlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BlockNotifierManager_GetCurrentBlockNumber_Call) RunAndReturn(run func(context.Context, types.BlockNumberFinality) (uint64, error)) *BlockNotifierManager_GetCurrentBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewBlockNotifierManager creates a new instance of BlockNotifierManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlockNotifierManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlockNotifierManager {
	mock := &BlockNotifierManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
