// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/aggsender/types"
)

// AuthProofServiceClient is an autogenerated mock type for the AuthProofServiceClient type
type AuthProofServiceClient struct {
	mock.Mock
}

type AuthProofServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthProofServiceClient) EXPECT() *AuthProofServiceClient_Expecter {
	return &AuthProofServiceClient_Expecter{mock: &_m.Mock}
}

// FetchAuthProof provides a mock function with given fields: ctx, in, opts
func (_m *AuthProofServiceClient) FetchAuthProof(ctx context.Context, in *types.FetchAuthProofRequest, opts ...grpc.CallOption) (*types.FetchAuthProofResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FetchAuthProof")
	}

	var r0 *types.FetchAuthProofResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.FetchAuthProofRequest, ...grpc.CallOption) (*types.FetchAuthProofResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.FetchAuthProofRequest, ...grpc.CallOption) *types.FetchAuthProofResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.FetchAuthProofResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.FetchAuthProofRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthProofServiceClient_FetchAuthProof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAuthProof'
type AuthProofServiceClient_FetchAuthProof_Call struct {
	*mock.Call
}

// FetchAuthProof is a helper method to define mock.On call
//   - ctx context.Context
//   - in *types.FetchAuthProofRequest
//   - opts ...grpc.CallOption
func (_e *AuthProofServiceClient_Expecter) FetchAuthProof(ctx interface{}, in interface{}, opts ...interface{}) *AuthProofServiceClient_FetchAuthProof_Call {
	return &AuthProofServiceClient_FetchAuthProof_Call{Call: _e.mock.On("FetchAuthProof",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *AuthProofServiceClient_FetchAuthProof_Call) Run(run func(ctx context.Context, in *types.FetchAuthProofRequest, opts ...grpc.CallOption)) *AuthProofServiceClient_FetchAuthProof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*types.FetchAuthProofRequest), variadicArgs...)
	})
	return _c
}

func (_c *AuthProofServiceClient_FetchAuthProof_Call) Return(_a0 *types.FetchAuthProofResponse, _a1 error) *AuthProofServiceClient_FetchAuthProof_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthProofServiceClient_FetchAuthProof_Call) RunAndReturn(run func(context.Context, *types.FetchAuthProofRequest, ...grpc.CallOption) (*types.FetchAuthProofResponse, error)) *AuthProofServiceClient_FetchAuthProof_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthProofServiceClient creates a new instance of AuthProofServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthProofServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthProofServiceClient {
	mock := &AuthProofServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
