// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	big "math/big"

	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	mock "github.com/stretchr/testify/mock"
)

// AggchainFEPCaller is an autogenerated mock type for the AggchainFEPCaller type
type AggchainFEPCaller struct {
	mock.Mock
}

type AggchainFEPCaller_Expecter struct {
	mock *mock.Mock
}

func (_m *AggchainFEPCaller) EXPECT() *AggchainFEPCaller_Expecter {
	return &AggchainFEPCaller_Expecter{mock: &_m.Mock}
}

// LatestBlockNumber provides a mock function with given fields: opts
func (_m *AggchainFEPCaller) LatestBlockNumber(opts *bind.CallOpts) (*big.Int, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for LatestBlockNumber")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) (*big.Int, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) *big.Int); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggchainFEPCaller_LatestBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestBlockNumber'
type AggchainFEPCaller_LatestBlockNumber_Call struct {
	*mock.Call
}

// LatestBlockNumber is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *AggchainFEPCaller_Expecter) LatestBlockNumber(opts interface{}) *AggchainFEPCaller_LatestBlockNumber_Call {
	return &AggchainFEPCaller_LatestBlockNumber_Call{Call: _e.mock.On("LatestBlockNumber", opts)}
}

func (_c *AggchainFEPCaller_LatestBlockNumber_Call) Run(run func(opts *bind.CallOpts)) *AggchainFEPCaller_LatestBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *AggchainFEPCaller_LatestBlockNumber_Call) Return(_a0 *big.Int, _a1 error) *AggchainFEPCaller_LatestBlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggchainFEPCaller_LatestBlockNumber_Call) RunAndReturn(run func(*bind.CallOpts) (*big.Int, error)) *AggchainFEPCaller_LatestBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// StartingBlockNumber provides a mock function with given fields: opts
func (_m *AggchainFEPCaller) StartingBlockNumber(opts *bind.CallOpts) (*big.Int, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for StartingBlockNumber")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) (*big.Int, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) *big.Int); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggchainFEPCaller_StartingBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartingBlockNumber'
type AggchainFEPCaller_StartingBlockNumber_Call struct {
	*mock.Call
}

// StartingBlockNumber is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *AggchainFEPCaller_Expecter) StartingBlockNumber(opts interface{}) *AggchainFEPCaller_StartingBlockNumber_Call {
	return &AggchainFEPCaller_StartingBlockNumber_Call{Call: _e.mock.On("StartingBlockNumber", opts)}
}

func (_c *AggchainFEPCaller_StartingBlockNumber_Call) Run(run func(opts *bind.CallOpts)) *AggchainFEPCaller_StartingBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *AggchainFEPCaller_StartingBlockNumber_Call) Return(_a0 *big.Int, _a1 error) *AggchainFEPCaller_StartingBlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggchainFEPCaller_StartingBlockNumber_Call) RunAndReturn(run func(*bind.CallOpts) (*big.Int, error)) *AggchainFEPCaller_StartingBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewAggchainFEPCaller creates a new instance of AggchainFEPCaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAggchainFEPCaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *AggchainFEPCaller {
	mock := &AggchainFEPCaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
