// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	big "math/big"

	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"
)

// AggchainFEPCaller is an autogenerated mock type for the AggchainFEPCaller type
type AggchainFEPCaller struct {
	mock.Mock
}

type AggchainFEPCaller_Expecter struct {
	mock *mock.Mock
}

func (_m *AggchainFEPCaller) EXPECT() *AggchainFEPCaller_Expecter {
	return &AggchainFEPCaller_Expecter{mock: &_m.Mock}
}

// GetAggchainSigners provides a mock function with given fields: opts
func (_m *AggchainFEPCaller) GetAggchainSigners(opts *bind.CallOpts) ([]common.Address, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for GetAggchainSigners")
	}

	var r0 []common.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) ([]common.Address, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) []common.Address); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggchainFEPCaller_GetAggchainSigners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAggchainSigners'
type AggchainFEPCaller_GetAggchainSigners_Call struct {
	*mock.Call
}

// GetAggchainSigners is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *AggchainFEPCaller_Expecter) GetAggchainSigners(opts interface{}) *AggchainFEPCaller_GetAggchainSigners_Call {
	return &AggchainFEPCaller_GetAggchainSigners_Call{Call: _e.mock.On("GetAggchainSigners", opts)}
}

func (_c *AggchainFEPCaller_GetAggchainSigners_Call) Run(run func(opts *bind.CallOpts)) *AggchainFEPCaller_GetAggchainSigners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *AggchainFEPCaller_GetAggchainSigners_Call) Return(_a0 []common.Address, _a1 error) *AggchainFEPCaller_GetAggchainSigners_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggchainFEPCaller_GetAggchainSigners_Call) RunAndReturn(run func(*bind.CallOpts) ([]common.Address, error)) *AggchainFEPCaller_GetAggchainSigners_Call {
	_c.Call.Return(run)
	return _c
}

// LatestBlockNumber provides a mock function with given fields: opts
func (_m *AggchainFEPCaller) LatestBlockNumber(opts *bind.CallOpts) (*big.Int, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for LatestBlockNumber")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) (*big.Int, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) *big.Int); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggchainFEPCaller_LatestBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestBlockNumber'
type AggchainFEPCaller_LatestBlockNumber_Call struct {
	*mock.Call
}

// LatestBlockNumber is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *AggchainFEPCaller_Expecter) LatestBlockNumber(opts interface{}) *AggchainFEPCaller_LatestBlockNumber_Call {
	return &AggchainFEPCaller_LatestBlockNumber_Call{Call: _e.mock.On("LatestBlockNumber", opts)}
}

func (_c *AggchainFEPCaller_LatestBlockNumber_Call) Run(run func(opts *bind.CallOpts)) *AggchainFEPCaller_LatestBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *AggchainFEPCaller_LatestBlockNumber_Call) Return(_a0 *big.Int, _a1 error) *AggchainFEPCaller_LatestBlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggchainFEPCaller_LatestBlockNumber_Call) RunAndReturn(run func(*bind.CallOpts) (*big.Int, error)) *AggchainFEPCaller_LatestBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// OptimisticMode provides a mock function with given fields: opts
func (_m *AggchainFEPCaller) OptimisticMode(opts *bind.CallOpts) (bool, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for OptimisticMode")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) (bool, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) bool); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggchainFEPCaller_OptimisticMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OptimisticMode'
type AggchainFEPCaller_OptimisticMode_Call struct {
	*mock.Call
}

// OptimisticMode is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *AggchainFEPCaller_Expecter) OptimisticMode(opts interface{}) *AggchainFEPCaller_OptimisticMode_Call {
	return &AggchainFEPCaller_OptimisticMode_Call{Call: _e.mock.On("OptimisticMode", opts)}
}

func (_c *AggchainFEPCaller_OptimisticMode_Call) Run(run func(opts *bind.CallOpts)) *AggchainFEPCaller_OptimisticMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *AggchainFEPCaller_OptimisticMode_Call) Return(_a0 bool, _a1 error) *AggchainFEPCaller_OptimisticMode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggchainFEPCaller_OptimisticMode_Call) RunAndReturn(run func(*bind.CallOpts) (bool, error)) *AggchainFEPCaller_OptimisticMode_Call {
	_c.Call.Return(run)
	return _c
}

// RangeVkeyCommitment provides a mock function with given fields: opts
func (_m *AggchainFEPCaller) RangeVkeyCommitment(opts *bind.CallOpts) ([32]byte, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for RangeVkeyCommitment")
	}

	var r0 [32]byte
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) ([32]byte, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) [32]byte); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([32]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggchainFEPCaller_RangeVkeyCommitment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RangeVkeyCommitment'
type AggchainFEPCaller_RangeVkeyCommitment_Call struct {
	*mock.Call
}

// RangeVkeyCommitment is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *AggchainFEPCaller_Expecter) RangeVkeyCommitment(opts interface{}) *AggchainFEPCaller_RangeVkeyCommitment_Call {
	return &AggchainFEPCaller_RangeVkeyCommitment_Call{Call: _e.mock.On("RangeVkeyCommitment", opts)}
}

func (_c *AggchainFEPCaller_RangeVkeyCommitment_Call) Run(run func(opts *bind.CallOpts)) *AggchainFEPCaller_RangeVkeyCommitment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *AggchainFEPCaller_RangeVkeyCommitment_Call) Return(_a0 [32]byte, _a1 error) *AggchainFEPCaller_RangeVkeyCommitment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggchainFEPCaller_RangeVkeyCommitment_Call) RunAndReturn(run func(*bind.CallOpts) ([32]byte, error)) *AggchainFEPCaller_RangeVkeyCommitment_Call {
	_c.Call.Return(run)
	return _c
}

// RollupConfigHash provides a mock function with given fields: opts
func (_m *AggchainFEPCaller) RollupConfigHash(opts *bind.CallOpts) ([32]byte, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for RollupConfigHash")
	}

	var r0 [32]byte
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) ([32]byte, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) [32]byte); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([32]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggchainFEPCaller_RollupConfigHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollupConfigHash'
type AggchainFEPCaller_RollupConfigHash_Call struct {
	*mock.Call
}

// RollupConfigHash is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *AggchainFEPCaller_Expecter) RollupConfigHash(opts interface{}) *AggchainFEPCaller_RollupConfigHash_Call {
	return &AggchainFEPCaller_RollupConfigHash_Call{Call: _e.mock.On("RollupConfigHash", opts)}
}

func (_c *AggchainFEPCaller_RollupConfigHash_Call) Run(run func(opts *bind.CallOpts)) *AggchainFEPCaller_RollupConfigHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *AggchainFEPCaller_RollupConfigHash_Call) Return(_a0 [32]byte, _a1 error) *AggchainFEPCaller_RollupConfigHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggchainFEPCaller_RollupConfigHash_Call) RunAndReturn(run func(*bind.CallOpts) ([32]byte, error)) *AggchainFEPCaller_RollupConfigHash_Call {
	_c.Call.Return(run)
	return _c
}

// StartingBlockNumber provides a mock function with given fields: opts
func (_m *AggchainFEPCaller) StartingBlockNumber(opts *bind.CallOpts) (*big.Int, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for StartingBlockNumber")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) (*big.Int, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) *big.Int); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggchainFEPCaller_StartingBlockNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartingBlockNumber'
type AggchainFEPCaller_StartingBlockNumber_Call struct {
	*mock.Call
}

// StartingBlockNumber is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *AggchainFEPCaller_Expecter) StartingBlockNumber(opts interface{}) *AggchainFEPCaller_StartingBlockNumber_Call {
	return &AggchainFEPCaller_StartingBlockNumber_Call{Call: _e.mock.On("StartingBlockNumber", opts)}
}

func (_c *AggchainFEPCaller_StartingBlockNumber_Call) Run(run func(opts *bind.CallOpts)) *AggchainFEPCaller_StartingBlockNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *AggchainFEPCaller_StartingBlockNumber_Call) Return(_a0 *big.Int, _a1 error) *AggchainFEPCaller_StartingBlockNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggchainFEPCaller_StartingBlockNumber_Call) RunAndReturn(run func(*bind.CallOpts) (*big.Int, error)) *AggchainFEPCaller_StartingBlockNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewAggchainFEPCaller creates a new instance of AggchainFEPCaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAggchainFEPCaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *AggchainFEPCaller {
	mock := &AggchainFEPCaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
