// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/aggsender/types"
)

// MultisigQuerier is an autogenerated mock type for the MultisigQuerier type
type MultisigQuerier struct {
	mock.Mock
}

type MultisigQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MultisigQuerier) EXPECT() *MultisigQuerier_Expecter {
	return &MultisigQuerier_Expecter{mock: &_m.Mock}
}

// GetMultisigCommittee provides a mock function with given fields: ctx, blockNum
func (_m *MultisigQuerier) GetMultisigCommittee(ctx context.Context, blockNum *big.Int) (*types.MultisigCommittee, error) {
	ret := _m.Called(ctx, blockNum)

	if len(ret) == 0 {
		panic("no return value specified for GetMultisigCommittee")
	}

	var r0 *types.MultisigCommittee
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int) (*types.MultisigCommittee, error)); ok {
		return rf(ctx, blockNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int) *types.MultisigCommittee); ok {
		r0 = rf(ctx, blockNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MultisigCommittee)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *big.Int) error); ok {
		r1 = rf(ctx, blockNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MultisigQuerier_GetMultisigCommittee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMultisigCommittee'
type MultisigQuerier_GetMultisigCommittee_Call struct {
	*mock.Call
}

// GetMultisigCommittee is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNum *big.Int
func (_e *MultisigQuerier_Expecter) GetMultisigCommittee(ctx interface{}, blockNum interface{}) *MultisigQuerier_GetMultisigCommittee_Call {
	return &MultisigQuerier_GetMultisigCommittee_Call{Call: _e.mock.On("GetMultisigCommittee", ctx, blockNum)}
}

func (_c *MultisigQuerier_GetMultisigCommittee_Call) Run(run func(ctx context.Context, blockNum *big.Int)) *MultisigQuerier_GetMultisigCommittee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*big.Int))
	})
	return _c
}

func (_c *MultisigQuerier_GetMultisigCommittee_Call) Return(_a0 *types.MultisigCommittee, _a1 error) *MultisigQuerier_GetMultisigCommittee_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MultisigQuerier_GetMultisigCommittee_Call) RunAndReturn(run func(context.Context, *big.Int) (*types.MultisigCommittee, error)) *MultisigQuerier_GetMultisigCommittee_Call {
	_c.Call.Return(run)
	return _c
}

// NewMultisigQuerier creates a new instance of MultisigQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMultisigQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MultisigQuerier {
	mock := &MultisigQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
