// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	bridgesync "github.com/agglayer/aggkit/bridgesync"
	common "github.com/ethereum/go-ethereum/common"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BridgeDataQuerier is an autogenerated mock type for the BridgeDataQuerier type
type BridgeDataQuerier struct {
	mock.Mock
}

type BridgeDataQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *BridgeDataQuerier) EXPECT() *BridgeDataQuerier_Expecter {
	return &BridgeDataQuerier_Expecter{mock: &_m.Mock}
}

// GetBridgesAndClaims provides a mock function with given fields: ctx, fromBlock, toBlock
func (_m *BridgeDataQuerier) GetBridgesAndClaims(ctx context.Context, fromBlock uint64, toBlock uint64) ([]bridgesync.Bridge, []bridgesync.Claim, error) {
	ret := _m.Called(ctx, fromBlock, toBlock)

	if len(ret) == 0 {
		panic("no return value specified for GetBridgesAndClaims")
	}

	var r0 []bridgesync.Bridge
	var r1 []bridgesync.Claim
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]bridgesync.Bridge, []bridgesync.Claim, error)); ok {
		return rf(ctx, fromBlock, toBlock)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []bridgesync.Bridge); ok {
		r0 = rf(ctx, fromBlock, toBlock)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bridgesync.Bridge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) []bridgesync.Claim); ok {
		r1 = rf(ctx, fromBlock, toBlock)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]bridgesync.Claim)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64, uint64) error); ok {
		r2 = rf(ctx, fromBlock, toBlock)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BridgeDataQuerier_GetBridgesAndClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBridgesAndClaims'
type BridgeDataQuerier_GetBridgesAndClaims_Call struct {
	*mock.Call
}

// GetBridgesAndClaims is a helper method to define mock.On call
//   - ctx context.Context
//   - fromBlock uint64
//   - toBlock uint64
func (_e *BridgeDataQuerier_Expecter) GetBridgesAndClaims(ctx interface{}, fromBlock interface{}, toBlock interface{}) *BridgeDataQuerier_GetBridgesAndClaims_Call {
	return &BridgeDataQuerier_GetBridgesAndClaims_Call{Call: _e.mock.On("GetBridgesAndClaims", ctx, fromBlock, toBlock)}
}

func (_c *BridgeDataQuerier_GetBridgesAndClaims_Call) Run(run func(ctx context.Context, fromBlock uint64, toBlock uint64)) *BridgeDataQuerier_GetBridgesAndClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *BridgeDataQuerier_GetBridgesAndClaims_Call) Return(_a0 []bridgesync.Bridge, _a1 []bridgesync.Claim, _a2 error) *BridgeDataQuerier_GetBridgesAndClaims_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *BridgeDataQuerier_GetBridgesAndClaims_Call) RunAndReturn(run func(context.Context, uint64, uint64) ([]bridgesync.Bridge, []bridgesync.Claim, error)) *BridgeDataQuerier_GetBridgesAndClaims_Call {
	_c.Call.Return(run)
	return _c
}

// GetExitRootByIndex provides a mock function with given fields: ctx, index
func (_m *BridgeDataQuerier) GetExitRootByIndex(ctx context.Context, index uint32) (common.Hash, error) {
	ret := _m.Called(ctx, index)

	if len(ret) == 0 {
		panic("no return value specified for GetExitRootByIndex")
	}

	var r0 common.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (common.Hash, error)); ok {
		return rf(ctx, index)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) common.Hash); ok {
		r0 = rf(ctx, index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, index)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BridgeDataQuerier_GetExitRootByIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExitRootByIndex'
type BridgeDataQuerier_GetExitRootByIndex_Call struct {
	*mock.Call
}

// GetExitRootByIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - index uint32
func (_e *BridgeDataQuerier_Expecter) GetExitRootByIndex(ctx interface{}, index interface{}) *BridgeDataQuerier_GetExitRootByIndex_Call {
	return &BridgeDataQuerier_GetExitRootByIndex_Call{Call: _e.mock.On("GetExitRootByIndex", ctx, index)}
}

func (_c *BridgeDataQuerier_GetExitRootByIndex_Call) Run(run func(ctx context.Context, index uint32)) *BridgeDataQuerier_GetExitRootByIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *BridgeDataQuerier_GetExitRootByIndex_Call) Return(_a0 common.Hash, _a1 error) *BridgeDataQuerier_GetExitRootByIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BridgeDataQuerier_GetExitRootByIndex_Call) RunAndReturn(run func(context.Context, uint32) (common.Hash, error)) *BridgeDataQuerier_GetExitRootByIndex_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastProcessedBlock provides a mock function with given fields: ctx
func (_m *BridgeDataQuerier) GetLastProcessedBlock(ctx context.Context) (uint64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastProcessedBlock")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (uint64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BridgeDataQuerier_GetLastProcessedBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastProcessedBlock'
type BridgeDataQuerier_GetLastProcessedBlock_Call struct {
	*mock.Call
}

// GetLastProcessedBlock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BridgeDataQuerier_Expecter) GetLastProcessedBlock(ctx interface{}) *BridgeDataQuerier_GetLastProcessedBlock_Call {
	return &BridgeDataQuerier_GetLastProcessedBlock_Call{Call: _e.mock.On("GetLastProcessedBlock", ctx)}
}

func (_c *BridgeDataQuerier_GetLastProcessedBlock_Call) Run(run func(ctx context.Context)) *BridgeDataQuerier_GetLastProcessedBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *BridgeDataQuerier_GetLastProcessedBlock_Call) Return(_a0 uint64, _a1 error) *BridgeDataQuerier_GetLastProcessedBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BridgeDataQuerier_GetLastProcessedBlock_Call) RunAndReturn(run func(context.Context) (uint64, error)) *BridgeDataQuerier_GetLastProcessedBlock_Call {
	_c.Call.Return(run)
	return _c
}

// OriginNetwork provides a mock function with no fields
func (_m *BridgeDataQuerier) OriginNetwork() uint32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OriginNetwork")
	}

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

// BridgeDataQuerier_OriginNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OriginNetwork'
type BridgeDataQuerier_OriginNetwork_Call struct {
	*mock.Call
}

// OriginNetwork is a helper method to define mock.On call
func (_e *BridgeDataQuerier_Expecter) OriginNetwork() *BridgeDataQuerier_OriginNetwork_Call {
	return &BridgeDataQuerier_OriginNetwork_Call{Call: _e.mock.On("OriginNetwork")}
}

func (_c *BridgeDataQuerier_OriginNetwork_Call) Run(run func()) *BridgeDataQuerier_OriginNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BridgeDataQuerier_OriginNetwork_Call) Return(_a0 uint32) *BridgeDataQuerier_OriginNetwork_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BridgeDataQuerier_OriginNetwork_Call) RunAndReturn(run func() uint32) *BridgeDataQuerier_OriginNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// NewBridgeDataQuerier creates a new instance of BridgeDataQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBridgeDataQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *BridgeDataQuerier {
	mock := &BridgeDataQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
