// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/agglayer/aggkit/aggsender/validator/proto/v1"
)

// AggsenderValidatorClient is an autogenerated mock type for the AggsenderValidatorClient type
type AggsenderValidatorClient struct {
	mock.Mock
}

type AggsenderValidatorClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AggsenderValidatorClient) EXPECT() *AggsenderValidatorClient_Expecter {
	return &AggsenderValidatorClient_Expecter{mock: &_m.Mock}
}

// HealthCheck provides a mock function with given fields: ctx, in, opts
func (_m *AggsenderValidatorClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*v1.HealthCheckResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 *v1.HealthCheckResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*v1.HealthCheckResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *v1.HealthCheckResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.HealthCheckResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggsenderValidatorClient_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type AggsenderValidatorClient_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - in *emptypb.Empty
//   - opts ...grpc.CallOption
func (_e *AggsenderValidatorClient_Expecter) HealthCheck(ctx interface{}, in interface{}, opts ...interface{}) *AggsenderValidatorClient_HealthCheck_Call {
	return &AggsenderValidatorClient_HealthCheck_Call{Call: _e.mock.On("HealthCheck",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *AggsenderValidatorClient_HealthCheck_Call) Run(run func(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption)) *AggsenderValidatorClient_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*emptypb.Empty), variadicArgs...)
	})
	return _c
}

func (_c *AggsenderValidatorClient_HealthCheck_Call) Return(_a0 *v1.HealthCheckResponse, _a1 error) *AggsenderValidatorClient_HealthCheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggsenderValidatorClient_HealthCheck_Call) RunAndReturn(run func(context.Context, *emptypb.Empty, ...grpc.CallOption) (*v1.HealthCheckResponse, error)) *AggsenderValidatorClient_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCertificate provides a mock function with given fields: ctx, in, opts
func (_m *AggsenderValidatorClient) ValidateCertificate(ctx context.Context, in *v1.ValidateCertificateRequest, opts ...grpc.CallOption) (*v1.ValidateCertificateResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCertificate")
	}

	var r0 *v1.ValidateCertificateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ValidateCertificateRequest, ...grpc.CallOption) (*v1.ValidateCertificateResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ValidateCertificateRequest, ...grpc.CallOption) *v1.ValidateCertificateResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ValidateCertificateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ValidateCertificateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggsenderValidatorClient_ValidateCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCertificate'
type AggsenderValidatorClient_ValidateCertificate_Call struct {
	*mock.Call
}

// ValidateCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ValidateCertificateRequest
//   - opts ...grpc.CallOption
func (_e *AggsenderValidatorClient_Expecter) ValidateCertificate(ctx interface{}, in interface{}, opts ...interface{}) *AggsenderValidatorClient_ValidateCertificate_Call {
	return &AggsenderValidatorClient_ValidateCertificate_Call{Call: _e.mock.On("ValidateCertificate",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *AggsenderValidatorClient_ValidateCertificate_Call) Run(run func(ctx context.Context, in *v1.ValidateCertificateRequest, opts ...grpc.CallOption)) *AggsenderValidatorClient_ValidateCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1.ValidateCertificateRequest), variadicArgs...)
	})
	return _c
}

func (_c *AggsenderValidatorClient_ValidateCertificate_Call) Return(_a0 *v1.ValidateCertificateResponse, _a1 error) *AggsenderValidatorClient_ValidateCertificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggsenderValidatorClient_ValidateCertificate_Call) RunAndReturn(run func(context.Context, *v1.ValidateCertificateRequest, ...grpc.CallOption) (*v1.ValidateCertificateResponse, error)) *AggsenderValidatorClient_ValidateCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateGER provides a mock function with given fields: ctx, in, opts
func (_m *AggsenderValidatorClient) ValidateGER(ctx context.Context, in *v1.ValidateGERRequest, opts ...grpc.CallOption) (*v1.ValidateGERResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ValidateGER")
	}

	var r0 *v1.ValidateGERResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ValidateGERRequest, ...grpc.CallOption) (*v1.ValidateGERResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ValidateGERRequest, ...grpc.CallOption) *v1.ValidateGERResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ValidateGERResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ValidateGERRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggsenderValidatorClient_ValidateGER_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateGER'
type AggsenderValidatorClient_ValidateGER_Call struct {
	*mock.Call
}

// ValidateGER is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ValidateGERRequest
//   - opts ...grpc.CallOption
func (_e *AggsenderValidatorClient_Expecter) ValidateGER(ctx interface{}, in interface{}, opts ...interface{}) *AggsenderValidatorClient_ValidateGER_Call {
	return &AggsenderValidatorClient_ValidateGER_Call{Call: _e.mock.On("ValidateGER",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *AggsenderValidatorClient_ValidateGER_Call) Run(run func(ctx context.Context, in *v1.ValidateGERRequest, opts ...grpc.CallOption)) *AggsenderValidatorClient_ValidateGER_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*v1.ValidateGERRequest), variadicArgs...)
	})
	return _c
}

func (_c *AggsenderValidatorClient_ValidateGER_Call) Return(_a0 *v1.ValidateGERResponse, _a1 error) *AggsenderValidatorClient_ValidateGER_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggsenderValidatorClient_ValidateGER_Call) RunAndReturn(run func(context.Context, *v1.ValidateGERRequest, ...grpc.CallOption) (*v1.ValidateGERResponse, error)) *AggsenderValidatorClient_ValidateGER_Call {
	_c.Call.Return(run)
	return _c
}

// NewAggsenderValidatorClient creates a new instance of AggsenderValidatorClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAggsenderValidatorClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AggsenderValidatorClient {
	mock := &AggsenderValidatorClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
