// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	big "math/big"

	aggchainecdsamultisig "github.com/0xPolygon/cdk-contracts-tooling/contracts/fep/aggchain-ecdsa-multisig/aggchainecdsamultisig"

	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"

	mock "github.com/stretchr/testify/mock"
)

// MultisigContract is an autogenerated mock type for the MultisigContract type
type MultisigContract struct {
	mock.Mock
}

type MultisigContract_Expecter struct {
	mock *mock.Mock
}

func (_m *MultisigContract) EXPECT() *MultisigContract_Expecter {
	return &MultisigContract_Expecter{mock: &_m.Mock}
}

// GetAggchainSignerInfos provides a mock function with given fields: opts
func (_m *MultisigContract) GetAggchainSignerInfos(opts *bind.CallOpts) ([]aggchainecdsamultisig.IAggchainSignersSignerInfo, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for GetAggchainSignerInfos")
	}

	var r0 []aggchainecdsamultisig.IAggchainSignersSignerInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) ([]aggchainecdsamultisig.IAggchainSignersSignerInfo, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) []aggchainecdsamultisig.IAggchainSignersSignerInfo); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]aggchainecdsamultisig.IAggchainSignersSignerInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MultisigContract_GetAggchainSignerInfos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAggchainSignerInfos'
type MultisigContract_GetAggchainSignerInfos_Call struct {
	*mock.Call
}

// GetAggchainSignerInfos is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *MultisigContract_Expecter) GetAggchainSignerInfos(opts interface{}) *MultisigContract_GetAggchainSignerInfos_Call {
	return &MultisigContract_GetAggchainSignerInfos_Call{Call: _e.mock.On("GetAggchainSignerInfos", opts)}
}

func (_c *MultisigContract_GetAggchainSignerInfos_Call) Run(run func(opts *bind.CallOpts)) *MultisigContract_GetAggchainSignerInfos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *MultisigContract_GetAggchainSignerInfos_Call) Return(_a0 []aggchainecdsamultisig.IAggchainSignersSignerInfo, _a1 error) *MultisigContract_GetAggchainSignerInfos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MultisigContract_GetAggchainSignerInfos_Call) RunAndReturn(run func(*bind.CallOpts) ([]aggchainecdsamultisig.IAggchainSignersSignerInfo, error)) *MultisigContract_GetAggchainSignerInfos_Call {
	_c.Call.Return(run)
	return _c
}

// Threshold provides a mock function with given fields: opts
func (_m *MultisigContract) Threshold(opts *bind.CallOpts) (*big.Int, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Threshold")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) (*big.Int, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) *big.Int); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MultisigContract_Threshold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Threshold'
type MultisigContract_Threshold_Call struct {
	*mock.Call
}

// Threshold is a helper method to define mock.On call
//   - opts *bind.CallOpts
func (_e *MultisigContract_Expecter) Threshold(opts interface{}) *MultisigContract_Threshold_Call {
	return &MultisigContract_Threshold_Call{Call: _e.mock.On("Threshold", opts)}
}

func (_c *MultisigContract_Threshold_Call) Run(run func(opts *bind.CallOpts)) *MultisigContract_Threshold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bind.CallOpts))
	})
	return _c
}

func (_c *MultisigContract_Threshold_Call) Return(_a0 *big.Int, _a1 error) *MultisigContract_Threshold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MultisigContract_Threshold_Call) RunAndReturn(run func(*bind.CallOpts) (*big.Int, error)) *MultisigContract_Threshold_Call {
	_c.Call.Return(run)
	return _c
}

// NewMultisigContract creates a new instance of MultisigContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMultisigContract(t interface {
	mock.TestingT
	Cleanup(func())
}) *MultisigContract {
	mock := &MultisigContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
