// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	l1infotreesync "github.com/agglayer/aggkit/l1infotreesync"

	mock "github.com/stretchr/testify/mock"

	treetypes "github.com/agglayer/aggkit/tree/types"

	types "github.com/agglayer/aggkit/types"
)

// L1InfoTreeSyncer is an autogenerated mock type for the L1InfoTreeSyncer type
type L1InfoTreeSyncer struct {
	mock.Mock
}

type L1InfoTreeSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *L1InfoTreeSyncer) EXPECT() *L1InfoTreeSyncer_Expecter {
	return &L1InfoTreeSyncer_Expecter{mock: &_m.Mock}
}

// Finality provides a mock function with no fields
func (_m *L1InfoTreeSyncer) Finality() types.BlockNumberFinality {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Finality")
	}

	var r0 types.BlockNumberFinality
	if rf, ok := ret.Get(0).(func() types.BlockNumberFinality); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.BlockNumberFinality)
	}

	return r0
}

// L1InfoTreeSyncer_Finality_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finality'
type L1InfoTreeSyncer_Finality_Call struct {
	*mock.Call
}

// Finality is a helper method to define mock.On call
func (_e *L1InfoTreeSyncer_Expecter) Finality() *L1InfoTreeSyncer_Finality_Call {
	return &L1InfoTreeSyncer_Finality_Call{Call: _e.mock.On("Finality")}
}

func (_c *L1InfoTreeSyncer_Finality_Call) Run(run func()) *L1InfoTreeSyncer_Finality_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *L1InfoTreeSyncer_Finality_Call) Return(_a0 types.BlockNumberFinality) *L1InfoTreeSyncer_Finality_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *L1InfoTreeSyncer_Finality_Call) RunAndReturn(run func() types.BlockNumberFinality) *L1InfoTreeSyncer_Finality_Call {
	_c.Call.Return(run)
	return _c
}

// GetInfoByGlobalExitRoot provides a mock function with given fields: globalExitRoot
func (_m *L1InfoTreeSyncer) GetInfoByGlobalExitRoot(globalExitRoot common.Hash) (*l1infotreesync.L1InfoTreeLeaf, error) {
	ret := _m.Called(globalExitRoot)

	if len(ret) == 0 {
		panic("no return value specified for GetInfoByGlobalExitRoot")
	}

	var r0 *l1infotreesync.L1InfoTreeLeaf
	var r1 error
	if rf, ok := ret.Get(0).(func(common.Hash) (*l1infotreesync.L1InfoTreeLeaf, error)); ok {
		return rf(globalExitRoot)
	}
	if rf, ok := ret.Get(0).(func(common.Hash) *l1infotreesync.L1InfoTreeLeaf); ok {
		r0 = rf(globalExitRoot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*l1infotreesync.L1InfoTreeLeaf)
		}
	}

	if rf, ok := ret.Get(1).(func(common.Hash) error); ok {
		r1 = rf(globalExitRoot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// L1InfoTreeSyncer_GetInfoByGlobalExitRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfoByGlobalExitRoot'
type L1InfoTreeSyncer_GetInfoByGlobalExitRoot_Call struct {
	*mock.Call
}

// GetInfoByGlobalExitRoot is a helper method to define mock.On call
//   - globalExitRoot common.Hash
func (_e *L1InfoTreeSyncer_Expecter) GetInfoByGlobalExitRoot(globalExitRoot interface{}) *L1InfoTreeSyncer_GetInfoByGlobalExitRoot_Call {
	return &L1InfoTreeSyncer_GetInfoByGlobalExitRoot_Call{Call: _e.mock.On("GetInfoByGlobalExitRoot", globalExitRoot)}
}

func (_c *L1InfoTreeSyncer_GetInfoByGlobalExitRoot_Call) Run(run func(globalExitRoot common.Hash)) *L1InfoTreeSyncer_GetInfoByGlobalExitRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Hash))
	})
	return _c
}

func (_c *L1InfoTreeSyncer_GetInfoByGlobalExitRoot_Call) Return(_a0 *l1infotreesync.L1InfoTreeLeaf, _a1 error) *L1InfoTreeSyncer_GetInfoByGlobalExitRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *L1InfoTreeSyncer_GetInfoByGlobalExitRoot_Call) RunAndReturn(run func(common.Hash) (*l1infotreesync.L1InfoTreeLeaf, error)) *L1InfoTreeSyncer_GetInfoByGlobalExitRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetInfoByIndex provides a mock function with given fields: ctx, index
func (_m *L1InfoTreeSyncer) GetInfoByIndex(ctx context.Context, index uint32) (*l1infotreesync.L1InfoTreeLeaf, error) {
	ret := _m.Called(ctx, index)

	if len(ret) == 0 {
		panic("no return value specified for GetInfoByIndex")
	}

	var r0 *l1infotreesync.L1InfoTreeLeaf
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (*l1infotreesync.L1InfoTreeLeaf, error)); ok {
		return rf(ctx, index)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) *l1infotreesync.L1InfoTreeLeaf); ok {
		r0 = rf(ctx, index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*l1infotreesync.L1InfoTreeLeaf)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, index)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// L1InfoTreeSyncer_GetInfoByIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfoByIndex'
type L1InfoTreeSyncer_GetInfoByIndex_Call struct {
	*mock.Call
}

// GetInfoByIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - index uint32
func (_e *L1InfoTreeSyncer_Expecter) GetInfoByIndex(ctx interface{}, index interface{}) *L1InfoTreeSyncer_GetInfoByIndex_Call {
	return &L1InfoTreeSyncer_GetInfoByIndex_Call{Call: _e.mock.On("GetInfoByIndex", ctx, index)}
}

func (_c *L1InfoTreeSyncer_GetInfoByIndex_Call) Run(run func(ctx context.Context, index uint32)) *L1InfoTreeSyncer_GetInfoByIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *L1InfoTreeSyncer_GetInfoByIndex_Call) Return(_a0 *l1infotreesync.L1InfoTreeLeaf, _a1 error) *L1InfoTreeSyncer_GetInfoByIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *L1InfoTreeSyncer_GetInfoByIndex_Call) RunAndReturn(run func(context.Context, uint32) (*l1infotreesync.L1InfoTreeLeaf, error)) *L1InfoTreeSyncer_GetInfoByIndex_Call {
	_c.Call.Return(run)
	return _c
}

// GetL1InfoTreeMerkleProofFromIndexToRoot provides a mock function with given fields: ctx, index, root
func (_m *L1InfoTreeSyncer) GetL1InfoTreeMerkleProofFromIndexToRoot(ctx context.Context, index uint32, root common.Hash) (treetypes.Proof, error) {
	ret := _m.Called(ctx, index, root)

	if len(ret) == 0 {
		panic("no return value specified for GetL1InfoTreeMerkleProofFromIndexToRoot")
	}

	var r0 treetypes.Proof
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, common.Hash) (treetypes.Proof, error)); ok {
		return rf(ctx, index, root)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, common.Hash) treetypes.Proof); ok {
		r0 = rf(ctx, index, root)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(treetypes.Proof)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, common.Hash) error); ok {
		r1 = rf(ctx, index, root)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// L1InfoTreeSyncer_GetL1InfoTreeMerkleProofFromIndexToRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetL1InfoTreeMerkleProofFromIndexToRoot'
type L1InfoTreeSyncer_GetL1InfoTreeMerkleProofFromIndexToRoot_Call struct {
	*mock.Call
}

// GetL1InfoTreeMerkleProofFromIndexToRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - index uint32
//   - root common.Hash
func (_e *L1InfoTreeSyncer_Expecter) GetL1InfoTreeMerkleProofFromIndexToRoot(ctx interface{}, index interface{}, root interface{}) *L1InfoTreeSyncer_GetL1InfoTreeMerkleProofFromIndexToRoot_Call {
	return &L1InfoTreeSyncer_GetL1InfoTreeMerkleProofFromIndexToRoot_Call{Call: _e.mock.On("GetL1InfoTreeMerkleProofFromIndexToRoot", ctx, index, root)}
}

func (_c *L1InfoTreeSyncer_GetL1InfoTreeMerkleProofFromIndexToRoot_Call) Run(run func(ctx context.Context, index uint32, root common.Hash)) *L1InfoTreeSyncer_GetL1InfoTreeMerkleProofFromIndexToRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32), args[2].(common.Hash))
	})
	return _c
}

func (_c *L1InfoTreeSyncer_GetL1InfoTreeMerkleProofFromIndexToRoot_Call) Return(_a0 treetypes.Proof, _a1 error) *L1InfoTreeSyncer_GetL1InfoTreeMerkleProofFromIndexToRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *L1InfoTreeSyncer_GetL1InfoTreeMerkleProofFromIndexToRoot_Call) RunAndReturn(run func(context.Context, uint32, common.Hash) (treetypes.Proof, error)) *L1InfoTreeSyncer_GetL1InfoTreeMerkleProofFromIndexToRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetL1InfoTreeRootByIndex provides a mock function with given fields: ctx, index
func (_m *L1InfoTreeSyncer) GetL1InfoTreeRootByIndex(ctx context.Context, index uint32) (treetypes.Root, error) {
	ret := _m.Called(ctx, index)

	if len(ret) == 0 {
		panic("no return value specified for GetL1InfoTreeRootByIndex")
	}

	var r0 treetypes.Root
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (treetypes.Root, error)); ok {
		return rf(ctx, index)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) treetypes.Root); ok {
		r0 = rf(ctx, index)
	} else {
		r0 = ret.Get(0).(treetypes.Root)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, index)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// L1InfoTreeSyncer_GetL1InfoTreeRootByIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetL1InfoTreeRootByIndex'
type L1InfoTreeSyncer_GetL1InfoTreeRootByIndex_Call struct {
	*mock.Call
}

// GetL1InfoTreeRootByIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - index uint32
func (_e *L1InfoTreeSyncer_Expecter) GetL1InfoTreeRootByIndex(ctx interface{}, index interface{}) *L1InfoTreeSyncer_GetL1InfoTreeRootByIndex_Call {
	return &L1InfoTreeSyncer_GetL1InfoTreeRootByIndex_Call{Call: _e.mock.On("GetL1InfoTreeRootByIndex", ctx, index)}
}

func (_c *L1InfoTreeSyncer_GetL1InfoTreeRootByIndex_Call) Run(run func(ctx context.Context, index uint32)) *L1InfoTreeSyncer_GetL1InfoTreeRootByIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint32))
	})
	return _c
}

func (_c *L1InfoTreeSyncer_GetL1InfoTreeRootByIndex_Call) Return(_a0 treetypes.Root, _a1 error) *L1InfoTreeSyncer_GetL1InfoTreeRootByIndex_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *L1InfoTreeSyncer_GetL1InfoTreeRootByIndex_Call) RunAndReturn(run func(context.Context, uint32) (treetypes.Root, error)) *L1InfoTreeSyncer_GetL1InfoTreeRootByIndex_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastL1InfoTreeRoot provides a mock function with given fields: ctx
func (_m *L1InfoTreeSyncer) GetLastL1InfoTreeRoot(ctx context.Context) (treetypes.Root, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastL1InfoTreeRoot")
	}

	var r0 treetypes.Root
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (treetypes.Root, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) treetypes.Root); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(treetypes.Root)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// L1InfoTreeSyncer_GetLastL1InfoTreeRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastL1InfoTreeRoot'
type L1InfoTreeSyncer_GetLastL1InfoTreeRoot_Call struct {
	*mock.Call
}

// GetLastL1InfoTreeRoot is a helper method to define mock.On call
//   - ctx context.Context
func (_e *L1InfoTreeSyncer_Expecter) GetLastL1InfoTreeRoot(ctx interface{}) *L1InfoTreeSyncer_GetLastL1InfoTreeRoot_Call {
	return &L1InfoTreeSyncer_GetLastL1InfoTreeRoot_Call{Call: _e.mock.On("GetLastL1InfoTreeRoot", ctx)}
}

func (_c *L1InfoTreeSyncer_GetLastL1InfoTreeRoot_Call) Run(run func(ctx context.Context)) *L1InfoTreeSyncer_GetLastL1InfoTreeRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *L1InfoTreeSyncer_GetLastL1InfoTreeRoot_Call) Return(_a0 treetypes.Root, _a1 error) *L1InfoTreeSyncer_GetLastL1InfoTreeRoot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *L1InfoTreeSyncer_GetLastL1InfoTreeRoot_Call) RunAndReturn(run func(context.Context) (treetypes.Root, error)) *L1InfoTreeSyncer_GetLastL1InfoTreeRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestL1InfoLeafUntilBlock provides a mock function with given fields: ctx, blockNum
func (_m *L1InfoTreeSyncer) GetLatestL1InfoLeafUntilBlock(ctx context.Context, blockNum uint64) (*l1infotreesync.L1InfoTreeLeaf, error) {
	ret := _m.Called(ctx, blockNum)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestL1InfoLeafUntilBlock")
	}

	var r0 *l1infotreesync.L1InfoTreeLeaf
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*l1infotreesync.L1InfoTreeLeaf, error)); ok {
		return rf(ctx, blockNum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *l1infotreesync.L1InfoTreeLeaf); ok {
		r0 = rf(ctx, blockNum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*l1infotreesync.L1InfoTreeLeaf)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, blockNum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// L1InfoTreeSyncer_GetLatestL1InfoLeafUntilBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestL1InfoLeafUntilBlock'
type L1InfoTreeSyncer_GetLatestL1InfoLeafUntilBlock_Call struct {
	*mock.Call
}

// GetLatestL1InfoLeafUntilBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNum uint64
func (_e *L1InfoTreeSyncer_Expecter) GetLatestL1InfoLeafUntilBlock(ctx interface{}, blockNum interface{}) *L1InfoTreeSyncer_GetLatestL1InfoLeafUntilBlock_Call {
	return &L1InfoTreeSyncer_GetLatestL1InfoLeafUntilBlock_Call{Call: _e.mock.On("GetLatestL1InfoLeafUntilBlock", ctx, blockNum)}
}

func (_c *L1InfoTreeSyncer_GetLatestL1InfoLeafUntilBlock_Call) Run(run func(ctx context.Context, blockNum uint64)) *L1InfoTreeSyncer_GetLatestL1InfoLeafUntilBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *L1InfoTreeSyncer_GetLatestL1InfoLeafUntilBlock_Call) Return(_a0 *l1infotreesync.L1InfoTreeLeaf, _a1 error) *L1InfoTreeSyncer_GetLatestL1InfoLeafUntilBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *L1InfoTreeSyncer_GetLatestL1InfoLeafUntilBlock_Call) RunAndReturn(run func(context.Context, uint64) (*l1infotreesync.L1InfoTreeLeaf, error)) *L1InfoTreeSyncer_GetLatestL1InfoLeafUntilBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetProcessedBlockUntil provides a mock function with given fields: ctx, blockNumber
func (_m *L1InfoTreeSyncer) GetProcessedBlockUntil(ctx context.Context, blockNumber uint64) (uint64, common.Hash, error) {
	ret := _m.Called(ctx, blockNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetProcessedBlockUntil")
	}

	var r0 uint64
	var r1 common.Hash
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (uint64, common.Hash, error)); ok {
		return rf(ctx, blockNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) uint64); ok {
		r0 = rf(ctx, blockNumber)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) common.Hash); ok {
		r1 = rf(ctx, blockNumber)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(common.Hash)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64) error); ok {
		r2 = rf(ctx, blockNumber)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// L1InfoTreeSyncer_GetProcessedBlockUntil_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProcessedBlockUntil'
type L1InfoTreeSyncer_GetProcessedBlockUntil_Call struct {
	*mock.Call
}

// GetProcessedBlockUntil is a helper method to define mock.On call
//   - ctx context.Context
//   - blockNumber uint64
func (_e *L1InfoTreeSyncer_Expecter) GetProcessedBlockUntil(ctx interface{}, blockNumber interface{}) *L1InfoTreeSyncer_GetProcessedBlockUntil_Call {
	return &L1InfoTreeSyncer_GetProcessedBlockUntil_Call{Call: _e.mock.On("GetProcessedBlockUntil", ctx, blockNumber)}
}

func (_c *L1InfoTreeSyncer_GetProcessedBlockUntil_Call) Run(run func(ctx context.Context, blockNumber uint64)) *L1InfoTreeSyncer_GetProcessedBlockUntil_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *L1InfoTreeSyncer_GetProcessedBlockUntil_Call) Return(_a0 uint64, _a1 common.Hash, _a2 error) *L1InfoTreeSyncer_GetProcessedBlockUntil_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *L1InfoTreeSyncer_GetProcessedBlockUntil_Call) RunAndReturn(run func(context.Context, uint64) (uint64, common.Hash, error)) *L1InfoTreeSyncer_GetProcessedBlockUntil_Call {
	_c.Call.Return(run)
	return _c
}

// IsUpToDate provides a mock function with given fields: ctx, l1Client
func (_m *L1InfoTreeSyncer) IsUpToDate(ctx context.Context, l1Client types.BaseEthereumClienter) (bool, error) {
	ret := _m.Called(ctx, l1Client)

	if len(ret) == 0 {
		panic("no return value specified for IsUpToDate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.BaseEthereumClienter) (bool, error)); ok {
		return rf(ctx, l1Client)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.BaseEthereumClienter) bool); ok {
		r0 = rf(ctx, l1Client)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.BaseEthereumClienter) error); ok {
		r1 = rf(ctx, l1Client)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// L1InfoTreeSyncer_IsUpToDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUpToDate'
type L1InfoTreeSyncer_IsUpToDate_Call struct {
	*mock.Call
}

// IsUpToDate is a helper method to define mock.On call
//   - ctx context.Context
//   - l1Client types.BaseEthereumClienter
func (_e *L1InfoTreeSyncer_Expecter) IsUpToDate(ctx interface{}, l1Client interface{}) *L1InfoTreeSyncer_IsUpToDate_Call {
	return &L1InfoTreeSyncer_IsUpToDate_Call{Call: _e.mock.On("IsUpToDate", ctx, l1Client)}
}

func (_c *L1InfoTreeSyncer_IsUpToDate_Call) Run(run func(ctx context.Context, l1Client types.BaseEthereumClienter)) *L1InfoTreeSyncer_IsUpToDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.BaseEthereumClienter))
	})
	return _c
}

func (_c *L1InfoTreeSyncer_IsUpToDate_Call) Return(_a0 bool, _a1 error) *L1InfoTreeSyncer_IsUpToDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *L1InfoTreeSyncer_IsUpToDate_Call) RunAndReturn(run func(context.Context, types.BaseEthereumClienter) (bool, error)) *L1InfoTreeSyncer_IsUpToDate_Call {
	_c.Call.Return(run)
	return _c
}

// NewL1InfoTreeSyncer creates a new instance of L1InfoTreeSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewL1InfoTreeSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *L1InfoTreeSyncer {
	mock := &L1InfoTreeSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
