// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"

	types "github.com/agglayer/aggkit/aggsender/types"
)

// AggchainFEPRollupQuerier is an autogenerated mock type for the AggchainFEPRollupQuerier type
type AggchainFEPRollupQuerier struct {
	mock.Mock
}

type AggchainFEPRollupQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *AggchainFEPRollupQuerier) EXPECT() *AggchainFEPRollupQuerier_Expecter {
	return &AggchainFEPRollupQuerier_Expecter{mock: &_m.Mock}
}

// GetAggregationProofPublicValuesData provides a mock function with given fields: lastProvenBlock, requestedEndBlock, l1InfoTreeLeafHash
func (_m *AggchainFEPRollupQuerier) GetAggregationProofPublicValuesData(lastProvenBlock uint64, requestedEndBlock uint64, l1InfoTreeLeafHash common.Hash) (*types.AggregationProofPublicValues, error) {
	ret := _m.Called(lastProvenBlock, requestedEndBlock, l1InfoTreeLeafHash)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregationProofPublicValuesData")
	}

	var r0 *types.AggregationProofPublicValues
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64, common.Hash) (*types.AggregationProofPublicValues, error)); ok {
		return rf(lastProvenBlock, requestedEndBlock, l1InfoTreeLeafHash)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64, common.Hash) *types.AggregationProofPublicValues); ok {
		r0 = rf(lastProvenBlock, requestedEndBlock, l1InfoTreeLeafHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AggregationProofPublicValues)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64, common.Hash) error); ok {
		r1 = rf(lastProvenBlock, requestedEndBlock, l1InfoTreeLeafHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggchainFEPRollupQuerier_GetAggregationProofPublicValuesData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAggregationProofPublicValuesData'
type AggchainFEPRollupQuerier_GetAggregationProofPublicValuesData_Call struct {
	*mock.Call
}

// GetAggregationProofPublicValuesData is a helper method to define mock.On call
//   - lastProvenBlock uint64
//   - requestedEndBlock uint64
//   - l1InfoTreeLeafHash common.Hash
func (_e *AggchainFEPRollupQuerier_Expecter) GetAggregationProofPublicValuesData(lastProvenBlock interface{}, requestedEndBlock interface{}, l1InfoTreeLeafHash interface{}) *AggchainFEPRollupQuerier_GetAggregationProofPublicValuesData_Call {
	return &AggchainFEPRollupQuerier_GetAggregationProofPublicValuesData_Call{Call: _e.mock.On("GetAggregationProofPublicValuesData", lastProvenBlock, requestedEndBlock, l1InfoTreeLeafHash)}
}

func (_c *AggchainFEPRollupQuerier_GetAggregationProofPublicValuesData_Call) Run(run func(lastProvenBlock uint64, requestedEndBlock uint64, l1InfoTreeLeafHash common.Hash)) *AggchainFEPRollupQuerier_GetAggregationProofPublicValuesData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64), args[1].(uint64), args[2].(common.Hash))
	})
	return _c
}

func (_c *AggchainFEPRollupQuerier_GetAggregationProofPublicValuesData_Call) Return(_a0 *types.AggregationProofPublicValues, _a1 error) *AggchainFEPRollupQuerier_GetAggregationProofPublicValuesData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggchainFEPRollupQuerier_GetAggregationProofPublicValuesData_Call) RunAndReturn(run func(uint64, uint64, common.Hash) (*types.AggregationProofPublicValues, error)) *AggchainFEPRollupQuerier_GetAggregationProofPublicValuesData_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastSettledL2Block provides a mock function with no fields
func (_m *AggchainFEPRollupQuerier) GetLastSettledL2Block() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastSettledL2Block")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AggchainFEPRollupQuerier_GetLastSettledL2Block_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastSettledL2Block'
type AggchainFEPRollupQuerier_GetLastSettledL2Block_Call struct {
	*mock.Call
}

// GetLastSettledL2Block is a helper method to define mock.On call
func (_e *AggchainFEPRollupQuerier_Expecter) GetLastSettledL2Block() *AggchainFEPRollupQuerier_GetLastSettledL2Block_Call {
	return &AggchainFEPRollupQuerier_GetLastSettledL2Block_Call{Call: _e.mock.On("GetLastSettledL2Block")}
}

func (_c *AggchainFEPRollupQuerier_GetLastSettledL2Block_Call) Run(run func()) *AggchainFEPRollupQuerier_GetLastSettledL2Block_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AggchainFEPRollupQuerier_GetLastSettledL2Block_Call) Return(_a0 uint64, _a1 error) *AggchainFEPRollupQuerier_GetLastSettledL2Block_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AggchainFEPRollupQuerier_GetLastSettledL2Block_Call) RunAndReturn(run func() (uint64, error)) *AggchainFEPRollupQuerier_GetLastSettledL2Block_Call {
	_c.Call.Return(run)
	return _c
}

// IsFEP provides a mock function with no fields
func (_m *AggchainFEPRollupQuerier) IsFEP() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsFEP")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// AggchainFEPRollupQuerier_IsFEP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFEP'
type AggchainFEPRollupQuerier_IsFEP_Call struct {
	*mock.Call
}

// IsFEP is a helper method to define mock.On call
func (_e *AggchainFEPRollupQuerier_Expecter) IsFEP() *AggchainFEPRollupQuerier_IsFEP_Call {
	return &AggchainFEPRollupQuerier_IsFEP_Call{Call: _e.mock.On("IsFEP")}
}

func (_c *AggchainFEPRollupQuerier_IsFEP_Call) Run(run func()) *AggchainFEPRollupQuerier_IsFEP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AggchainFEPRollupQuerier_IsFEP_Call) Return(_a0 bool) *AggchainFEPRollupQuerier_IsFEP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AggchainFEPRollupQuerier_IsFEP_Call) RunAndReturn(run func() bool) *AggchainFEPRollupQuerier_IsFEP_Call {
	_c.Call.Return(run)
	return _c
}

// StartL2Block provides a mock function with no fields
func (_m *AggchainFEPRollupQuerier) StartL2Block() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartL2Block")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// AggchainFEPRollupQuerier_StartL2Block_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartL2Block'
type AggchainFEPRollupQuerier_StartL2Block_Call struct {
	*mock.Call
}

// StartL2Block is a helper method to define mock.On call
func (_e *AggchainFEPRollupQuerier_Expecter) StartL2Block() *AggchainFEPRollupQuerier_StartL2Block_Call {
	return &AggchainFEPRollupQuerier_StartL2Block_Call{Call: _e.mock.On("StartL2Block")}
}

func (_c *AggchainFEPRollupQuerier_StartL2Block_Call) Run(run func()) *AggchainFEPRollupQuerier_StartL2Block_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AggchainFEPRollupQuerier_StartL2Block_Call) Return(_a0 uint64) *AggchainFEPRollupQuerier_StartL2Block_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AggchainFEPRollupQuerier_StartL2Block_Call) RunAndReturn(run func() uint64) *AggchainFEPRollupQuerier_StartL2Block_Call {
	_c.Call.Return(run)
	return _c
}

// NewAggchainFEPRollupQuerier creates a new instance of AggchainFEPRollupQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAggchainFEPRollupQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *AggchainFEPRollupQuerier {
	mock := &AggchainFEPRollupQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
