// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	types "github.com/agglayer/aggkit/aggsender/types"
	mock "github.com/stretchr/testify/mock"
)

// ProofVerifier is an autogenerated mock type for the ProofVerifier type
type ProofVerifier struct {
	mock.Mock
}

type ProofVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *ProofVerifier) EXPECT() *ProofVerifier_Expecter {
	return &ProofVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: publicInput, proof, vKey
func (_m *ProofVerifier) Verify(publicInput types.AggregationProofPublicValues, proof []byte, vKey []byte) error {
	ret := _m.Called(publicInput, proof, vKey)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.AggregationProofPublicValues, []byte, []byte) error); ok {
		r0 = rf(publicInput, proof, vKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProofVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type ProofVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - publicInput types.AggregationProofPublicValues
//   - proof []byte
//   - vKey []byte
func (_e *ProofVerifier_Expecter) Verify(publicInput interface{}, proof interface{}, vKey interface{}) *ProofVerifier_Verify_Call {
	return &ProofVerifier_Verify_Call{Call: _e.mock.On("Verify", publicInput, proof, vKey)}
}

func (_c *ProofVerifier_Verify_Call) Run(run func(publicInput types.AggregationProofPublicValues, proof []byte, vKey []byte)) *ProofVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.AggregationProofPublicValues), args[1].([]byte), args[2].([]byte))
	})
	return _c
}

func (_c *ProofVerifier_Verify_Call) Return(_a0 error) *ProofVerifier_Verify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProofVerifier_Verify_Call) RunAndReturn(run func(types.AggregationProofPublicValues, []byte, []byte) error) *ProofVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewProofVerifier creates a new instance of ProofVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProofVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProofVerifier {
	mock := &ProofVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
