// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// RoutesRegisterer is an autogenerated mock type for the RoutesRegisterer type
type RoutesRegisterer struct {
	mock.Mock
}

type RoutesRegisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *RoutesRegisterer) EXPECT() *RoutesRegisterer_Expecter {
	return &RoutesRegisterer_Expecter{mock: &_m.Mock}
}

// RegisterRoutes provides a mock function with given fields: _a0
func (_m *RoutesRegisterer) RegisterRoutes(_a0 gin.IRouter) {
	_m.Called(_a0)
}

// RoutesRegisterer_RegisterRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRoutes'
type RoutesRegisterer_RegisterRoutes_Call struct {
	*mock.Call
}

// RegisterRoutes is a helper method to define mock.On call
//   - _a0 gin.IRouter
func (_e *RoutesRegisterer_Expecter) RegisterRoutes(_a0 interface{}) *RoutesRegisterer_RegisterRoutes_Call {
	return &RoutesRegisterer_RegisterRoutes_Call{Call: _e.mock.On("RegisterRoutes", _a0)}
}

func (_c *RoutesRegisterer_RegisterRoutes_Call) Run(run func(_a0 gin.IRouter)) *RoutesRegisterer_RegisterRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(gin.IRouter))
	})
	return _c
}

func (_c *RoutesRegisterer_RegisterRoutes_Call) Return() *RoutesRegisterer_RegisterRoutes_Call {
	_c.Call.Return()
	return _c
}

func (_c *RoutesRegisterer_RegisterRoutes_Call) RunAndReturn(run func(gin.IRouter)) *RoutesRegisterer_RegisterRoutes_Call {
	_c.Run(run)
	return _c
}

// NewRoutesRegisterer creates a new instance of RoutesRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoutesRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoutesRegisterer {
	mock := &RoutesRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
