#!/bin/bash
### Common variables
KURTOSIS_ENCLAVE=aggkit
TMP_AGGKIT_FOLDER=tmp/aggkit
DEST_KURTOSIS_PARAMS_YML=../$TMP_AGGKIT_FOLDER/e2e-params.yml
KURTOSIS_FOLDER=${KURTOSIS_FOLDER:=../kurtosis-cdk}
USE_L1_GAS_TOKEN_CONTRACT=true
