name: arm_rpm_packager

on:
  push:
    branches:
      - 'main'
    paths:
      - '**'
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on:
      labels: arm-runner-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.22.x
      - name: Adding TAG to ENV
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

      - name: Adding a TAG.1 to the env
        run: echo "GIT_TAG1=`echo $(git describe --tags --abbrev=0)`" | sed 's/-/./g' >> $GITHUB_ENV

      - name: Download deps for project
        run: go mod download

      - name: Building aggkit for arm
        run: make build

      - name: Installing some dependencies
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Setup rpm package for binary
        run: |
          mkdir -p packaging/rpm/SPECS
          mkdir -p packaging/rpm/BUILD
          mkdir -p packaging/rpm/RPMS
          mkdir -p packaging/rpm/SRPMS
          
          touch packaging/rpm/aggkit.spec 
          echo "Name: aggkit" >> packaging/rpm/SPECS/aggkit.spec
          echo "Version: ${{ env.GIT_TAG1 }}" >> packaging/rpm/SPECS/aggkit.spec
          echo "Release: 1%{?dist}" >> packaging/rpm/SPECS/aggkit.spec
          echo "License: GPL/AGPL" >> packaging/rpm/SPECS/aggkit.spec
          echo "BuildArch: aarch64" >> packaging/rpm/SPECS/aggkit.spec
          echo "Summary: aggkit rpm package" >> packaging/rpm/SPECS/aggkit.spec
          
          echo "%description" >> packaging/rpm/SPECS/aggkit.spec
          echo "aggkit rpm package" >> packaging/rpm/SPECS/aggkit.spec
          
          echo "%pre" >> packaging/rpm/SPECS/aggkit.spec
          echo "getent group aggkit >/dev/null || groupadd -r aggkit" >> packaging/rpm/SPECS/aggkit.spec
          echo "getent passwd aggkit >/dev/null || useradd -s /bin/false -d /opt/aggkit -r aggkit -g aggkit" >> packaging/rpm/SPECS/aggkit.spec
          
          echo "%install" >> packaging/rpm/SPECS/aggkit.spec
          echo "mkdir -p %{buildroot}/usr/bin" >> packaging/rpm/SPECS/aggkit.spec
          echo "cp /home/runner/work/aggkit/aggkit/target/aggkit %{buildroot}/usr/bin/aggkit" >> packaging/rpm/SPECS/aggkit.spec
          echo "cp /home/runner/work/aggkit/aggkit/target/release/aggkit %{buildroot}/usr/bin/aggkit" >> packaging/rpm/SPECS/aggkit.spec
          
          echo "%files" >> packaging/rpm/SPECS/aggkit.spec
          echo "/usr/bin/aggkit" >> packaging/rpm/SPECS/aggkit.spec


      - name: Construct rpm package
        run: |
          rpmbuild --define "_topdir /home/runner/work/aggkit/aggkit/packaging/rpm_build" \
                   --define "_builddir %{_topdir}/BUILD" \
                   --define "_rpmdir %{_topdir}/RPMS" \
                   --define "_srcrpmdir %{_topdir}/SRPMS" \
                   --define "__spec_install_post /bin/true" \
                   -bb packaging/rpm/SPECS/aggkit.spec

      - name: Rename file for post rpm build and for checksum
        run: mv /home/runner/work/aggkit/aggkit/packaging/rpm_build/RPMS/aarch64/aggkit-${{ env.GIT_TAG1 }}-1.aarch64.rpm /home/runner/work/aggkit/aggkit/packaging/rpm_build/RPMS/aarch64/aggkit-${{ env.GIT_TAG1 }}.aarch64.rpm

      - name: Checksum for the rpm package
        run: sha256sum /home/runner/work/aggkit/aggkit/packaging/rpm_build/RPMS/aarch64/aggkit-${{ env.GIT_TAG1 }}.aarch64.rpm > /home/runner/work/aggkit/aggkit/packaging/rpm_build/RPMS/aarch64/aggkit-${{ env.GIT_TAG1 }}.aarch64.rpm.checksum

      - name: Release aggkit Packages
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GIT_TAG }}
          prerelease: true
          files: |
            packaging/rpm_build/RPMS/aarch64/aggkit-**.rpm
            packaging/rpm_build/RPMS/aarch64/aggkit-**.rpm.checksum
