name: Build CDK Image
on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      docker-image-name:
        required: true
        type: string

jobs:
  build-cdk-image:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Debug Workflow Setup
        run: |
          echo "Current directory:"
          pwd
          echo "List all files:"
          ls -R
          echo "Environment variables:"
          printenv
          echo "Checking if 'test' exists:"
          if [ -d "test" ]; then
            echo "'test' directory exists."
            ls -l test
          else
            echo "'test' directory does not exist!"
          fi
          echo "Checking Docker images:"
          docker image ls -a

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Build CDK Docker Image
        run: make build-docker

      - name: Save CDK Image to Archive
        run: docker save --output /tmp/${{ inputs.docker-image-name }}.tar ${{ inputs.docker-image-name }}

      - name: Upload CDK Archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.docker-image-name }}
          path: /tmp/${{ inputs.docker-image-name }}.tar
