name: Build Aggkit Image
on:
  workflow_dispatch: {}
  push:
    branches:
      - '**' # Trigger for any branch

jobs:
  build-aggkit-image:
    runs-on: amd-runner-2204
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Build Aggkit Docker Image
        run: make build-docker

      - name: Save Aggkit Image to Archive
        run: docker save --output /tmp/aggkit.tar aggkit

      - name: Upload Aggkit Archive
        uses: actions/upload-artifact@v4
        with:
          name: aggkit
          path: /tmp/aggkit.tar
