name: Setup Environment
on:
  workflow_call:
    inputs:
      kurtosis-repository:
        required: true
        type: string
      kurtosis-ref:
        required: false
        type: string
      docker-image-name:
        required: true
        type: string

jobs:
  setup-environment:
    runs-on: amd-runner-2204
    steps:
      - name: Debug Workflow Setup (pre-setup)
        run: |
          echo "Current directory:"
          pwd
          echo "List all files:"
          ls -R
          echo "Environment variables:"
          printenv
          echo "Checking if 'test' exists:"
          if [ -d "test" ]; then
            echo "'test' directory exists."
            ls -l test
          else
            echo "'test' directory does not exist!"
          fi
          echo "Checking Docker images:"
          docker image ls -a

      - name: Checkout Kurtosis CDK
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.kurtosis-repository }}
          path: kurtosis-cdk
          ref: ${{ inputs.kurtosis-ref }}

      - name: Install Kurtosis CDK Tools
        uses: ./kurtosis-cdk/.github/actions/setup-kurtosis-cdk

      - name: Setup Bats and Bats Libs
        uses: bats-core/bats-action@3.0.0

      - name: Download CDK Archive
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.docker-image-name }}
          path: /tmp

      - name: Load CDK Image
        run: |
          docker load --input /tmp/${{ inputs.docker-image-name }}.tar
          docker image ls -a
