# This workflow runs the Bats E2E tests for aggkit.
name: Bats E2E Tests

on:
  push:
    branches:
      - '**'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-aggkit-image:
    uses: ./.github/workflows/build-aggkit-image.yml
    with:
      go-version: 1.24.x
      docker-image-name: aggkit

  read-aggkit-args:
    name: Read aggkit args
    runs-on: ubuntu-latest
    outputs:
      # single l2 network (fork 12, op-succinct)
      kurtosis-cdk-args-single-fork12-op-succinct: ${{ steps.read-args.outputs.fork12_op_succinct_args }}
      # single l2 network (fork 12, pessimistic)
      kurtosis-cdk-args-single-fork12-pessimistic: ${{ steps.read-args.outputs.fork12_pessimistic_args }}
      # multi l2 networks
      kurtosis-cdk-args-1: ${{ steps.read-args.outputs.kurtosis-cdk-args-1 }}
      kurtosis-cdk-args-2: ${{ steps.read-args.outputs.kurtosis-cdk-args-2 }}
      kurtosis-cdk-args-3: ${{ steps.read-args.outputs.kurtosis-cdk-args-3 }}
      kurtosis-cdk-args-4: ${{ steps.read-args.outputs.kurtosis-cdk-args-4 }}
      kurtosis-cdk-args-5: ${{ steps.read-args.outputs.kurtosis-cdk-args-5 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read kurtosis-cdk-args from file
        id: read-args
        run: |
          # single l2 network (fork 12, op-succinct)
          CONTENT=$(cat ./.github/test_e2e_single_chain_fork12_op_succinct_args.json | jq -c .)
          echo "fork12_op_succinct_args=${CONTENT}" >> $GITHUB_OUTPUT
          # single l2 network (fork 12, pessimistic)
          CONTENT=$(cat ./.github/test_e2e_single_chain_fork12_pessimistic_args.json | jq -c .)
          echo "fork12_pessimistic_args=${CONTENT}" >> $GITHUB_OUTPUT
          # multi l2 networks
          CONTENT=$(cat ./.github/test_e2e_multi_chains_args_1.json | jq -c .)
          echo "kurtosis-cdk-args-1=${CONTENT}" >> $GITHUB_OUTPUT
          CONTENT=$(cat ./.github/test_e2e_multi_chains_args_2.json | jq -c .)
          echo "kurtosis-cdk-args-2=${CONTENT}" >> $GITHUB_OUTPUT
          CONTENT=$(cat ./.github/test_e2e_multi_chains_args_3.json | jq -c .)
          echo "kurtosis-cdk-args-3=${CONTENT}" >> $GITHUB_OUTPUT
          CONTENT=$(cat ./.github/test_e2e_multi_chains_args_4.json | jq -c .)
          echo "kurtosis-cdk-args-4=${CONTENT}" >> $GITHUB_OUTPUT
          CONTENT=$(cat ./.github/test_e2e_multi_chains_args_5.json | jq -c .)
          echo "kurtosis-cdk-args-5=${CONTENT}" >> $GITHUB_OUTPUT

  test-single-l2-network-fork12-pessimistic:
    name: Single L2 chain tests (pessimistic)
    needs:
      - build-aggkit-image
      - read-aggkit-args
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@60fdb6e88e57083bd21daae01483df048245f89e
    secrets: inherit
    with:
      kurtosis-cdk-ref: 71c7f2cb01cc14681a3037e7451f3653457c2145
      agglayer-e2e-ref: 60fdb6e88e57083bd21daae01483df048245f89e
      kurtosis-cdk-enclave-name: aggkit
      kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-fork12-pessimistic }}
      test-name: "test-single-l2-network-fork12-pessimistic"

  check-single-l2-network-fork12-pessimistic-tests-result:
    name: Check results for single l2 network (pessimistic)
    needs:
      - test-single-l2-network-fork12-pessimistic
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-l2-network-fork12-pessimistic.result) }}

  test-single-l2-network-fork12-op-succinct:
    name: Single L2 chain tests (op-succinct)
    needs:
      - build-aggkit-image
      - read-aggkit-args
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@60fdb6e88e57083bd21daae01483df048245f89e
    secrets: inherit
    with:
      kurtosis-cdk-ref: 71c7f2cb01cc14681a3037e7451f3653457c2145
      agglayer-e2e-ref: 60fdb6e88e57083bd21daae01483df048245f89e
      kurtosis-cdk-enclave-name: op
      kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-fork12-op-succinct }}
      test-name: "test-single-l2-network-fork12-op-succinct"

  check-single-network-fork12-op-succinct-tests-result:
    name: Check results for single l2 network (op-succinct)
    needs:
      - test-single-l2-network-fork12-op-succinct
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-l2-network-fork12-op-succinct.result) }}

  build-tools:
    name: Build aggsender find imported bridge tool
    needs:
      - build-aggkit-image
    runs-on: amd-runner-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Build Aggsender Find Imported Bridge
        run: make build-tools
      
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: aggsender_find_imported_bridge
          path: ./target/aggsender_find_imported_bridge

  test-multi-l2-networks-2-chains:
    name: Multi chains E2E test (2 chains)
    needs:
      - build-aggkit-image
      - build-tools
      - read-aggkit-args
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@60fdb6e88e57083bd21daae01483df048245f89e
    secrets: inherit
    with:
      kurtosis-cdk-ref: 71c7f2cb01cc14681a3037e7451f3653457c2145
      agglayer-e2e-ref: 60fdb6e88e57083bd21daae01483df048245f89e
      kurtosis-cdk-enclave-name: aggkit
      aggsender-find-imported-bridge-artifact: aggsender_find_imported_bridge
      kurtosis-cdk-args-1: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-1 }}
      kurtosis-cdk-args-2: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-2 }}
  
  check-multi-l2-networks-2-chains-tests-result:
    name: Check results for multi l2 networks (2 chains)
    needs:
      - test-multi-l2-networks-2-chains
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-multi-l2-networks-2-chains.result) }}

  test-multi-l2-networks-3-chains:
    name: Multi chains E2E test (3 chains)
    needs:
      - build-aggkit-image
      - build-tools
      - read-aggkit-args
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@60fdb6e88e57083bd21daae01483df048245f89e
    secrets: inherit
    with:
      kurtosis-cdk-ref: 71c7f2cb01cc14681a3037e7451f3653457c2145
      agglayer-e2e-ref: 60fdb6e88e57083bd21daae01483df048245f89e
      kurtosis-cdk-enclave-name: aggkit
      aggsender-find-imported-bridge-artifact: aggsender_find_imported_bridge
      kurtosis-cdk-args-1: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-3 }}
      kurtosis-cdk-args-2: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-4 }}
      kurtosis-cdk-args-3: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-5 }}
      number-of-chains: 3

  check-multi-l2-networks-3-chains-tests-result:
    name: Check results for multi l2 networks (3 chains)
    needs:
      - test-multi-l2-networks-3-chains
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-multi-l2-networks-3-chains.result) }}
