name: Test E2E (single chain)
on: 
  push:
    branches:
      - '**'
  workflow_dispatch: {}

jobs:
  build-aggkit-image:
    name: Build aggkit docker image
    uses: ./.github/workflows/build-aggkit-image.yml
    with:
      go-version: 1.23.x
      docker-image-name: aggkit

  test-single-e2e:
    name: Single chain E2E test
    needs:
      - build-aggkit-image
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@22665185bde0d441089c49ba68cd70ca369cc5d9
    secrets: inherit
    with:
      docker-tag: local
      kurtosis-cdk-ref: arpit/bridge-service
      docker-artifact-name: aggkit
      agglayer-e2e-ref: 22665185bde0d441089c49ba68cd70ca369cc5d9
      kurtosis-cdk-enclave-name: aggkit
      kurtosis-cdk-args: |
        args=$(cat ../test_e2e_single_chain_args.json | jq -c .)
        echo $args
        $args

  check-test-single-e2e-result:
    name: Check E2E results
    needs:
      - test-single-e2e
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-e2e.result) }}
