name: Bats E2E Tests
# This workflow runs the Bats E2E tests for aggkit.

on:
  push:
    branches:
      - "**"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AGGKIT_REPORT_CHANNEL: "C092K6Z0EUT"

jobs:
  build-aggkit-image:
    uses: ./.github/workflows/build-aggkit-image.yml
    with:
      go-version: 1.24.x
      docker-image-name: aggkit

  single-l2-chain:
    needs: build-aggkit-image
    runs-on: amd-runner-2204
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        e2e-group:
          - fork12-pessimistic
          - fork12-op-succinct

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout kurtosis-cdk
        uses: actions/checkout@v4
        with:
          repository: 0xPolygon/kurtosis-cdk
          path: kurtosis-cdk
          ref: v0.4.5

      - name: Install Kurtosis CDK tools
        uses: ./kurtosis-cdk/.github/actions/kurtosis-pre-run

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@2.0.0

      - name: Download aggkit archive
        uses: actions/download-artifact@v4
        with:
          name: aggkit
          path: /tmp

      - name: Load aggkit image
        run: |
          docker load --input /tmp/aggkit.tar
          docker image ls -a

      - name: Run E2E tests
        run: make test-e2e-${{ matrix.e2e-group }}
        working-directory: test
        env:
          KURTOSIS_FOLDER: ${{ github.workspace }}/kurtosis-cdk
          BATS_LIB_PATH: /usr/lib/
          AGGLAYER_PROVER_SP1_KEY: ${{ secrets.SP1_PRIVATE_KEY }}

      - name: Dump enclave logs
        if: failure()
        run: kurtosis dump ./dump

      - name: Generate archive name
        if: failure()
        run: |
          archive_name="dump_run_with_args_${{matrix.e2e-group}}_${{ github.run_id }}"
          echo "ARCHIVE_NAME=${archive_name}" >> "$GITHUB_ENV"
          echo "Generated archive name: ${archive_name}"

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ./dump

  multi-l2-chains:
    needs: build-aggkit-image
    runs-on: amd-runner-2204
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Build Tools
        run: make build-tools

      - name: Checkout kurtosis-cdk
        uses: actions/checkout@v4
        with:
          repository: 0xPolygon/kurtosis-cdk
          path: kurtosis-cdk
          ref: v0.4.5

      - name: Install Kurtosis CDK tools
        uses: ./kurtosis-cdk/.github/actions/kurtosis-pre-run

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@2.0.0

      - name: Download aggkit archive
        uses: actions/download-artifact@v4
        with:
          name: aggkit
          path: /tmp

      - name: Load aggkit image
        run: |
          docker load --input /tmp/aggkit.tar
          docker image ls -a

      - name: Run E2E tests
        run: make test-e2e-fork12-multi-pessimistic
        working-directory: test
        env:
          KURTOSIS_FOLDER: ${{ github.workspace }}/kurtosis-cdk
          BATS_LIB_PATH: /usr/lib/
          AGGLAYER_PROVER_SP1_KEY: ${{ secrets.SP1_PRIVATE_KEY }}

      - name: Dump enclave logs
        if: failure()
        run: kurtosis dump ./dump

      - name: Generate archive name
        if: failure()
        run: |
          archive_name="dump_run_with_args_fork12-multi-pessimistic_${{ github.run_id }}"
          echo "ARCHIVE_NAME=${archive_name}" >> "$GITHUB_ENV"
          echo "Generated archive name: ${archive_name}"

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: aggsender_find_imported_bridge
          path: ./target/aggsender_find_imported_bridge

  test-single-l2-network-fork12-pessimistic:
    name: Single L2 chain tests (pessimistic)
    needs:
      - build-aggkit-image
      - read-aggkit-args
      - get-kurtosis-cdk-commit
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@69bf5cf6cf8853b5f78a7a62d9d1ba9923b8ee95
    secrets: inherit
    with:
      kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
      agglayer-e2e-ref: 69bf5cf6cf8853b5f78a7a62d9d1ba9923b8ee95
      kurtosis-cdk-enclave-name: aggkit
      kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-fork12-pessimistic }}
      test-name: "test-single-l2-network-fork12-pessimistic"

  check-single-l2-network-fork12-pessimistic-tests-result:
    name: Check results for single l2 network (pessimistic)
    needs:
      - test-single-l2-network-fork12-pessimistic
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-l2-network-fork12-pessimistic.result) }}

  test-single-l2-network-fork12-global-index-pp-old-contracts:
    name: Single L2 chain tests (global index pp old contracts)
    needs:
      - build-aggkit-image
      - build-tools
      - read-aggkit-args
      - get-kurtosis-cdk-commit
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@69bf5cf6cf8853b5f78a7a62d9d1ba9923b8ee95
    secrets: inherit
    if: always() && github.event_name == 'schedule' && github.ref == 'refs/heads/develop'
    with:
      kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
      agglayer-e2e-ref: 69bf5cf6cf8853b5f78a7a62d9d1ba9923b8ee95
      kurtosis-cdk-enclave-name: aggkit
      kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-fork12-global-index-pp-old-contracts }}
      test-name: "test-single-l2-network-fork12-global-index-pp-old-contracts"
      aggsender-find-imported-bridge-artifact: aggsender_find_imported_bridge

  check-single-l2-network-fork12-global-index-pp-old-contracts-tests-result:
    name: Check results for single l2 network (global index pp old contracts)
    needs:
      - test-single-l2-network-fork12-global-index-pp-old-contracts
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-l2-network-fork12-global-index-pp-old-contracts.result) }}

  test-single-l2-network-fork12-op-succinct:
    name: Single L2 chain tests (op-succinct)
    needs:
      - build-aggkit-image
      - read-aggkit-args
      - get-kurtosis-cdk-commit
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@69bf5cf6cf8853b5f78a7a62d9d1ba9923b8ee95
    secrets: inherit
    with:
      kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
      agglayer-e2e-ref: 69bf5cf6cf8853b5f78a7a62d9d1ba9923b8ee95
      kurtosis-cdk-enclave-name: op
      kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-single-fork12-op-succinct }}
      test-name: "test-single-l2-network-fork12-op-succinct"

  check-single-network-fork12-op-succinct-tests-result:
    name: Check results for single l2 network (op-succinct)
    needs:
      - test-single-l2-network-fork12-op-succinct
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-l2-network-fork12-op-succinct.result) }}

  test-multi-l2-networks-2-chains:
    name: Multi chains E2E test (2 chains)
    needs:
      - build-aggkit-image
      - build-tools
      - read-aggkit-args
      - get-kurtosis-cdk-commit
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@69bf5cf6cf8853b5f78a7a62d9d1ba9923b8ee95
    secrets: inherit
    with:
      kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
      agglayer-e2e-ref: 69bf5cf6cf8853b5f78a7a62d9d1ba9923b8ee95
      kurtosis-cdk-enclave-name: aggkit
      aggsender-find-imported-bridge-artifact: aggsender_find_imported_bridge
      kurtosis-cdk-args-1: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-1 }}
      kurtosis-cdk-args-2: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-2 }}

  check-multi-l2-networks-2-chains-tests-result:
    name: Check results for multi l2 networks (2 chains)
    needs:
      - test-multi-l2-networks-2-chains
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-multi-l2-networks-2-chains.result) }}

  test-multi-l2-networks-3-chains:
    name: Multi chains E2E test (3 chains)
    needs:
      - build-aggkit-image
      - build-tools
      - read-aggkit-args
      - get-kurtosis-cdk-commit
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-multi-chains.yml@69bf5cf6cf8853b5f78a7a62d9d1ba9923b8ee95
    secrets: inherit
    with:
      kurtosis-cdk-ref: ${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}
      agglayer-e2e-ref: 69bf5cf6cf8853b5f78a7a62d9d1ba9923b8ee95
      kurtosis-cdk-enclave-name: aggkit
      aggsender-find-imported-bridge-artifact: aggsender_find_imported_bridge
      kurtosis-cdk-args-1: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-3 }}
      kurtosis-cdk-args-2: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-4 }}
      kurtosis-cdk-args-3: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args-5 }}
      number-of-chains: 3

  check-multi-l2-networks-3-chains-tests-result:
    name: Check results for multi l2 networks (3 chains)
    needs:
      - test-multi-l2-networks-3-chains
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-multi-l2-networks-3-chains.result) }}

  notify-slack:
    name: Notify Slack
    needs:
      - test-single-l2-network-fork12-pessimistic
      - test-single-l2-network-fork12-op-succinct
      - test-multi-l2-networks-2-chains
      - test-multi-l2-networks-3-chains
      - test-single-l2-network-fork12-global-index-pp-old-contracts
      - get-kurtosis-cdk-commit
    runs-on: ubuntu-latest
    if: always() && github.event_name == 'schedule' && github.ref == 'refs/heads/develop'
    steps:
      - name: Send Slack notification
        uses: agglayer/gha-notify-generic@v1
        with:
          slack-bot-token: ${{ secrets.SLACK_APP_TOKEN_AGGLAYER_NOTIFY_GENERIC }}
          channel-id: ${{ env.AGGKIT_REPORT_CHANNEL }}
          message: |
            Daily E2E Tests Report

            Kurtosis CDK Commit: `${{ needs.get-kurtosis-cdk-commit.outputs.kurtosis-commit }}`

            Test Results:
            • Single L2 (pessimistic): ${{ needs.test-single-l2-network-fork12-pessimistic.result == 'success' && '🟢' || '🔴' }}
            • Single L2 (op-succinct): ${{ needs.test-single-l2-network-fork12-op-succinct.result == 'success' && '🟢' || '🔴' }}
            • Multi L2 (2 chains): ${{ needs.test-multi-l2-networks-2-chains.result == 'success' && '🟢' || '🔴' }}
            • Multi L2 (3 chains): ${{ needs.test-multi-l2-networks-3-chains.result == 'success' && '🟢' || '🔴' }}
            • Single L2 (global index pp old contracts): ${{ needs.test-single-l2-network-fork12-global-index-pp-old-contracts.result == 'success' && '🟢' || '🔴' }}

            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>
