
name: Test E2E (single chain)
on: 
    push:
      branches:
        - '**'
    workflow_dispatch: {}

jobs:
  build-aggkit-image:
    uses: ./.github/workflows/build-aggkit-image.yml
    with:
      go-version: 1.24.x
      docker-image-name: aggkit
  
  test-e2e:
    needs: build-aggkit-image
    runs-on: amd-runner-2204
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        e2e-group:
          - fork12-pessimistic
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Checkout kurtosis-cdk
      uses: actions/checkout@v4
      with:
        repository: 0xPolygon/kurtosis-cdk
        path: kurtosis-cdk
        ref: 0ce0bb0e100bb86c8e7d51d8d27b7b53b29fed1f # feat/aggsender-agglayer-grpc-integration
    
    - name: Install Kurtosis CDK tools
      uses: ./kurtosis-cdk/.github/actions/setup-kurtosis-cdk
    
    - name: Setup Bats and bats libs
      uses: bats-core/bats-action@2.0.0
    
    - name: Download aggkit archive
      uses: actions/download-artifact@v4
      with:
        name: aggkit
        path: /tmp
    
    - name: Load aggkit image
      run: |
        docker load --input /tmp/aggkit.tar
        docker image ls -a

    - name: Run E2E tests
      run: make test-e2e-${{ matrix.e2e-group }}
      working-directory: test
      env:
        KURTOSIS_FOLDER: ${{ github.workspace }}/kurtosis-cdk
        BATS_LIB_PATH: /usr/lib/
        AGGLAYER_PROVER_SP1_KEY: ${{ secrets.SP1_PRIVATE_KEY }}
    
    - name: Dump enclave logs
      if: failure()
      run: kurtosis dump ./dump

    - name: Generate archive name
      if: failure()
      run: |
        archive_name="dump_run_with_args_${{matrix.e2e-group}}_${{ github.run_id }}"
        echo "ARCHIVE_NAME=${archive_name}" >> "$GITHUB_ENV"
        echo "Generated archive name: ${archive_name}"

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: ./dump
