name: Test E2E (single chain)
on: 
  push:
    branches:
      - '**'
  workflow_dispatch: {}

jobs:
  build-aggkit-image:
    name: Build aggkit docker image
    uses: ./.github/workflows/build-aggkit-image.yml
    with:
      go-version: 1.24.x
      docker-image-name: aggkit

  read-aggkit-args:
    name: Read aggkit args
    runs-on: ubuntu-latest
    outputs:
      kurtosis-cdk-args: ${{ steps.read-args.outputs.args }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read kurtosis-cdk-args from file
        id: read-args
        run: |
          CONTENT=$(cat ./.github/test_e2e_single_chain_args.json | jq -c .)
          echo "args=${CONTENT}" >> $GITHUB_OUTPUT

  test-single-e2e:
    name: Single chain E2E test
    needs:
      - build-aggkit-image
      - read-aggkit-args
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@22665185bde0d441089c49ba68cd70ca369cc5d9
    secrets: inherit
    with:
      docker-tag: local
      # TODO: we should use this one (0ce0bb0e100bb86c8e7d51d8d27b7b53b29fed1f) or continue with the arpit/bridge-service after it is rebased
      kurtosis-cdk-ref: arpit/bridge-service
      docker-artifact-name: aggkit
      agglayer-e2e-ref: 22665185bde0d441089c49ba68cd70ca369cc5d9
      kurtosis-cdk-enclave-name: aggkit
      kurtosis-cdk-args: ${{ needs.read-aggkit-args.outputs.kurtosis-cdk-args }}

  check-test-single-e2e-result:
    name: Check E2E results
    needs:
      - test-single-e2e
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-e2e.result) }}
