name: Test E2E (single chain)
on: 
  push:
    branches:
      - '**'
  workflow_dispatch: {}

jobs:
  build-aggkit-image:
    name: Build aggkit docker image
    uses: ./.github/workflows/build-aggkit-image.yml
    with:
      go-version: 1.23.x
      docker-image-name: aggkit

  test-single-e2e:
    name: Single chain E2E test
    needs:
      - build-aggkit-image
    uses: agglayer/e2e/.github/workflows/aggkit-e2e-single-chain.yml@44eb14615e8787358ea94b778db71025a0173ef1
    secrets: inherit
    with:
      docker-tag: local
      kurtosis-cdk-ref: arpit/bridge-service
      docker-artifact-name: aggkit
      agglayer-e2e-ref: 44eb14615e8787358ea94b778db71025a0173ef1
      kurtosis-cdk-enclave-name: aggkit
      kurtosis-cdk-args: |
        {
          "deployment_stages": {
            "deploy_l2_contracts": true
          },
          "args": {
            "verbosity": "debug",
            "cdk_node_image": "aggkit:local",
            "agglayer_image": "ghcr.io/agglayer/agglayer@sha256:5715855f2cc6834bd84a99a33937915164648547d21bfb55198948b0ae4e0fad",
            "cdk_erigon_node_image": "hermeznetwork/cdk-erigon:v2.61.16-hotfix2",
            "zkevm_contracts_image": "leovct/zkevm-contracts:v9.0.0-rc.5-pp-fork.12",
            "zkevm_prover_image": "hermeznetwork/zkevm-prover:v8.0.0-RC16-fork.12",
            "additional_services": [],
            "consensus_contract_type": "pessimistic",
            "sequencer_type": "erigon",
            "erigon_strict_mode": false,
            "gas_token_enabled": true,
            "gas_token_address": "",
            "agglayer_prover_sp1_key": "",
            "zkevm_use_real_verifier": false,
            "agglayer_prover_primary_prover": "mock-prover",
            "enable_normalcy": true,
            "zkevm_rollup_id": 1,
            "binary_name": "aggkit",
            "components": "aggsender,bridge"
          }
        }

  check-test-single-e2e-result:
    name: Check E2E results
    needs:
      - test-single-e2e
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: ${{ contains(fromJSON('["failure", "cancelled"]'), needs.test-single-e2e.result) }}
