name: Test Unit and SonarCloud analysis

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull_request:
  workflow_dispatch: {}

jobs:
  test-unit:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.22.4]
        goarch: ["amd64"]
    runs-on: amd-runner-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        env:
          GOARCH: ${{ matrix.goarch }}

      - name: Test
        run: make test-unit
        
      # TODO: Uncomment the following lines to enable SonarCloud analysis, once the project is set up in SonarCloud
      # 
      # - name: Analyze with SonarCloud
      #   uses: sonarsource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}